import { CSSProperties } from 'react'

export interface IconProps {
	size?: number
	color?: string
	style?: CSSProperties
	className?: string // when using styled component to override icons
}

export { AddColumn } from './AddColumn'
export { AlignCenter } from './AlignCenter'
export { AlignEnd } from './AlignEnd'
export { AlignStart } from './AlignStart'
export { ArrowLeft } from './ArrowLeft'
export { ArrowRight } from './ArrowRight'
export { BulletedListIcon } from './BulletedList.icon'
export { CardsIcon } from './Cards.icon'
export { ChevronIcon } from './Chevron.icon'
export { CodeIcon } from './Code.icon'
export { Cross } from './Cross'
export { DividerIcon } from './Divider.icon'
export { Download01Icon } from './Download01.Icon'
export { DuplicateIcon } from './Duplicate.icon'
export { StyledEarthIcon } from './EarthIcon.icon'
export { EditIcon } from './EditIcon'
export { EmbedIcon } from './Embed.icon'
export { EmojiIcon } from './Emoji.icon'
export { Expand } from './Expand'
export { ExpandableIcon } from './Expandable.icon'
export { File06Icon } from './File06.Icon'
export { Heading1Icon } from './Heading1.icon'
export { Heading2Icon } from './Heading2.icon'
export { Heading3Icon } from './Heading3.icon'
export { HintIcon } from './Hint.icon'
export { ImageIcon } from './Image.icon'
export { InsertAbove } from './InsertAbove'
export { InsertBelow } from './InsertBelow'
export { JavascriptIcon } from './Javascript.icon'
export { ListIcon } from './List.icon'
export { MessageIcon } from './Message.icon'
export { NoticeAIIcon } from './NoticeAI.icon'
export { NumberedListIcon } from './NumberedList.icon'
export { PageIcon } from './Page.icon'
export { PlayIcon } from './Play.icon'
export { PlusIcon } from './Plus.icon'
export { PreviousNextIcon } from './PreviousNext.icon'
export { QuoteIcon } from './Quote.icon'
export { SearchIcon } from './Search.icon'
export { SixDotsIcon } from './SixDotsIcon'
export { TableIcone } from './Table.icon'
export { TextIcon } from './Text.icon'
export { TodoIcon } from './Todo.icon'
export { TrashIcon } from './TrashIcon'
export { VideoIcon } from './Video.icon'
