version: '3.9'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: notice_mongodb
    ports:
      - '27017:27017'
    networks:
      - notice
    volumes:
      - mongodb:/data/db

  # PostgresSQL
  postgres:
    image: postgres:12-alpine
    container_name: notice_postgres
    ports:
      - '5432:5432'
    networks:
      - notice
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'notice'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  mongodb:
    name: notice_mongodb
  postgres:
    name: notice_postgres

networks:
  notice:
    name: notice_network
