export const LANGUAGES = [
	{ name: 'Plain Text', value: 'plain_text' },
	{ name: 'HTML', value: 'html' },
	{ name: 'Javascript', value: 'javascript', code: 'js' },
	{ name: 'Typescript', value: 'typescript', code: 'ts' },
	{ name: 'JSX', value: 'jsx' },
	{ name: 'TSX', value: 'tsx' },
	{ name: 'Java', value: 'java' },
	{ name: 'Python', value: 'python', code: 'py' },
	{ name: 'XML', value: 'xml' },
	{ name: 'Ruby', value: 'ruby' },
	{ name: 'SASS', value: 'sass' },
	{ name: 'CSS', value: 'css' },
	{ name: 'Markdown', value: 'markdown' },
	{ name: 'MYSQL', value: 'mysql' },
	{ name: 'JSON', value: 'json' },
	{ name: 'JSON5', value: 'json5' },
	{ name: 'Handlebars', value: 'handlebars' },
	{ name: 'Go Lang', value: 'golang' },
	{ name: 'C#', value: 'csharp' },
	{ name: 'C', value: 'c_cpp' },
	{ name: 'Rust', value: 'rust' },
	{ name: 'Clojure', value: 'clojure' },
	{ name: 'Elixir', value: 'elixir' },
]

export const THEMES = [
	{ name: 'One Dark', value: 'one_dark' },
	{ name: 'Pastel On Dark', value: 'pastel_on_dark' },
	{ name: 'Nord Dark', value: 'nord_dark' },
	{ name: 'Vibrant Ink', value: 'vibrant_ink' },
	{ name: 'Solarized Light', value: 'solarized_light' },
	{ name: 'Solarized Dark', value: 'solarized_dark' },
	{ name: 'Cloud9 Night', value: 'cloud9_night' },
	{ name: 'GOB', value: 'gob' },
	{ name: 'Github', value: 'github' },
	{ name: 'IPlastic', value: 'iplastic' },
	{ name: 'Twilight', value: 'twilight' },
	{ name: 'Terminal', value: 'terminal' },
]
