export const de = {
	customization: 'Anpassung',
	translation: 'Übersetzung',
	integrations: 'Integrationen',
	insights: 'Einblicke',
	FreePlan: 'Kostenloser Plan',
	upgrade: 'Upgrade',
	yourProfile: 'Ihr Profil',
	general: 'Allgemein',
	layout: 'Layout',
	theme: 'Thema',
	advanced: 'Erweitert',
	styling: 'Styling',
	code: 'Code',
	billing: 'Abrechnung',
	aiSettings: 'KI-Einstellungen',
	aiSettingsDescription:
		'Willkommen bei den AI-Einstellungen, wo Sie steuern, wie unsere AI Inhalte für diesen Arbeitsbereich generiert',
	aiSettingSection1: 'Was machst du?',
	aiSettingSection1Description:
		'Helfen Sie uns, Ihre Arbeitslinie oder den Schwerpunkt Ihres Unternehmens zu verstehen. Bitte geben Sie eine kurze Beschreibung Ihres Geschäfts oder Berufs an.',
	aiSettingSection1Placeholder:
		'Ich leite eine kreative Agentur, die sich auf digitale Marketingstrategien und Content-Erstellung spezialisiert hat',
	aiSettingSection2: 'Wie ist Ihr Ton?',
	aiSettingSection2Description:
		'Definieren Sie den Ton, den Sie für den Text in Ihrem Arbeitsbereich wünschen. Teilen Sie uns den Ton mit, der zu Ihrem Kommunikationsstil passt.',
	aiSettingSection2Placeholder:
		'Wir klingen professionell, aber freundlich, und teilen unser Fachwissen auf eine Weise, die leicht zu verbinden ist',
	aiSettingSection3: 'Einblick in Ihren bevorzugten Schreibstil',
	aiSettingSection3Description:
		'Geben Sie ein oder zwei Beispiele für Ihren Schreibstil oder einen Abschnitt eines Ihrer Lieblingstexte an. Unsere KI wird sich anpassen und den Text im gleichen Stil liefern.',
	aiSettingSection3Placeholder: `Als Gregor Samsa eines Morgens aus unruhigen Träumen erwachte, fand er sich in seinem Bett zu einem ungeheueren Ungeziefer verwandelt.`,
	aiSettingsModelSettings: 'KI-Modell-Einstellungen',
	aiSettingModelSection: 'Wählen Sie Ihr KI-Modell',
	aiSettingModelSectionDescription:
		'Wählen Sie das KI-Generierungsmodell aus, das Ihren Präferenzen am besten entspricht.',
	aiSettingGPT4Tooltip: 'Optimierter',
	aiSettingGPT3Tooltip: 'Schneller',
	edit: 'bearbeiten',
	save: 'speichern',
	skip: 'überspringen',
	changeAISettings: 'AI-Einstellungen ändern',
	PleaseClickToEditTheSettings: 'Bitte klicken Sie, um die Einstellungen zu bearbeiten',
	billingDetailsAndInvoices: 'Abrechnungsdetails & Rechnungen',
	overview: 'Überblick',
	currentPlan: 'Aktueller Plan',
	nextBillingOn: 'Nächste Abrechnung am',
	nextBillingAmount: 'Nächster Rechnungsbetrag',
	numberOfProjects: 'Anzahl der Projekte',
	reachesSubscriptionPage: 'Erreicht die Abonnement-Seite',
	billingPageUpgradeButton: 'Upgrade-Knopf auf der Abrechnungsseite',
	upgradeYourPlan: 'Upgraden Sie Ihren Plan',
	billingInfoAndPayment: 'Abrechnungsinformationen & Zahlung',
	manageAllYourBilling: 'Verwalten Sie hier alle Ihre Abrechnungsinformationen und Zahlungsmethoden',
	manageBillingDetails: 'Abrechnungsdetails verwalten',
	invoicesHistory: 'Rechnungshistorie',
	invoiceID: 'Rechnungs-ID',
	date: 'Datum',
	total: 'Gesamt',
	status: 'Status',
	invoiceReceipt: 'Rechnung/Quittung',
	download: 'Herunterladen',
	noInfoAvailableYet: 'Noch keine Informationen verfügbar',
	hideBranding: 'Branding verbergen',
	hideBrandingDescription: 'Verbirgt das Branding von Notice in Ihrem Projekt.',
	handleTitleTagTitle: 'Verwalten des <title />-Tags',
	titleTagDescription: 'Wenn aktiviert, verwaltet Notice das <title />-Tag Ihres Projekts.',
	projectLogo: 'Projektlogo',
	projectLogoDescription: 'Ihr Projektlogo kann an verschiedenen Stellen Ihres Projekts angezeigt werden.',
	faviconDescription: 'Verwenden Sie Ihr Logo als Favicon.',
	faviconWarning: 'Sie müssen ein <b>Projektlogo</b> oben hochladen, um diese Funktion zu aktivieren.',
	uploadImage: 'Bild hochladen',
	configureLogoRedirect: 'Konfigurieren Sie die Adresse, auf die das Logo weiterleitet',
	navigationType: 'Navigationstyp',
	navigationTypeDescription: `Query-Parameter verwendet den Wert 'page=' in der URL zur Navigation. Slash verwendet den klassischen '/' Unterordner.`,
	stopUserTracking: 'Nutzertracking stoppen',
	stopUserTrackingDescription: 'Notice wird keine Daten sammeln, um Ihnen Statistiken zur Verfügung zu stellen.',
	stopUserTrackingWarning: 'Das Statistik-Dashboard wird deaktiviert.',
	headerSpace: 'Kopfbereich',
	projectTitle: 'Projekttitel',
	homeButton: 'Home-Knopf',
	topSpace: 'Oberer Bereich',
	contactForm: 'Kontaktformular',
	emailToReceiveMessages: 'E-Mail, um Nachrichten zu erhalten',
	themeSwitch: 'Themenwechsel',
	languageSelector: 'Sprachauswahl',
	breadcrumbNavigation: 'Breadcrumb-Navigation',
	timeToRead: 'Lesezeit',
	shareToFacebook: 'Auf Facebook teilen',
	shareToTwitter: 'Auf Twitter teilen',
	shareToLinkedIn: 'Auf LinkedIn teilen',
	leftSpace: 'Linker Bereich',
	navigationMenu: 'Navigationsmenü',
	rightSpace: 'Rechter Bereich',
	anchorMenu: 'Anker-Menü',
	bottomSpace: 'Unterer Bereich',
	bottomNavigation: 'Untere Navigation',
	readMoreArticles: 'Weitere Artikel lesen',
	setProjectTitle: 'Projekttitel festlegen',
	setProjectTitleDescription: 'Zeigt den Projekttitel im oberen Bereich für jede Seite an.',
	navMenuDesc: 'Navigationsmenü links, das einfachen Zugang zu Ihrem Projekt bietet.',
	searchDescription: 'Erlauben Sie Benutzern, innerhalb Ihres Projekts zu suchen. Sie werden auch',
	analyticsSupport: 'Analytik-Unterstützung',
	searchDescription2: 'Analytik-Unterstützung von Notice für Ihre Projektsuche erhalten.',
	themeSwitchDescription: 'Sie können Benutzern erlauben, das Thema Ihres Projekts zu ändern. Sie können Ihr Thema',
	hereInsideColors: 'hier bei den Farben einrichten.',
	languageSwitchDescription:
		'Sie können Benutzern erlauben, die Sprache Ihres Projekts zu ändern. Sie können Ihre Übersetzungen',
	here: 'hier',
	allowNavDescription: 'Benutzern erlauben, zwischen Seiten mit dem Navigationsmenü zu navigieren.',
	displayHomeButtonDescription: 'Einen Home-Knopf anzeigen, um Benutzern die Navigation zur Startseite zu ermöglichen.',
	timeToReadDescription: 'Die geschätzte Lesezeit für eine Seite anzeigen.',
	facebookShareDescription: 'Benutzern erlauben, Ihre Artikel auf Facebook zu teilen.',
	twitterShareDescription: 'Benutzern erlauben, Ihre Artikel auf Twitter zu teilen.',
	linkedinShareDescription: 'Benutzern erlauben, Ihre Artikel auf LinkedIn zu teilen.',
	nextPrevDescription:
		'Knöpfe hinzufügen, um auf der Unterseite der Seite zu den nächsten und vorherigen Seiten zu navigieren.',
	anchorRightMenuDescription:
		'Ein Menü auf der rechten Seite hinzufügen, das Benutzern erlaubt, innerhalb der Untertitel der aktuellen Seite zu navigieren.',
	allowRecommendedArticlesDescription: 'Benutzern erlauben, weitere zum aktuellen Artikel verwandte Artikel zu lesen.',
	pageTitle: 'Seitentitel',
	colors: 'Farben',
	lightBgColor: 'Helle Hintergrundfarbe',
	lightFontColor: 'Helle Schriftfarbe',
	lightHighlightColor: 'Helles Hervorhebungsfarbe',
	darkBgColor: 'Dunkle Hintergrundfarbe',
	darkFontColor: 'Dunkle Schriftfarbe',
	darkHighlightColor: 'Dunkle Hervorhebungsfarbe',
	fonts: 'Schriftarten',
	fontFamily: 'Schriftfamilie',
	fontSize: 'Schriftgröße',
	spacing: 'Abstand',
	blockPadding: 'Blockabstand',
	maxWidth: 'Maximale Breite',
	maxWidthDescription: 'Maximale Breite für die Hauptspalte festlegen',
	icons: 'Symbole',
	iconStroke: 'Symbolstrichbreite',
	headings: 'Überschriften',
	h1Weight: 'H1 Gewicht',
	h1Size: 'H1 Größe',
	h2Size: 'H2 Größe',
	h2Weight: 'H2 Gewicht',
	h3Size: 'H3 Größe',
	h3Weight: 'H3 Gewicht',
	headingsPadding: 'Überschriftenabstand',
	titleFontSize: 'Schriftgröße des Titels',
	fontFamilyDescription:
		'Um Schriftarten zu erkunden, gehen Sie zu <a href="https://fonts.google.com/" target="_blank">Google Fonts.</a>',
	text: 'Text',
	textLineHeight: 'Textzeilenhöhe',
	textLetterSpacing: 'Textbuchstabenabstand',
	codeHtmlDesc: 'Der geschriebene Code wird in den ',
	codeHtmlDesc2: ' Ihres Notice-Projekts eingefügt.',
	CSSDesc: 'Schreiben Sie etwas CSS-Code, um das Aussehen Ihres Projekts zu ändern',
	JavascriptDesc: 'Schreiben Sie etwas Javascript-Code, um das Verhalten Ihres Projekts zu ändern',
	insightsDesc: 'Inhaltsstrategie vorantreiben und Kundensupport mit Daten über Benutzerverhalten verbessern.',
	publishing: 'Veröffentlichung',
	publish: 'Veröffentlichen',
	visitPage: 'Seite besuchen',
	newProject: 'Neues Projekt',
	createNewProject: 'Neues Projekt erstellen',
	newPage: 'Neue Seite',
	addNewPage: 'Eine neue Seite innerhalb des aktuellen Projekts hinzufügen',
	workspaceSettings: 'Arbeitsbereicheinstellungen',
	accountSettings: 'Kontoeinstellungen',
	supportAndCommunity: 'Support & Community',
	signOut: 'Abmelden',
	whatIsNew: 'Was gibt’s Neues',
	inviteCollaborators: 'Mitarbeiter einladen',
	inviteCollaboratorsDescription:
		'Viele Hände machen leicht Arbeit. Laden Sie Ihre Kollegen ein, gemeinsam an Ihren Projekten zu arbeiten.',
	emailAddress: 'E-Mail-Adresse',
	admin: 'Administrator',
	editor: 'Redakteur',
	viewer: 'Betrachter',
	owner: 'Eigentümer',
	close: 'Schließen',
	invite: 'Einladen',
	translationDescription: 'Übersetzen Sie Ihren Inhalt in mehr als 100 Sprachen.',
	selectBlock: 'Sie können einen Block auswählen, indem Sie das',
	selectProjectLanguage: 'Wählen Sie die Standardsprache dieses Projekts',
	validate: 'Bestätigen',
	selectLanguageHint: 'Hinweis: Dies ist die Sprache Ihres aktuellen Projekts.',
	configureTranslation: 'Übersetzung konfigurieren',
	translationStatus: 'Übersetzungsstatus',
	selected: 'Ausgewählt',
	translated: 'Übersetzt',
	notTranslated: 'Nicht übersetzt',
	translationOutOfDate: 'Übersetzung veraltet',
	translateBlock: 'Block übersetzen',
	markAsIncomplete: 'Als unvollständig markieren',
	markAsComplete: 'Als abgeschlossen markieren',
	markAsCompleteAndGoToNext: 'Als abgeschlossen markieren und zum nächsten gehen',
	anotherNoticeTabIsOpened: 'Ein anderer Notice-Tab ist geöffnet',
	pleaseReloadToAvoidMismatch: 'Bitte laden Sie dieses Fenster neu, um Dateninkonsistenzen zu vermeiden.',
	reload: 'Neu laden',
	oopsNoResultsWereFound: 'Ups! Es wurden noch keine Ergebnisse gefunden.',
	tryAgainNoResults: 'Versuchen Sie es erneut mit einem anderen Zeitraum.',
	configureYourTranslation: 'Konfigurieren Sie Ihre Übersetzung',
	allowUsersToChangeLang: 'Erlauben Sie Benutzern, die Sprache Ihres Projekts zu ändern.',
	addsALangQueryLike: 'Fügt eine Sprachabfrage wie',
	toYourProjectUrl: 'zu Ihrer Projekt-URL hinzu.',
	addLanguageQueryToUrl: 'Sprachparameter zur URL hinzufügen',
	chooseADefaultLanguage: 'Wählen Sie eine Standardsprache',
	availableLanguages: 'Verfügbare Sprachen',
	ifYouWantMoreLanguages: 'Wenn Sie mehr Sprachen möchten',
	contactUs: 'Kontaktieren Sie uns',
	letUsKnow: 'lassen Sie es uns wissen.',
	languageSelectorWarning:
		'Der Sprachauswähler kann auch in Ihrem Layout des oberen Bereichs verwaltet werden, indem Sie',
	clickingHere: 'hier klicken',
	addNew: 'Neu hinzufügen',
	translateTo: 'Übersetzen in',
	translateThisPage: 'Diese Seite übersetzen',
	stepByStepGuide: 'Schritt-für-Schritt-Anleitung',
	manyHandsMakeLightWork: 'Viele Hände machen der Arbeit ein Ende',
	createAndCustomizeContent: 'Inhalte erstellen und anpassen',
	clickOnPublish: 'Klicken Sie auf Veröffentlichen',
	deployItAnywhere: 'Überall einsetzen, indem Sie zum Tab Integrationen gehen',
	inviteColleaguesToCollaborate: 'Kollegen einladen, gemeinsam an Ihren Projekten zu arbeiten.',
	inviteYourTeam: 'Laden Sie Ihr Team ein',
	makeTheMostOfNotice: 'Nutzen Sie Notice optimal',
	getInTouchWithUs: 'Nehmen Sie Kontakt mit uns auf',
	getInTouchDescription:
		'Brauchen Sie Hilfe oder haben Sie Funktionswünsche? Schicken Sie uns eine Nachricht oder treten Sie unserer Community auf Slack bei.',
	accountSettingsDescription: 'Verwalten Sie Ihr Profil, Ihre Einstellungen und Anmeldeinformationen',
	dashboardLanguage: 'Dashboard-Sprache',
	updateEmail: 'E-Mail aktualisieren',
	featureComingSoon: 'Funktion demnächst verfügbar...',
	signOnWithGoogle: 'Einmalanmeldung mit Google einrichten und mit einem Klick anmelden',
	yourGoogleAccountHasBeenUnlinked: 'Ihr Google-Konto wurde erfolgreich von Ihrem Konto getrennt.',
	unlinkAccount: 'Konto trennen',
	linkAccount: 'Konto verknüpfen',
	singleSignOnGithub: 'Einmalanmeldung mit Github einrichten und mit einem Klick anmelden',
	githubAccountHasBeenUnlinked: 'Ihr Github-Konto wurde erfolgreich von Ihrem Konto getrennt.',
	signOutDescription: 'Sie können sich sicher von den aktuellen Sitzungen abmelden und sich später wieder anmelden',
	accountDeletion: 'Kontolöschung',
	accountDeletionDescription: 'Durch das Löschen Ihres persönlichen Kontos werden alle zugehörigen Daten gelöscht.',
	deleteAccount: 'Konto löschen',
	deleteMyAccountSubject: 'Mein Konto löschen',
	deleteMyAccountBody: 'Hallo, ich möchte mein Konto löschen',
	settings: 'Einstellungen',
	account: 'Konto',
	myWorkspaces: 'Meine Arbeitsbereiche',
	workspace: 'Arbeitsbereich',
	collaborators: 'Mitarbeiter',
	plans: 'Pläne',
	profilePicture: 'Profilbild',
	profilePictureDescription: 'Verwenden Sie ein quadratisches Bild mit mindestens 64 Pixeln Kantenlänge',
	fullName: 'Vollständiger Name',
	myWorkspacesDescription: 'Eine globale Übersicht über alle Arbeitsbereiche, denen Sie beigetreten sind',
	workspaces: 'Arbeitsbereiche',
	created: 'Erstellt',
	manageWorkspaceProfile: 'Arbeitsbereichsprofil verwalten',
	workspaceProfile: 'Arbeitsbereichsprofil',
	workspaceLogo: 'Arbeitsbereichslogo',
	displayName: 'Anzeigename',
	workspaceDeletion: 'Löschung des Arbeitsbereichs',
	workspaceDeletionDescription: 'Durch das Löschen Ihres Arbeitsbereichs werden alle zugehörigen Daten gelöscht.',
	deleteWorkspace: 'Arbeitsbereich löschen',
	storage: 'Speicher',
	storageDescription: '(Bilder, Videos, Dateien, ...)',
	deleteWorkspaceDescription: 'Sind Sie sicher, dass Sie diesen Arbeitsbereich löschen möchten?',
	deleteWorkspaceWarning: 'Diese Aktion kann nicht rückgängig gemacht werden.',
	cancel: 'Abbrechen',
	confirm: 'Bestätigen',
	visits: 'Besuche',
	statistics: 'Statistiken',
	visitsByTimeSpan: 'Besuche nach Zeitspanne',
	location: 'Standort',
	locationDescription: 'Der Standort Ihrer Besucher',
	device: 'Gerät',
	deviceDescription: 'Das von Ihren Besuchern verwendete Gerät',
	browser: 'Browser',
	browserDescription: 'Der von Ihren Besuchern verwendete Browser',
	OSdescription: 'Das von Ihren Besuchern verwendete Betriebssystem',
	integration: 'Integration',
	hosting: 'Hosting',
	noticeDomain: 'Notice-Domain',
	noticeDomainDescription: 'Ändern Sie den Namen der gehosteten Notice-Domain.',
	allowedCharacters: 'Erlaubte Zeichen',
	letters: 'Buchstaben',
	numbers: 'Zahlen',
	and: 'und',
	domainName: 'Domainname',
	customDomainDescription:
		'Fügen Sie Ihre eigene benutzerdefinierte Domain hinzu und verknüpfen Sie sie mit Ihrem Projekt.',
	customDomain: 'Benutzerdefinierte Domain',
	customDomainMissing: 'Derzeit haben Sie keine benutzerdefinierte Domain, die mit diesem Projekt verknüpft ist',
	customDomainPresent: 'Derzeit haben Sie eine benutzerdefinierte Domain, die mit diesem Projekt verknüpft ist',
	configure: 'Konfigurieren',
	whatDomainWouldYouLikeToLink: 'Welche Domain möchten Sie verknüpfen?',
	hostnameIsInvalid: 'Hostname ist ungültig. Es sind nur Unterdomains erlaubt.',
	mustOwnSubdomainAndAbilityToEditDNS:
		'Sie müssen die Unterdomain besitzen und die Möglichkeit haben, deren DNS-Einträge zu bearbeiten.',
	configureDNS: 'DNS konfigurieren',
	others: 'Andere',
	webflowIntegration: 'Fügen Sie Notice-Blöcke mit einem Klick Ihrer Webflow-Website hinzu.',
	wordpressIntegration: 'Ermächtigen Sie Ihr Wordpress-Erlebnis mit dem Notice-Plugin.',
	shopifyIntegration:
		'Bieten Sie ein großartiges Kundenerlebnis, indem Sie das Notice-Plugin in Ihrem Store verwenden.',
	umsoIntegration: 'Fügen Sie Ihrem Umso-Webauftritt Notice-Blöcke hinzu und gewinnen Sie Einblicke in Ihr Publikum.',
	wixIntegration:
		'Notice in Wix zu integrieren ist einfach. Fügen Sie einfach einen Integrationsblock hinzu und alles ist fertig!',
	squarespaceIntegration:
		'Wie gewohnt schnell. Fügen Sie einen Codeblock hinzu und kopieren Sie Ihre Notice-ID, um Ihre Inhalte anzuzeigen.',
	unicornIntegration:
		'Schneller Gewinn, um Ihre Webseite mit intelligenten Blöcken zu verbessern und zu personalisieren.',
	reactIntegration: 'Notice-Blöcke lassen sich in nur einem Schritt problemlos in React integrieren.',
	nextIntegration: 'Für die Liebhaber des Next.js SSR-Frontend-Frameworks, nahtlose Integration.',
	vueIntegration: 'Integrieren Sie Notice in weniger als einer Minute in Ihr Vue.js-Projekt.',
	nuxtIntegration: 'Für die Liebhaber des Nuxt SSR-Frontend-Frameworks, nahtlose Integration.',
	linkIntegration: 'Die einfachste Lösung, teilen Sie einfach den Link! Sie brauchen nicht einmal eine Webseite.',
	htmlIntegration: 'Die Standardlösung für Webseiten, falls Sie Ihr spezifisches Framework nicht finden.',
	iframeIntegration: 'Einfach zu verwenden, iframes passen überall, sogar in mobilen Anwendungen.',
	rawJSONIntegration: 'Für fortgeschrittene Benutzer, die die vollständige Kontrolle über ihre Projekte wünschen.',
	qrcodeIntegration: 'Ihre Inhalte direkt an den Fingerspitzen der Benutzer! Teilen Sie Ihren eigenen QR-Code :)',
	integrationsDescription: 'Erhöhen Sie Ihre Sichtbarkeit, indem Sie Ihre Notice überall teilen und integrieren.',
	categories: 'Kategorien',
	all: 'Alle',
	needADifferentIntegrationAndCannotFindItHere:
		'Brauchen Sie eine andere Integration und können sie hier nicht finden?',
	shareables: 'Teilbares',
	useTemplates: 'Vorlagen verwenden',
	useAIGeneration: 'KI-Generierung nutzen',
	selectProjectTip: 'Sie können zwischen KI-Generierung und Vorlagen wechseln',
	preFilledTemplate: 'Vorausgefüllte Vorlage',
	helpCenter: 'Hilfezentrum',
	termsOfuse: 'Nutzungsbedingungen',
	privacyPolicy: 'Datenschutzrichtlinie',
	jobBoard: 'Stellenbörse',
	getStarted: 'Anleitung',
	changelog: 'Änderungsprotokoll',
	missionAndValues: 'Mission & Werte',
	investorsReport: 'Investorenbericht',
	startFromScratch: 'Von Grund auf neu beginnen',
	helpOurAIGenerateYour: 'Helfen Sie unserer KI, Ihre',
	provideYourWebsiteURL: 'Geben Sie Ihre bestehende Website-URL an',
	weFoundAWebsite: 'Wir haben eine Webseite gefunden, die mit Ihrer E-Mail-Adresse verlinkt ist',
	makeSureProvidedWebsiteAlreadyExists: 'Stellen Sie sicher, dass die angegebene Webseite bereits existiert',
	AIExplanation: 'Unsere KI durchläuft die angegebene Webseite und generiert eine individuelle',
	basedOnTheWebsiteInformation: 'basierend auf den Informationen der Webseite.',
	youCanUseAnyExistingURL: 'Sie können jede vorhandene URL verwenden.',
	enhanceYourGeneration: 'Sie können Ihre Generierung verbessern, indem Sie weitere Anweisungen hinzufügen',
	giveInstructions: 'Geben Sie Anweisungen, um Ihre',
	makeSureThisPromptIsMatching:
		'Bitte stellen Sie sicher, dass dieser Prompt mit dem ausgewählten Projekttyp übereinstimmt',
	writeItInFrenchOnlyUsePastTense: 'Beispiel: Schreiben Sie es auf Französisch, verwenden Sie nur Vergangenheitsform',
	backToList: 'Zurück zur Liste',
	pricingDescription: 'Unsere Preisgestaltung ist unkompliziert und auf Ihre Geschäftsziele ausgerichtet.',
	monthlyTokenAmount: 'Monatliche Token-Menge',
	billingPeriod: 'Abrechnungszeitraum',
	monthly: 'Monatlich',
	yearly: 'Jährlich',
	oneMonthFree: '1 Monat kostenlos',
	customizeYourNewContentsHome: 'Passen Sie das Zuhause Ihres neuen Inhalts an',
	manageSmartContentForYourCompany: 'Verwalten Sie intelligenten Inhalt für Ihr Unternehmen',
	activateContentSynergiesForYourTeam: 'Aktivieren Sie Content-Synergien für Ihr Team',
	forThoseNeedingAnEnterpriseGradeSolution: 'Für diejenigen, die eine Unternehmenslösung benötigen',
	letsTalk: 'Lassen Sie uns reden',
	numberOfCollaborators: 'Anzahl der Mitarbeiter',
	numberOfWorkspaces: 'Anzahl der Arbeitsbereiche',
	integrateAnywhere: 'Überall integrieren',
	removeNoticeBranding: 'Notice-Branding entfernen',
	aiAssistant: 'KI-Assistent',
	customSupportAndHelp: 'Individuelle Unterstützung und Hilfe',
	premiumCdn: 'Premium-CDN',
	ssoEnabled: 'SSO aktiviert',
	onPremiseData: 'Vor-Ort-Daten',
	contentAndSeoAudit: 'Inhalts- und SEO-Audit',
	downgrade: 'Herabstufen',
	newWorkspace: 'Neuer Arbeitsbereich',
	createANewWorkspace: 'Einen neuen Arbeitsbereich erstellen',
	enterNameOfNewWorkspace: 'Geben Sie den Namen Ihres neuen Arbeitsbereichs ein',
	create: 'Erstellen',
	signIn: 'Anmelden',
	signInDescription:
		'Melden Sie sich schnell mit einem Ihrer sozialen Konten an, oder verwenden Sie Ihre Arbeits-E-Mail.',
	signUp: 'Registrieren',
	continueWithGoogle: 'Mit Google fortfahren',
	continueWithGithub: 'Mit Github fortfahren',
	orSignInUsingWorkEmail: 'Oder melden Sie sich mit Ihrer Arbeits-E-Mail an',
	enterWorkEmail: 'Arbeits-E-Mail eingeben',
	enterTemporaryCode: 'Temporären Code eingeben',
	weJustSentYouATemporaryLoginCode: 'Wir haben Ihnen gerade einen temporären Anmeldecode gesendet.',
	pleaseCheckYourInbox: 'Bitte überprüfen Sie Ihren Posteingang.',
	alreadyHaveAnAccountSignIn: 'Sie haben bereits ein Konto? Anmelden',
	continueWithLoginCode: 'Mit Anmeldecode fortfahren',
	continueWithEmail: 'Mit E-Mail fortfahren',
	selectYourProject: 'Wählen Sie Ihr Projekt aus',
	chooseYourIntegration: 'Wählen Sie Ihre Integration',
	publishingYourProject: 'Veröffentlichung Ihres Projekts',
	projectCreated:
		'Ihr Notice-Projekt wurde erstellt! Fügen Sie dieses neue Projekt Ihrer Website hinzu, indem Sie eine unserer Integrationen oder direkt über den für Sie vorab generierten Link verwenden.',
	signInMethods: 'Anmeldemethoden',
	signInMethodsDescription: 'Aktualisieren Sie die E-Mail, mit der Sie sich in Ihrem Konto anmelden',
	joinOurSlackCommunityForUpdatesAndFeedback:
		'Treten Sie unserer Slack-Community bei, um Updates zu erhalten und Feedback zu geben, und vernetzen Sie sich mit uns in den sozialen Medien.',
	joinSlack: 'Slack beitreten',
	joinTheAcademy: 'Der Akademie beitreten',
	readOurDoc: 'Unsere Dokumentation lesen',
	checkOurTutorials: 'Sehen Sie sich unsere Tutorials an',
	sendUsAnEmail: 'Senden Sie uns eine E-Mail',
	pleaseEnterYourFirstName: 'Bitte geben Sie Ihren Vornamen ein.',
	pleaseEnterYourLastName: 'Bitte geben Sie Ihren Nachnamen ein.',
	firstname: 'Vorname',
	lastname: 'Nachname',
	pleasEnterAValidPhoneNumber: 'Bitte geben Sie eine gültige Telefonnummer ein.',
	phoneNumber: 'Telefonnummer',
	pleaseEnterYourCompanyName: 'Bitte geben Sie Ihren Firmennamen ein.',
	companyName: 'Firmenname',
	pleaseChooseYourCompanySize: 'Bitte wählen Sie Ihre Firmengröße.',
	companySize: 'Firmengröße',
	pleaseChooseYourRoleInTheCompany: 'Bitte wählen Sie Ihre Rolle im Unternehmen.',
	companyRole: 'Rolle im Unternehmen',
	startCreating: 'Beginnen Sie mit dem Erstellen !',
	welcomeToNotice: 'Willkommen bei Notice !',
	pleaseHelpUsWithForm: 'Bitte helfen Sie uns bei dem Prozess, Ihnen das komplette Notice-Erlebnis zu bieten.',
	preview: 'Vorschau',
	rename: 'Umbenennen',
	duplicate: 'Duplizieren',
	exportMarkdown: 'Markdown exportieren',
	delete: 'Löschen',
	exportJSON: 'JSON exportieren',
	type: 'Typ',
	forCommands: 'für Befehle',
	paragraph: 'Absatz',
	justWriteDownSomeText: 'Schreiben Sie einfach einen Text',
	basicBlocks: 'Grundbausteine',
	heading: 'Überschrift',
	bigSectionHeading: 'Große Abschnittsüberschrift',
	mediumSectionHeading: 'Mittlere Abschnittsüberschrift',
	smallSectionHeading: 'Kleine Abschnittsüberschrift',
	bulletedList: 'Aufzählungsliste',
	organizeContentWithBullets: 'Inhalte mit Aufzählungszeichen organisieren',
	numberedList: 'Nummerierte Liste',
	createANumberedList: 'Nummerierte Liste erstellen',
	captureACodeSnippet: 'Code-Schnipsel erfassen',
	hint: 'Hinweis',
	provideHelpfulInformation: 'Hilfreiche Informationen bereitstellen',
	quote: 'Zitat',
	highlightASpecificPassageOfText: 'Einen spezifischen Textabschnitt hervorheben',
	divider: 'Trennlinie',
	separateDifferentBlocks: 'Verschiedene Blöcke trennen',
	toDo: 'To-Do',
	keepTrackOfTasksOrItems: 'Aufgaben oder Elemente verfolgen',
	media: 'Medien',
	image: 'Bild',
	uploadAnImageFile: 'Ein Bild hochladen',
	document: 'Dokument',
	uploadADocument: 'Ein Dokument hochladen',
	video: 'Video',
	addAVideo: 'Ein Video hinzufügen',
	advancedBlocks: 'Erweiterte Blöcke',
	table: 'Tabelle',
	organizeWithRowsAndColumns: 'Mit Reihen und Spalten organisieren',
	expandable: 'Erweiterbar',
	addACollapsableBlock: 'Einen zusammenklappbaren Block hinzufügen',
	textAIGeneration: 'Text KI-Generierung',
	letOurRobotCreateYourContent: 'Lassen Sie unseren Roboter Ihren Inhalt erstellen',
	imageAIGeneration: 'Bild KI-Generierung',
	letOurRobotCreateYourImages: 'Lassen Sie unseren Roboter Ihre Bilder erstellen',
	javascript: 'Javascript',
	embedJavascript: 'Javascript einbetten',
	youtube: 'Youtube',
	embedYoutubeVideos: 'Youtube-Videos einbetten',
	justCopyPasteTheLinkOfYourVideo:
		'Kopieren Sie einfach den Link Ihres Videos in einen leeren Absatz, um automatisch ein Youtube-Video einzubetten. Beispiel-Link: https://www.youtube.com/watch?v=m4fDm4rdUdk',
	embedLoomVideos: 'Loom-Videos einbetten',
	justCopyPasteLoomVideo:
		'Kopieren Sie einfach den Link Ihres Videos in einen leeren Absatz, um automatisch ein Loom-Video einzubetten. Beispiel-Link: https://www.loom.com/share/36656bc4afb84de2bb829183f46a1b40',
	embedVimeos: 'Vimeo-Videos einbetten',
	embedVimeosInstructions:
		'Kopieren Sie einfach den Link Ihres Videos in einen leeren Absatz, um automatisch ein Vimeo-Video einzubetten. Beispiel-Link: https://vimeo.com/251147627',
	embedAirtableInstructions:
		'Kopieren Sie den Link Ihrer Tabellenansicht in einen leeren Absatz, um automatisch ein AirTable einzubetten. Beispiel-Link: https://airtable.com/appeh8s8bwMI7JjlW/shro43JbOcXFQH0tQ/tblnrBMRpvfrcqkko',
	AIIsWriting: 'KI schreibt...',
	Keep: 'Behalten',
	Retry: 'Wiederholen',
	DescribeWhatYouWantAI: 'Beschreiben Sie, was Sie unserer KI erstellen möchten',
	LetOurAICreate: 'Lassen Sie unsere KI Ihre Seite erstellen',
	LetOurAICreateImage: 'Ein Bild erstellen, das von dieser Seite inspiriert ist',
	freeTrialEndsIn: 'Ihre kostenlose Testversion endet in X Tagen.',
	AIIsGeneratingAnImageIdea: 'KI generiert eine Bildidee...',
	AIIsGeneratingImage: 'KI generiert ein Bild...',
	GenImagePlaceholder: 'Ein Sonnenblumenfeld am Ende des Tages. Im Stil von Van Gogh Gemälden.',
	metadata: 'Metadaten',
	pageMetadata: 'Seiten-Metadaten',
	giveInformationForSEO: 'Bereichern Sie diese Seite mit Informationen zur Verbesserung von SEO und Vorschauen',
	author: 'Autor',
	editMyName: 'Meinen Namen bearbeiten',
	tags: 'Schlagwörter',
	datePublished: 'Veröffentlichungsdatum',
	addATag: 'Schlagwort hinfügen',
	advancedOptions: 'Erweiterte Optionen',
	tellGoogleExists: 'Google mitteilen, dass Ihr Projekt existiert',
	tellGoogleExistsDescription: 'Um Ihr Projekt ordnungsgemäß zu indizieren, müssen Sie Ihre Website hier verifizieren ',
	clickHereToFollowOurGuide: 'Klicken Sie hier, um unserer Anleitung zu folgen',
	explanationDateOfPublication: 'Indem Sie ein zukünftiges Datum einstellen, wird die Seite bis zum',
	articleHiddenDateFuture: 'Dieser Artikel ist verborgen, weil das Datum in der Zukunft liegt.',
	blockMenuChangeImageCover: 'Bildcover ändern',
	blockMenuAddImageCover: 'Bildcover hinzufügen',
	blockMenuDuplicate: 'Duplizieren',
	blockMenuDelete: 'Löschen',
	blockMenuOnlyText: 'Nur Text',
	blockMenuWithImage: 'Mit Bild',
	blockMenuPageSummary: 'Seitenzusammenfassung',
	blockMenuBorder: 'Rahmen',
	blockMenuLayout: 'Layout',
	blockMenuDisplay: 'Anzeige',
	blockMenuStyle: 'Stil',
	subPageUpgradeSucessTitle: 'Upgrade Erfolgreich',
	subPageUpgradeSuccessMsg:
		'Herzlichen Glückwunsch! 🎉 Ihr Konto wurde erfolgreich aktualisiert. Vielen Dank, dass Sie sich für Notice entschieden haben, um Ihr Erlebnis zu verbessern!',
	subPageGoBack: 'Zurück zur Bearbeitung',
	deleteProjectDeleteProject: 'Projekt löschen',
	deleteProjectAreYouSure: 'Sind Sie sicher, dass Sie dieses Projekt löschen möchten?',
	deleteWarning: 'Diese Aktion kann nicht rückgängig gemacht werden.',
	cancelButton: 'Abbrechen',
	confirmButton: 'Bestätigen',
	deletePageDeletePage: 'Seite löschen',
	deletePageAreYouSure:
		'Diese Aktion wird diese Seite und alle zugehörigen Inhalte dauerhaft löschen, sind Sie sicher, dass Sie fortfahren möchten?',
	pasteLinkHere: 'Link hier einfügen',
	addLink: 'Link hinzufügen',
	removeLink: 'Link entfernen',
	selectAnImage: 'Bild auswählen',
	selectADocument: 'Dokument auswählen',
	selectAVideo: 'Video auswählen',
	selectAnAudio: 'Audio auswählen',
	dropYourFileHere: 'Lassen Sie Ihre Datei hier fallen, um mit dem Hochladen zu beginnen oder',
	anyDocTypeAccepted: 'Jede Art von Dokument wird akzeptiert',
	acceptedTypes: 'Akzeptierte Arten',
	browseFiles: 'Dateien durchsuchen',
	filterFiles: 'Dateien filtern',
	files: 'Dateien',
	enterAnURL: 'Geben Sie eine URL ein',
}
