export const en = {
	customization: 'Customization',
	translation: 'Translation',
	integrations: 'Integrations',
	insights: 'Insights',
	FreePlan: 'Free Plan',
	upgrade: 'Upgrade',
	yourProfile: 'Your profile',
	general: 'General',
	layout: 'Layout',
	theme: 'Theme',
	advanced: 'Advanced',
	styling: 'Styling',
	code: 'Code',
	billing: 'Billing',
	aiSettings: 'AI Settings',
	aiSettingsDescription:
		'Welcome to AI Settings, where you take control of how our AI generates content for this workspace',
	aiSettingSection1: 'What do you do ?',
	aiSettingSection1Description: `Help us understand your line of work or your company's focus. Please provide a brief description of your
	business or profession.`,
	aiSettingSection1Placeholder: `I run a creative agency that specializes in digital marketing strategies and content creation`,
	aiSettingSection2: 'What is your tone ?',
	aiSettingSection2Description: `Define the tone you desire for the text in your workspace. Share with us the kind of tone that aligns with
	your communication style.`,
	aiSettingSection2Placeholder: `We sound professional but friendly, sharing our expertise in a way that's easy to connect with`,
	aiSettingSection3: 'Glimpse of your preferred writing style',
	aiSettingSection3Description: `Provide one or two examples of your writing style or a passage from one of your favorite piece of writing, Which our AI will adapts as its own.`,
	aiSettingSection3Placeholder: `Too much sanity may be madness, and maddest of all is to see life as it is and not as it should be`,
	aiSettingsModelSettings: 'AI Model Settings',
	aiSettingModelSection: 'Choose your AI model',
	aiSettingModelSectionDescription: 'Select the AI generation model that best fits your preferences.',
	aiSettingGPT4Tooltip: 'More optimized',
	aiSettingGPT3Tooltip: 'Faster',
	edit: 'edit',
	save: 'Save',
	skip: 'Skip',
	changeAISettings: 'Change AI settings',
	PleaseClickToEditTheSettings: 'Please click to edit the settings',
	billingDetailsAndInvoices: 'Billing details & Invoices',
	overview: 'Overview',
	currentPlan: 'Current plan',
	nextBillingOn: 'Next billing on',
	nextBillingAmount: 'Next billing amount',
	numberOfProjects: 'Number of projects',
	reachesSubscriptionPage: 'Reaches subscription page',
	billingPageUpgradeButton: 'Billing page upgrade button',
	upgradeYourPlan: 'Upgrade your Plan',
	billingInfoAndPayment: 'Billing Information & Payment',
	manageAllYourBilling: 'Manage all your billing information and payment methods here',
	manageBillingDetails: 'Manage billing details',
	invoicesHistory: 'Invoices history',
	invoiceID: 'Invoice ID',
	date: 'Date',
	total: 'Total',
	status: 'Status',
	invoiceReceipt: 'Invoice/Receipt',
	download: 'Download',
	noInfoAvailableYet: 'No information available yet',
	hideBranding: 'Hide branding',
	hideBrandingDescription: 'Hides the Notice branding on your project.',
	handleTitleTagTitle: 'Handle <title /> tag',
	titleTagDescription: 'When enabled, Notice will handle the <title /> tag of your project.',
	projectLogo: 'Project logo',
	projectLogoDescription: 'Your project logo can be displayed in different places of your project.',
	faviconDescription: 'Use your logo as a favicon.',
	faviconWarning: (
		<span>
			You need to upload a <b>Project logo</b> above to enable this feature.
		</span>
	),
	uploadImage: 'Upload image',
	configureLogoRedirect: 'Configure the address to which the logo redirects',
	navigationType: 'Navigation type',
	navigationTypeDescription: `Query param will use the 'page=' value in the URL to handle navigation. Slash will use the classic '/' subfolder.`,
	stopUserTracking: 'Stop user tracking',
	stopUserTrackingDescription: 'Notice will not collect data to provide you with statistics.',
	stopUserTrackingWarning: <span>The statistics dashboard will be disabled.</span>,
	headerSpace: 'Header space',
	projectTitle: 'Project title',
	homeButton: 'Home button',
	topSpace: 'Top space',
	contactForm: 'Contact form',
	emailToReceiveMessages: 'Email to receive messages',
	themeSwitch: 'Theme switch',
	languageSelector: 'Language selector',
	breadcrumbNavigation: 'Breadcrumb navigation',
	timeToRead: 'Time to read',
	shareToFacebook: 'Share to Facebook',
	shareToTwitter: 'Share to Twitter',
	shareToLinkedIn: 'Share to LinkedIn',
	leftSpace: 'Left space',
	navigationMenu: 'Navigation menu',
	rightSpace: 'Right space',
	anchorMenu: 'Anchor menu',
	bottomSpace: 'Bottom space',
	bottomNavigation: 'Bottom navigation',
	readMoreArticles: 'Read more articles',
	setProjectTitle: 'Set project title',
	setProjectTitleDescription: 'Will show the project title on the top space for every page.',
	navMenuDesc: 'Navigation menu on the left that gives easy access to your project.',
	searchDescription: 'Allow user to search inside you project. you will also have',
	analyticsSupport: 'analytics support',
	searchDescription2: 'from notice for your project search.',
	themeSwitchDescription: 'You can allow users to change the theme of your project. you can setup your theme',
	hereInsideColors: 'here inside colors.',
	languageSwitchDescription:
		'You can allow users to change the language of your project. You can configure your translations',
	here: 'here',
	allowNavDescription: 'Allow users to navigate between pages using the navigation menu.',
	displayHomeButtonDescription: 'Display a home button for users to navigate to homepage.',
	timeToReadDescription: 'Display the estimated time to read a page.',
	facebookShareDescription: 'Allow users to share your articles on Facebook.',
	twitterShareDescription: 'Allow users to share your articles on Twitter.',
	linkedinShareDescription: 'Allow users to share your articles on LinkedIn.',
	nextPrevDescription: 'Add buttons to navigate to next and previous pages on the bottom of the page.',
	anchorRightMenuDescription:
		'Add a menu on the right that allows users to navigate inside subtitles of the current page.',
	allowRecommendedArticlesDescription: 'Allow users to read more articles related to the current one.',
	pageTitle: 'Page title',
	colors: 'Colors',
	lightBgColor: 'Light Background Color',
	lightFontColor: 'Light Font Color',
	lightHighlightColor: 'Light Highlight Color',
	darkBgColor: 'Dark Background Color',
	darkFontColor: 'Dark Font Color',
	darkHighlightColor: 'Dark Highlight Color',
	fonts: 'Fonts',
	fontFamily: 'Font family',
	fontSize: 'Font size',
	spacing: 'Spacing',
	blockPadding: 'Block Padding',
	maxWidth: 'Max Width',
	maxWidthDescription: 'set max-width for main column',
	icons: 'Icons',
	iconStroke: 'Icon Stroke Width',
	headings: 'Headings',
	h1Weight: 'H1 Weight',
	h1Size: 'H1 Size',
	h2Size: 'H2 Size',
	h2Weight: 'H2 Weight',
	h3Size: 'H3 Size',
	h3Weight: 'H3 Weight',
	headingsPadding: 'Headings Padding',
	titleFontSize: 'Title font size',
	fontFamilyDescription: `To explore fonts, go to to <a href="https://fonts.google.com/" target="_blank">Google Fonts.</a>`,
	text: 'Text',
	textLineHeight: 'Text Line Height',
	textLetterSpacing: 'Text Letter Spacing',
	codeHtmlDesc: 'The code written will be inserted in to the ',
	// Explain that it's the <head /> tag of the page and you can add analytics
	codeHtmlDesc2: ` of your notice project. You can add analytics, meta tags, or any other script.`,
	CSSDesc: 'Write some CSS code to change the way your project looks',
	JavascriptDesc: 'Write some Javascript code to change the way your project behaves',
	insightsDesc: 'Drive content strategy and improve customer support with data on user behavior.',
	publishing: 'Publishing',
	publish: 'Publish',
	visitPage: 'Visit page',
	newProject: 'New project',
	createNewProject: 'Create new project',
	newPage: 'New page',
	addNewPage: 'Add a new page inside the current project',
	workspaceSettings: 'Workspace Settings',
	accountSettings: 'Account Settings',
	supportAndCommunity: 'Support & Community',
	signOut: 'Sign Out',
	whatIsNew: "What's new",
	inviteCollaborators: 'Invite collaborators',
	inviteCollaboratorsDescription:
		'Many hands make light work. Invite your colleagues to collaborate together on your projects.',
	emailAddress: 'Email address',
	admin: 'Administrator',
	editor: 'Editor',
	viewer: 'Viewer',
	owner: 'Owner',
	close: 'Close',
	invite: 'Invite',
	translationDescription: 'Translate your content in more than 100 languages.',
	selectBlock: 'You can select a block by clicking the',
	selectProjectLanguage: 'Select this project default language',
	validate: 'Validate',
	selectLanguageHint: 'Hint: this is the language of your current project.',
	configureTranslation: 'Configure translation',
	translationStatus: 'Translation status',
	selected: 'Selected',
	translated: 'Translated',
	notTranslated: 'Not translated',
	translationOutOfDate: 'Translation out of date',
	translateBlock: 'Translate block',
	markAsIncomplete: 'Mark as incomplete',
	markAsComplete: 'Mark as complete',
	markAsCompleteAndGoToNext: 'Mark as complete and go to next',
	anotherNoticeTabIsOpened: 'Another Notice tab is opened',
	pleaseReloadToAvoidMismatch: 'Please reload this window before using to avoid data mismatch.',
	reload: 'Reload',
	oopsNoResultsWereFound: 'Oops! No results found yet.',
	tryAgainNoResults: 'Try again with another period.',
	configureYourTranslation: 'Configure your translation',
	allowUsersToChangeLang: 'Allow users to change the language of your project.',
	addsALangQueryLike: 'Adds a lang query like',
	toYourProjectUrl: 'to your project url.',
	addLanguageQueryToUrl: 'Add language query param to url',
	chooseADefaultLanguage: 'Choose a default language',
	availableLanguages: 'Available Languages',
	ifYouWantMoreLanguages: 'If you want more languages',
	contactUs: 'Contact us',
	letUsKnow: 'let us know.',
	languageSelectorWarning: 'The language selector can also be managed in your top space layout by',
	clickingHere: 'clicking here',
	addNew: 'Add New',
	translateTo: 'Translate to',
	translateThisPage: 'Translate this page',
	stepByStepGuide: 'Step-by-step guide',
	manyHandsMakeLightWork: 'Many hands make light work',
	createAndCustomizeContent: 'Create and customize content',
	clickOnPublish: 'Click on publish',
	deployItAnywhere: 'Deploy it anywhere by going to the Integrations tab',
	inviteColleaguesToCollaborate: 'Invite colleagues to work together on your projects.',
	inviteYourTeam: 'Invite your team',
	makeTheMostOfNotice: 'Make the most of Notice',
	getInTouchWithUs: 'Get in touch with us',
	getInTouchDescription: 'Need any help or have feature requests? Send us a message or join our community on Slack.',
	accountSettingsDescription: 'Manage your profile, preferences, and login settings',
	dashboardLanguage: 'Dashboard language',
	updateEmail: 'Update email',
	featureComingSoon: 'Feature coming soon...',
	signOnWithGoogle: 'Set up a single sign-on with Google and login with one click',
	yourGoogleAccountHasBeenUnlinked: 'Your Google account has been successfully unlinked from your account.',
	unlinkAccount: 'Unlink account',
	linkAccount: 'Link account',
	singleSignOnGithub: 'Set up a single sign-on with Github and login with one click',
	githubAccountHasBeenUnlinked: 'Your Github account has been successfully unlinked from your account.',
	signOutDescription: 'You can safely sign out from the current sessions and choose to sign in back later',
	accountDeletion: 'Account deletion',
	accountDeletionDescription: 'By deleting your personnal account, you delete all associated data.',
	deleteAccount: 'Delete account',
	deleteMyAccountSubject: 'Delete my account',
	deleteMyAccountBody: 'Hi, I want to delete my account',
	settings: 'Settings',
	account: 'Account',
	myWorkspaces: 'My workspaces',
	workspace: 'Workspace',
	collaborators: 'Collaborators',
	plans: 'Plans',
	profilePicture: 'Profile picture',
	profilePictureDescription: 'Use a squared image with a minimum of 64 pixels',
	fullName: 'Full name',
	myWorkspacesDescription: `Global vision on all the workspaces you joined`,
	workspaces: 'Workspaces',
	created: 'Created',
	manageWorkspaceProfile: 'Manage workspace profile',
	workspaceProfile: 'Workspace profile',
	workspaceLogo: 'Workspace logo',
	displayName: 'Display name',
	workspaceDeletion: 'Workspace deletion',
	workspaceDeletionDescription: 'By deleting your workspace, you delete all associated data.',
	deleteWorkspace: 'Delete workspace',
	storage: 'Storage',
	storageDescription: `(images, videos, files, ...)`,
	deleteWorkspaceDescription: 'Are you sure you want to delete this workspace?',
	deleteWorkspaceWarning: 'This action cannot be undone.',
	cancel: 'Cancel',
	confirm: 'Confirm',
	visits: 'Visits',
	statistics: 'Statistics',
	visitsByTimeSpan: 'Visits by time span',
	location: 'Location',
	locationDescription: 'The location of your visitors',
	device: 'Device',
	deviceDescription: 'The device used by your visitors',
	browser: 'Browser',
	browserDescription: 'The browser used by your visitors',
	OSdescription: 'The operating system used by your visitors',
	integration: 'Integration',
	hosting: 'Hosting',
	noticeDomain: 'Notice Domain',
	noticeDomainDescription: 'Change the name of the notice hosted domain.',
	allowedCharacters: 'Allowed characters',
	letters: 'letters',
	numbers: 'numbers',
	and: 'and',
	domainName: 'Domain name',
	customDomainDescription: 'Add your own custom domain and link it to your project.',
	customDomain: 'Custom domain',
	customDomainMissing: `You currently don't have a custom domain link to this project`,
	customDomainPresent: `You currently have a custom domain link to this project`,
	configure: 'Configure',
	whatDomainWouldYouLikeToLink: 'What domain would you like to link?',
	hostnameIsInvalid: 'Hostname is invalid. Only subdomains are allowed.',
	mustOwnSubdomainAndAbilityToEditDNS: 'You must own the subdomain and have the ability to edit its DNS records.',
	configureDNS: 'Configure DNS',
	others: 'Others',
	webflowIntegration: 'Add Notice blocks to your Webflow website in a single click.',
	wordpressIntegration: 'Add Notice Plugin to empower your experience on Wordpress.',
	shopifyIntegration: 'Deliver great customer experience by using Notice Plugin in your store.',
	umsoIntegration: 'Add Notice blocks to Umso website and get insights from your audience.',
	wixIntegration:
		"Intégrer Notice dans Wix est facile. Il suffit d'ajouter un bloc d'intégration et le tour est joué !",
	squarespaceIntegration:
		"C'est rapide, comme d'habitude. Ajoutez un bloc de code et collez votre ID Notice pour afficher votre contenu.",
	unicornIntegration: 'Quick win to improve and personalize your website with smart blocks.',
	reactIntegration: 'Notice blocks easily integrated into React in just one step.',
	nextIntegration: 'For the lovers of the Next.js SSR frontend framework, smooth integration.',
	vueIntegration: 'Integrate Notice inside your Vue.js project in less than one minute.',
	nuxtIntegration: 'For the lovers of the Nuxt SSR frontend framework, smooth integration.',
	linkIntegration: `The easiest solution, just share the link! You don't even need a website.`,
	htmlIntegration: `The go-to solution for websites if you don't find your specific framework.`,
	iframeIntegration: 'Easy to use, iframes fit everywhere, even in mobile application.',
	rawJSONIntegration: 'For advanced users that want total control over their projects.',
	qrcodeIntegration: `Your content at users fingertips! Share your own QR code :)`,
	integrationsDescription: 'Empower your visibility by sharing and integrating your Notice everywhere.',
	categories: 'Categories',
	all: 'All',
	needADifferentIntegrationAndCannotFindItHere: 'Need a different integration and cannot find it here?',
	shareables: 'Shareables',
	useTemplates: 'Use Templates',
	useAIGeneration: 'Use AI Generation',
	selectProjectTip: 'You can toggle between AI generation and templates',
	preFilledTemplate: 'Pre-filled template',
	helpCenter: 'Help Center',
	termsOfuse: 'Terms of use',
	privacyPolicy: 'Privacy policy',
	jobBoard: 'Job board',
	getStarted: 'Tutorial',
	changelog: 'Changelog',
	missionAndValues: 'Mission & Values',
	investorsReport: 'Investors report',
	startFromScratch: 'Start from scratch',
	helpOurAIGenerateYour: 'Help our AI generate your',
	provideYourWebsiteURL: `Provide your existing website URL`,
	weFoundAWebsite: `We found a website linked to your email address`,
	makeSureProvidedWebsiteAlreadyExists: `Make sure the provided website already exists`,
	AIExplanation: `Our AI goes through the provided website and generates a custom`,
	basedOnTheWebsiteInformation: `based on the website information.`,
	youCanUseAnyExistingURL: `You can use any existing URL.`,
	enhanceYourGeneration: `You can enhance your generation by adding more instructions`,
	giveInstructions: `Give instructions to generate your`,
	makeSureThisPromptIsMatching: `Please make sure this prompt is matching with the selected project type`,
	writeItInFrenchOnlyUsePastTense: `Example: Write it in French, only use past tense`,
	backToList: `Back to list`,
	pricingDescription: 'Our pricing is straightforward and aligned with your business goals.',
	monthlyTokenAmount: 'Monthly token amount',
	billingPeriod: 'Billing period',
	monthly: 'Monthly',
	yearly: 'Yearly',
	oneMonthFree: '1 month free',
	customizeYourNewContentsHome: 'Start personal projects',
	manageSmartContentForYourCompany: 'Manage smart content for your company',
	activateContentSynergiesForYourTeam: 'Activate content synergies for your team',
	forThoseNeedingAnEnterpriseGradeSolution: 'Tailored for corporate demands',
	letsTalk: 'Let’s talk',
	numberOfCollaborators: 'Number of collaborators',
	numberOfWorkspaces: 'Number of workspaces',
	integrateAnywhere: 'Integrate anywhere',
	removeNoticeBranding: 'Remove Notice branding',
	aiAssistant: 'AI assistant',
	customSupportAndHelp: 'Custom support and help',
	premiumCdn: 'Premium CDN',
	ssoEnabled: 'SSO enabled',
	onPremiseData: 'On-premise data',
	contentAndSeoAudit: 'Content & SEO audit',
	downgrade: 'Downgrade',
	newWorkspace: 'New workspace',
	createANewWorkspace: 'Create a new workspace',
	enterNameOfNewWorkspace: 'Enter the name of your new workspace',
	create: 'Create',
	signIn: 'Sign In',
	signInDescription: 'Sign in quickly using one of your social accounts, or use your work email.',
	signUp: 'Sign Up',
	continueWithGoogle: 'Continue with Google',
	continueWithGithub: 'Continue with Github',
	orSignInUsingWorkEmail: 'Or sign in using your work email',
	enterWorkEmail: 'Enter your work email',
	enterTemporaryCode: 'Enter temporary code',
	weJustSentYouATemporaryLoginCode: 'We just sent you a temporary login code.',
	pleaseCheckYourInbox: 'Please check your inbox.',
	alreadyHaveAnAccountSignIn: 'Already have an account? Sign in',
	continueWithLoginCode: 'Continue with Login code',
	continueWithEmail: 'Continue with email',
	selectYourProject: 'Select your project',
	chooseYourIntegration: 'Choose your integration',
	publishingYourProject: 'Publishing your project',
	projectCreated:
		'Your Notice project has been created! Add this new project to your website using one of our integrations or directly via the pre-generated link for you.',
	signInMethods: 'Sign in methods',
	signInMethodsDescription: 'Update the email used to log into your account',
	joinOurSlackCommunityForUpdatesAndFeedback:
		'Join our Slack community for updates and feedback, and connect with us on socials.',
	joinSlack: 'Join Slack',
	joinTheAcademy: 'Join the Academy',
	readOurDoc: 'Read our doc',
	checkOurTutorials: 'Check our tutorials',
	sendUsAnEmail: 'Send us an email',
	pleaseEnterYourFirstName: 'Please enter your first name.',
	pleaseEnterYourLastName: 'Please enter your last name.',
	firstname: 'First name',
	lastname: 'Last name',
	pleasEnterAValidPhoneNumber: 'Please enter a valid phone number.',
	phoneNumber: 'Phone number',
	pleaseEnterYourCompanyName: 'Please enter your company name.',
	companyName: 'Company name',
	pleaseChooseYourCompanySize: 'Please choose your company size.',
	companySize: 'Company size',
	pleaseChooseYourRoleInTheCompany: 'Please choose your role in the company.',
	companyRole: 'Company role',
	startCreating: 'Start creating !',
	welcomeToNotice: 'Welcome to Notice !',
	pleaseHelpUsWithForm: 'Please help us with the process of providing you the complete Notice experience.',
	preview: 'Preview',
	rename: 'Rename',
	duplicate: 'Duplicate',
	exportMarkdown: 'Export Markdown',
	delete: 'Delete',
	exportJSON: 'Export JSON',
	type: 'Type',
	forCommands: 'to add blocks and for commands',
	paragraph: 'Paragraph',
	justWriteDownSomeText: 'Just write down some text',
	basicBlocks: 'Basic blocks',
	heading: 'Heading',
	bigSectionHeading: 'Big section heading',
	mediumSectionHeading: 'Medium section heading',
	smallSectionHeading: 'Small section heading',
	bulletedList: 'Bulleted list',
	organizeContentWithBullets: 'Organize content with bullets',
	numberedList: 'Numbered list',
	createANumberedList: 'Create a numbered list',
	captureACodeSnippet: 'Capture a code snippet',
	hint: 'Hint',
	provideHelpfulInformation: 'Provide helpful information',
	quote: 'Quote',
	highlightASpecificPassageOfText: 'Highlight a specific passage of text',
	divider: 'Divider',
	separateDifferentBlocks: 'Separate different blocks',
	toDo: 'To-do',
	keepTrackOfTasksOrItems: 'Keep track of tasks or items',
	media: 'Media',
	image: 'Image',
	uploadAnImageFile: 'Upload an image file',
	document: 'Document',
	uploadADocument: 'Upload a document',
	video: 'Video',
	addAVideo: 'Add a video',
	advancedBlocks: 'Advanced blocks',
	table: 'Table',
	organizeWithRowsAndColumns: 'Organize with rows and columns',
	expandable: 'Expandable',
	addACollapsableBlock: 'Add a collapsable block',
	textAIGeneration: 'Text AI generation',
	letOurRobotCreateYourContent: 'Let our robot create your content',
	imageAIGeneration: 'Image AI generation',
	letOurRobotCreateYourImages: 'Let our robot create your images',
	javascript: 'Javascript',
	embedJavascript: 'Embed Javascript',
	youtube: 'Youtube',
	embedYoutubeVideos: 'Embed Youtube videos',
	justCopyPasteTheLinkOfYourVideo:
		'Just copy paste the link of your video in an empty paragraph to automatically embed a Youtube video. Example link: https://www.youtube.com/watch?v=m4fDm4rdUdk',
	embedLoomVideos: 'Embed Loom videos',
	justCopyPasteLoomVideo:
		'Just copy paste the link of your video in an empty paragraph to automatically embed a Loom video. Example link: https://www.loom.com/share/36656bc4afb84de2bb829183f46a1b40',
	embedVimeos: 'Embed Vimeos',
	embedVimeosInstructions:
		'Just copy paste the link of your video in an empty paragraph to automatically embed a Vimeo video. Example link: https://vimeo.com/251147627',
	embedAirtableInstructions:
		'Paste the link of your table view in an empty paragraph to automatically embed an AirTable. Example link: https://airtable.com/appeh8s8bwMI7JjlW/shro43JbOcXFQH0tQ/tblnrBMRpvfrcqkko',
	AIIsWriting: 'AI is writing...',
	Keep: 'Keep',
	Retry: 'Retry',
	DescribeWhatYouWantAI: 'Describe what you want to create to our AI',
	LetOurAICreate: 'Let our AI create your page',
	LetOurAICreateImage: 'Create an image inspired by this page',
	freeTrialEndsIn: 'Your free trial will end in X days.',
	AIIsGeneratingAnImageIdea: 'AI is generating an image idea...',
	AIIsGeneratingImage: 'AI is generating an image...',
	GenImagePlaceholder: 'A field of sunflowers at the end of the day. In the style of Van Ghogh paintings.',
	metadata: 'Metadata',
	pageMetadata: 'Page Metadata',
	giveInformationForSEO: 'Enrich this page with information for improved SEO and previews',
	author: 'Author',
	editMyName: 'Edit my profile',
	tags: 'Tags',
	datePublished: 'Publication date',
	addATag: 'Add a tag',
	advancedOptions: 'Advanced Options',
	tellGoogleExists: 'Tell Google your project exists',
	tellGoogleExistsDescription: `To properly index your project, you need to verify your website on `,
	clickHereToFollowOurGuide: 'Click here to follow our guide',
	explanationDateOfPublication: 'By setting a date in the future it will hide the page until the chosen date.',
	articleHiddenDateFuture: 'This article is hidden because the date is in the future',
	blockMenuChangeImageCover: 'Change Image Cover',
	blockMenuAddImageCover: 'Add Image Cover',
	blockMenuDuplicate: 'Duplicate',
	blockMenuDelete: 'Delete',
	blockMenuOnlyText: 'Only Text',
	blockMenuWithImage: 'With Image',
	blockMenuPageSummary: 'Page Summary',
	blockMenuBorder: 'Border',
	blockMenuLayout: 'Layout',
	blockMenuDisplay: 'Display',
	blockMenuStyle: 'Style',
	subPageUpgradeSucessTitle: 'Upgrade Successful',
	subPageUpgradeSuccessMsg:
		'Congratulations! 🎉 Your account has been successfully upgraded. Thank you for choosing Notice to enhance yourexperience!',
	subPageGoBack: 'Go back editing',
	deleteProjectDeleteProject: 'Delete Project',
	deleteProjectAreYouSure: 'Are you sure you want to delete this project?',
	deleteWarning: 'This action cannot be undone.',
	cancelButton: 'Cancel',
	confirmButton: 'Confirm',
	deletePageDeletePage: 'Delete Page',
	deletePageAreYouSure:
		'This action will permanently delete this page and all its related content, are you sure you want to continue?',
	writeYourImageDesc: 'Write your image description here (Max. 125 characters).',
	imageDescription: 'Image description',
	pasteLinkHere: 'Paste link here',
	addLink: 'Add link',
	removeLink: 'Remove link',
	selectAnImage: 'Select an Image',
	selectADocument: 'Select A Document',
	selectAVideo: 'Select a Video',
	selectAnAudio: 'Select an Audio',
	dropYourFileHere: 'Drop your file here to start uploading or',
	anyDocTypeAccepted: 'Any type of document is accepted',
	acceptedTypes: 'Accepted types',
	browseFiles: 'Browse Files',
	filterFiles: 'Filter files',
	files: 'Files',
	enterAnURL: 'Enter an URL',
}
