export const es = {
	customization: 'Personalización',
	translation: 'Traducción',
	integrations: 'Integraciones',
	insights: 'Perspectivas',
	FreePlan: 'Plan gratuito',
	upgrade: 'Mejorar',
	yourProfile: 'Tu perfil',
	general: 'General',
	layout: 'Diseño',
	theme: 'Tema',
	advanced: 'Avanzado',
	styling: 'Estilización',
	code: 'Código',
	billing: 'Facturación',
	aiSettings: 'Configuraciones de IA',
	aiSettingsDescription:
		'Bienvenido a la configuración de IA, donde controlas cómo nuestra IA genera contenido para este espacio de trabajo',
	aiSettingSection1: '¿Qué haces?',
	aiSettingSection1Description:
		'Ayúdenos a entender su línea de trabajo o el enfoque de su empresa. Proporcione una breve descripción de su negocio o profesión.',
	aiSettingSection1Placeholder:
		'Dirijo una agencia creativa que se especializa en estrategias de marketing digital y creación de contenido',
	aiSettingSection2: '¿Cuál es tu tono?',
	aiSettingSection2Description:
		'Define el tono que deseas para el texto en tu espacio de trabajo. Comparte con nosotros el tipo de tono que se alinea con tu estilo de comunicación.',
	aiSettingSection2Placeholder:
		'Sonamos profesionales pero amigables, compartiendo nuestra experiencia de una manera que es fácil de conectar',
	aiSettingSection3: 'Vistazo a tu estilo de escritura preferido',
	aiSettingSection3Description:
		'Proporcione uno o dos ejemplos de su estilo de escritura o un pasaje de una de sus piezas favoritas de escritura. Nuestra IA se adaptará y proporcionará el texto en el mismo estilo.',
	aiSettingSection3Placeholder: `Amor y deseo son dos cosas diferentes; que no todo lo que se ama se desea, ni todo lo que se desea se ama.`,
	aiSettingsModelSettings: 'Configuración del Modelo de IA',
	aiSettingModelSection: 'Elige tu modelo de IA',
	aiSettingModelSectionDescription: 'Selecciona el modelo de generación de IA que mejor se adapte a tus preferencias.',
	aiSettingGPT4Tooltip: 'Más optimizado',
	aiSettingGPT3Tooltip: 'Más rápido',
	edit: 'editar',
	save: 'guardar',
	skip: 'saltar',
	changeAISettings: 'Cambiar configuraciones de IA',
	PleaseClickToEditTheSettings: 'Por favor, haga clic para editar la configuración',
	billingDetailsAndInvoices: 'Detalles de facturación y facturas',
	overview: 'Resumen',
	currentPlan: 'Plan actual',
	nextBillingOn: 'Próxima facturación en',
	nextBillingAmount: 'Monto de la próxima facturación',
	numberOfProjects: 'Número de proyectos',
	reachesSubscriptionPage: 'Llega a la página de suscripción',
	billingPageUpgradeButton: 'Botón de mejora de la página de facturación',
	upgradeYourPlan: 'Mejora tu plan',
	billingInfoAndPayment: 'Información de facturación y pago',
	manageAllYourBilling: 'Administra toda tu información de facturación y métodos de pago aquí',
	manageBillingDetails: 'Administrar detalles de facturación',
	invoicesHistory: 'Historial de facturas',
	invoiceID: 'ID de factura',
	date: 'Fecha',
	total: 'Total',
	status: 'Estado',
	invoiceReceipt: 'Factura/Recibo',
	download: 'Descargar',
	noInfoAvailableYet: 'Aún no hay información disponible',
	hideBranding: 'Ocultar marca',
	hideBrandingDescription: 'Oculta la marca de Notice en tu proyecto.',
	handleTitleTagTitle: 'Manejar etiqueta <title />',
	titleTagDescription: 'Cuando está activado, Notice manejará la etiqueta <title /> de tu proyecto.',
	projectLogo: 'Logo del proyecto',
	projectLogoDescription: 'Tu logo de proyecto se puede mostrar en diferentes lugares de tu proyecto.',
	faviconDescription: 'Usa tu logo como un favicon.',
	faviconWarning: (
		<span>
			Necesitas subir un <b>Logo del proyecto</b> arriba para habilitar esta función.
		</span>
	),
	uploadImage: 'Subir imagen',
	configureLogoRedirect: 'Configura la dirección a la que redirige el logo',
	navigationType: 'Tipo de navegación',
	navigationTypeDescription: `El tipo de navegación por parámetro de consulta usará el valor 'page=' en la URL para manejar la navegación. La barra usará la clásica subcarpeta '/'.`,
	stopUserTracking: 'Detener seguimiento de usuario',
	stopUserTrackingDescription: 'Notice no recopilará datos para proporcionarte estadísticas.',
	stopUserTrackingWarning: <span>El panel de estadísticas será deshabilitado.</span>,
	headerSpace: 'Espacio de cabecera',
	projectTitle: 'Título del proyecto',
	homeButton: 'Botón de inicio',
	topSpace: 'Espacio superior',
	contactForm: 'Formulario de contacto',
	emailToReceiveMessages: 'Correo electrónico para recibir mensajes',
	themeSwitch: 'Interruptor de tema',
	languageSelector: 'Selector de idioma',
	breadcrumbNavigation: 'Navegación de migas de pan',
	timeToRead: 'Tiempo de lectura',
	shareToFacebook: 'Compartir en Facebook',
	shareToTwitter: 'Compartir en Twitter',
	shareToLinkedIn: 'Compartir en LinkedIn',
	leftSpace: 'Espacio izquierdo',
	navigationMenu: 'Menú de navegación',
	rightSpace: 'Espacio derecho',
	anchorMenu: 'Menú de anclas',
	bottomSpace: 'Espacio inferior',
	bottomNavigation: 'Navegación inferior',
	readMoreArticles: 'Leer más artículos',
	setProjectTitle: 'Establecer título del proyecto',
	setProjectTitleDescription: 'Mostrará el título del proyecto en el espacio superior de cada página.',
	navMenuDesc: 'Menú de navegación a la izquierda que facilita el acceso a tu proyecto.',
	searchDescription: 'Permite al usuario buscar dentro de tu proyecto. También tendrás',
	analyticsSupport: 'soporte de análisis',
	searchDescription2: 'de Notice para la búsqueda en tu proyecto.',
	themeSwitchDescription: 'Puedes permitir a los usuarios cambiar el tema de tu proyecto. Puedes configurar tu tema',
	hereInsideColors: 'aquí dentro de colores.',
	languageSwitchDescription:
		'Puedes permitir a los usuarios cambiar el idioma de tu proyecto. Puedes configurar tus traducciones',
	here: 'aquí',
	allowNavDescription: 'Permitir a los usuarios navegar entre páginas usando el menú de navegación.',
	displayHomeButtonDescription: 'Mostrar un botón de inicio para que los usuarios naveguen a la página principal.',
	timeToReadDescription: 'Mostrar el tiempo estimado de lectura de una página.',
	facebookShareDescription: 'Permitir a los usuarios compartir tus artículos en Facebook.',
	twitterShareDescription: 'Permitir a los usuarios compartir tus artículos en Twitter.',
	linkedinShareDescription: 'Permitir a los usuarios compartir tus artículos en LinkedIn.',
	nextPrevDescription:
		'Añadir botones para navegar a las páginas siguiente y anterior en la parte inferior de la página.',
	anchorRightMenuDescription:
		'Añadir un menú a la derecha que permite a los usuarios navegar dentro de los subtítulos de la página actual.',
	allowRecommendedArticlesDescription: 'Permitir a los usuarios leer más artículos relacionados con el actual.',
	pageTitle: 'Título de la página',
	colors: 'Colores',
	lightBgColor: 'Color de fondo claro',
	lightFontColor: 'Color de fuente claro',
	lightHighlightColor: 'Color de resaltado claro',
	darkBgColor: 'Color de fondo oscuro',
	darkFontColor: 'Color de fuente oscuro',
	darkHighlightColor: 'Color de resaltado oscuro',
	fonts: 'Fuentes',
	fontFamily: 'Familia de fuentes',
	fontSize: 'Tamaño de fuente',
	spacing: 'Espaciado',
	blockPadding: 'Relleno de bloque',
	maxWidth: 'Anchura máxima',
	maxWidthDescription: 'Establecer anchura máxima para la columna principal',
	icons: 'Iconos',
	iconStroke: 'Ancho de trazo del icono',
	headings: 'Encabezados',
	h1Weight: 'Peso de H1',
	h1Size: 'Tamaño de H1',
	h2Size: 'Tamaño de H2',
	h2Weight: 'Peso de H2',
	h3Size: 'Tamaño de H3',
	h3Weight: 'Peso de H3',
	headingsPadding: 'Relleno de los encabezados',
	titleFontSize: 'Tamaño de fuente del título',
	fontFamilyDescription: `Para explorar fuentes, visita <a href="https://fonts.google.com/" target="_blank">Google Fonts.</a>`,
	text: 'Texto',
	textLineHeight: 'Altura de línea del texto',
	textLetterSpacing: 'Espaciado entre letras del texto',
	codeHtmlDesc: 'El código escrito será insertado en el ',
	codeHtmlDesc2: ' de tu proyecto Notice.',
	CSSDesc: 'Escribe código CSS para cambiar la apariencia de tu proyecto',
	JavascriptDesc: 'Escribe código Javascript para cambiar el comportamiento de tu proyecto',
	insightsDesc:
		'Guía la estrategia de contenido y mejora el soporte al cliente con datos sobre el comportamiento del usuario.',
	publishing: 'Publicación',
	publish: 'Publicar',
	visitPage: 'Visitar página',
	newProject: 'Nuevo proyecto',
	createNewProject: 'Crear nuevo proyecto',
	newPage: 'Nueva página',
	addNewPage: 'Añadir una nueva página dentro del proyecto actual',
	workspaceSettings: 'Configuración del espacio de trabajo',
	accountSettings: 'Configuración de la cuenta',
	supportAndCommunity: 'Soporte y comunidad',
	signOut: 'Cerrar sesión',
	whatIsNew: 'Novedades',
	inviteCollaborators: 'Invitar colaboradores',
	inviteCollaboratorsDescription:
		'Muchos ayudantes facilitan el trabajo. Invita a tus colegas a colaborar juntos en tus proyectos.',
	emailAddress: 'Dirección de correo electrónico',
	admin: 'Administrador',
	editor: 'Editor',
	viewer: 'Espectador',
	owner: 'Propietario',
	close: 'Cerrar',
	invite: 'Invitar',
	translationDescription: 'Traduce tu contenido en más de 100 idiomas.',
	selectBlock: 'Puedes seleccionar un bloque haciendo clic en el',
	selectProjectLanguage: 'Selecciona el idioma predeterminado de este proyecto',
	validate: 'Validar',
	selectLanguageHint: 'Consejo: este es el idioma de tu proyecto actual.',
	configureTranslation: 'Configurar traducción',
	translationStatus: 'Estado de la traducción',
	selected: 'Seleccionado',
	translated: 'Traducido',
	notTranslated: 'No traducido',
	translationOutOfDate: 'Traducción desactualizada',
	translateBlock: 'Traducir bloque',
	markAsIncomplete: 'Marcar como incompleto',
	markAsComplete: 'Marcar como completo',
	markAsCompleteAndGoToNext: 'Marcar como completo e ir al siguiente',
	anotherNoticeTabIsOpened: 'Otra pestaña de Notice está abierta',
	pleaseReloadToAvoidMismatch: 'Por favor, recarga esta ventana antes de usar para evitar desajustes de datos.',
	reload: 'Recargar',
	oopsNoResultsWereFound: '¡Ups! Aún no se encontraron resultados.',
	tryAgainNoResults: 'Intenta de nuevo con otro período.',
	configureYourTranslation: 'Configura tu traducción',
	allowUsersToChangeLang: 'Permite a los usuarios cambiar el idioma de tu proyecto.',
	addsALangQueryLike: 'Agrega una consulta de idioma como',
	toYourProjectUrl: 'a la URL de tu proyecto.',
	addLanguageQueryToUrl: 'Agregar parámetro de idioma a la URL',
	chooseADefaultLanguage: 'Elige un idioma predeterminado',
	availableLanguages: 'Idiomas Disponibles',
	ifYouWantMoreLanguages: 'Si deseas más idiomas',
	contactUs: 'Contáctanos',
	letUsKnow: 'haznos saber.',
	languageSelectorWarning:
		'El selector de idioma también se puede gestionar en el diseño de tu espacio superior haciendo clic',
	clickingHere: 'aquí',
	addNew: 'Añadir nuevo',
	translateTo: 'Traducir a',
	translateThisPage: 'Traducir esta página',
	stepByStepGuide: 'Guía paso a paso',
	manyHandsMakeLightWork: 'Muchas manos hacen el trabajo más ligero',
	createAndCustomizeContent: 'Crear y personalizar contenido',
	clickOnPublish: 'Haz clic en publicar',
	deployItAnywhere: 'Despliégalo en cualquier lugar yendo a la pestaña de Integraciones',
	inviteColleaguesToCollaborate: 'Invita a los colegas a colaborar juntos en tus proyectos.',
	inviteYourTeam: 'Invita a tu equipo',
	makeTheMostOfNotice: 'Aprovecha al máximo Notice',
	getInTouchWithUs: 'Ponte en contacto con nosotros',
	getInTouchDescription:
		'¿Necesitas ayuda o tienes alguna solicitud de función? Envíanos un mensaje o únete a nuestra comunidad en Slack.',
	accountSettingsDescription: 'Gestiona tu perfil, preferencias y configuraciones de inicio de sesión',
	dashboardLanguage: 'Idioma del panel',
	updateEmail: 'Actualizar correo electrónico',
	featureComingSoon: 'Función próximamente...',
	signOnWithGoogle: 'Configura el inicio de sesión único con Google y entra con un clic',
	yourGoogleAccountHasBeenUnlinked: 'Tu cuenta de Google ha sido desvinculada con éxito de tu cuenta.',
	unlinkAccount: 'Desvincular cuenta',
	linkAccount: 'Vincular cuenta',
	singleSignOnGithub: 'Configura el inicio de sesión único con Github y entra con un clic',
	githubAccountHasBeenUnlinked: 'Tu cuenta de Github ha sido desvinculada con éxito de tu cuenta.',
	signOutDescription:
		'Puedes cerrar sesión de forma segura de las sesiones actuales y elegir volver a iniciar sesión más tarde',
	accountDeletion: 'Eliminación de cuenta',
	accountDeletionDescription: 'Al eliminar tu cuenta personal, borras todos los datos asociados.',
	deleteAccount: 'Eliminar cuenta',
	deleteMyAccountSubject: 'Eliminar mi cuenta',
	deleteMyAccountBody: 'Hola, quiero eliminar mi cuenta',
	settings: 'Configuraciones',
	account: 'Cuenta',
	myWorkspaces: 'Mis espacios de trabajo',
	workspace: 'Espacio de trabajo',
	collaborators: 'Colaboradores',
	plans: 'Planes',
	profilePicture: 'Foto de perfil',
	profilePictureDescription: 'Usa una imagen cuadrada con un mínimo de 64 píxeles',
	fullName: 'Nombre completo',
	myWorkspacesDescription: `Visión global de todos los espacios de trabajo a los que te has unido`,
	workspaces: 'Espacios de trabajo',
	created: 'Creado',
	manageWorkspaceProfile: 'Gestionar perfil del espacio de trabajo',
	workspaceProfile: 'Perfil del espacio de trabajo',
	workspaceLogo: 'Logo del espacio de trabajo',
	displayName: 'Nombre para mostrar',
	workspaceDeletion: 'Eliminación del espacio de trabajo',
	workspaceDeletionDescription: 'Al eliminar tu espacio de trabajo, borras todos los datos asociados.',
	deleteWorkspace: 'Eliminar espacio de trabajo',
	storage: 'Almacenamiento',
	storageDescription: `(imágenes, videos, archivos, ...)`,
	deleteWorkspaceDescription: '¿Estás seguro de que quieres eliminar este espacio de trabajo?',
	deleteWorkspaceWarning: 'Esta acción no se puede deshacer.',
	cancel: 'Cancelar',
	confirm: 'Confirmar',
	visits: 'Visitas',
	statistics: 'Estadísticas',
	visitsByTimeSpan: 'Visitas por intervalo de tiempo',
	location: 'Ubicación',
	locationDescription: 'La ubicación de tus visitantes',
	device: 'Dispositivo',
	deviceDescription: 'El dispositivo utilizado por tus visitantes',
	browser: 'Navegador',
	browserDescription: 'El navegador utilizado por tus visitantes',
	OSdescription: 'El sistema operativo utilizado por tus visitantes',
	integration: 'Integración',
	hosting: 'Alojamiento',
	noticeDomain: 'Dominio de Notice',
	noticeDomainDescription: 'Cambia el nombre del dominio hospedado por Notice.',
	allowedCharacters: 'Caracteres permitidos',
	letters: 'letras',
	numbers: 'números',
	and: 'y',
	domainName: 'Nombre de dominio',
	customDomainDescription: 'Agrega tu propio dominio personalizado y enlázalo a tu proyecto.',
	customDomain: 'Dominio personalizado',
	customDomainMissing: `Actualmente no tienes un dominio personalizado vinculado a este proyecto`,
	customDomainPresent: `Actualmente tienes un dominio personalizado vinculado a este proyecto`,
	configure: 'Configurar',
	whatDomainWouldYouLikeToLink: '¿Qué dominio te gustaría vincular?',
	hostnameIsInvalid: 'El nombre de host es inválido. Solo se permiten subdominios.',
	mustOwnSubdomainAndAbilityToEditDNS: 'Debes poseer el subdominio y tener la capacidad de editar sus registros DNS.',
	configureDNS: 'Configurar DNS',
	others: 'Otros',
	webflowIntegration: 'Añade bloques de Notice a tu sitio web de Webflow con un solo clic.',
	wordpressIntegration: 'Añade el Plugin de Notice para potenciar tu experiencia en Wordpress.',
	shopifyIntegration: 'Ofrece una gran experiencia al cliente utilizando el Plugin de Notice en tu tienda.',
	umsoIntegration: 'Añade bloques de Notice a tu sitio web de Umso y obtén información de tu audiencia.',
	wixIntegration: 'Integrar Notice en Wix es fácil. Solo agrega un bloque de integración y listo.',
	squarespaceIntegration:
		'Es rápido, como de costumbre. Agrega un bloque de código y pega tu ID de Notice para mostrar tu contenido.',
	unicornIntegration: 'Una solución rápida para mejorar y personalizar tu sitio web con bloques inteligentes.',
	reactIntegration: 'Bloques de Notice fácilmente integrados en React en solo un paso.',
	nextIntegration: 'Para los amantes del framework de frontend SSR de Next.js, integración sin problemas.',
	vueIntegration: 'Integra Notice dentro de tu proyecto de Vue.js en menos de un minuto.',
	nuxtIntegration: 'Para los amantes del framework de frontend SSR de Nuxt, integración sin problemas.',
	linkIntegration: `La solución más fácil, ¡solo comparte el enlace! Ni siquiera necesitas un sitio web.`,
	htmlIntegration: `La solución predeterminada para sitios web si no encuentras tu framework específico.`,
	iframeIntegration: 'Fácil de usar, los iframes encajan en todas partes, incluso en aplicaciones móviles.',
	rawJSONIntegration: 'Para usuarios avanzados que desean control total sobre sus proyectos.',
	qrcodeIntegration: `¡Tu contenido al alcance de los usuarios! Comparte tu propio código QR :)`,
	integrationsDescription: 'Potencia tu visibilidad compartiendo e integrando tu Notice en todas partes.',
	categories: 'Categorías',
	all: 'Todo',
	needADifferentIntegrationAndCannotFindItHere: '¿Necesitas una integración diferente y no la encuentras aquí?',
	shareables: 'Compartibles',
	useTemplates: 'Usar plantillas',
	useAIGeneration: 'Usar generación con IA',
	selectProjectTip: 'Puedes alternar entre la generación con IA y las plantillas',
	preFilledTemplate: 'Plantilla prellenada',
	helpCenter: 'Centro de ayuda',
	termsOfuse: 'Términos de uso',
	privacyPolicy: 'Política de privacidad',
	jobBoard: 'Tablón de empleo',
	getStarted: 'Tutorial',
	changelog: 'Registro de cambios',
	missionAndValues: 'Misión y valores',
	investorsReport: 'Informe para inversores',
	startFromScratch: 'Empezar desde cero',
	helpOurAIGenerateYour: 'Ayuda a nuestra IA a generar tu',
	provideYourWebsiteURL: `Proporciona la URL de tu sitio web existente`,
	weFoundAWebsite: `Encontramos un sitio web vinculado a tu dirección de correo electrónico`,
	makeSureProvidedWebsiteAlreadyExists: `Asegúrate de que el sitio web proporcionado ya exista`,
	AIExplanation: `Nuestra IA examina el sitio web proporcionado y genera un`,
	basedOnTheWebsiteInformation: `personalizado basado en la información del sitio web.`,
	youCanUseAnyExistingURL: `Puedes usar cualquier URL existente.`,
	enhanceYourGeneration: `Puedes mejorar tu generación agregando más instrucciones`,
	giveInstructions: `Da instrucciones para generar tu`,
	makeSureThisPromptIsMatching: `Asegúrate de que este mensaje coincida con el tipo de proyecto seleccionado`,
	writeItInFrenchOnlyUsePastTense: `Ejemplo: Escríbelo en francés, solo usa tiempo pasado`,
	backToList: `Volver a la lista`,
	pricingDescription: 'Nuestros precios son claros y están alineados con tus objetivos empresariales.',
	monthlyTokenAmount: 'Cantidad de tokens mensuales',
	billingPeriod: 'Período de facturación',
	monthly: 'Mensual',
	yearly: 'Anual',
	oneMonthFree: '1 mes gratis',
	customizeYourNewContentsHome: 'Personaliza el hogar de tu nuevo contenido',
	manageSmartContentForYourCompany: 'Gestiona contenido inteligente para tu empresa',
	activateContentSynergiesForYourTeam: 'Activa sinergias de contenido para tu equipo',
	forThoseNeedingAnEnterpriseGradeSolution: 'Para aquellos que necesitan una solución de grado empresarial',
	letsTalk: 'Hablemos',
	numberOfCollaborators: 'Número de colaboradores',
	numberOfWorkspaces: 'Número de espacios de trabajo',
	integrateAnywhere: 'Integra en cualquier lugar',
	removeNoticeBranding: 'Eliminar la marca de Notice',
	aiAssistant: 'Asistente de IA',
	customSupportAndHelp: 'Soporte y ayuda personalizados',
	premiumCdn: 'CDN premium',
	ssoEnabled: 'SSO habilitado',
	onPremiseData: 'Datos en las instalaciones',
	contentAndSeoAudit: 'Auditoría de contenido y SEO',
	downgrade: 'Degradar',
	newWorkspace: 'Nuevo espacio de trabajo',
	createANewWorkspace: 'Crear un nuevo espacio de trabajo',
	enterNameOfNewWorkspace: 'Ingresa el nombre de tu nuevo espacio de trabajo',
	create: 'Crear',
	signIn: 'Iniciar sesión',
	signInDescription:
		'Inicia sesión rápidamente usando una de tus cuentas sociales, o utiliza tu correo electrónico de trabajo.',
	signUp: 'Registrarse',
	continueWithGoogle: 'Continuar con Google',
	continueWithGithub: 'Continuar con Github',
	orSignInUsingWorkEmail: 'O inicia sesión usando tu correo electrónico de trabajo',
	enterWorkEmail: 'Ingresa tu correo electrónico de trabajo',
	enterTemporaryCode: 'Ingresa el código temporal',
	weJustSentYouATemporaryLoginCode: 'Te acabamos de enviar un código temporal de inicio de sesión.',
	pleaseCheckYourInbox: 'Por favor, revisa tu bandeja de entrada.',
	alreadyHaveAnAccountSignIn: '¿Ya tienes una cuenta? Iniciar sesión',
	continueWithLoginCode: 'Continuar con el código de inicio de sesión',
	continueWithEmail: 'Continuar con correo electrónico',
	selectYourProject: 'Selecciona tu proyecto',
	chooseYourIntegration: 'Elige tu integración',
	publishingYourProject: 'Publicando tu proyecto',
	projectCreated:
		'¡Tu proyecto Notice ha sido creado! Agrega este nuevo proyecto a tu sitio web utilizando una de nuestras integraciones o directamente a través del enlace pregenerado para ti.',
	signInMethods: 'Métodos de inicio de sesión',
	signInMethodsDescription: 'Actualiza el correo electrónico utilizado para iniciar sesión en tu cuenta',
	joinOurSlackCommunityForUpdatesAndFeedback:
		'Únete a nuestra comunidad de Slack para actualizaciones y retroalimentación, y conéctate con nosotros en las redes sociales.',
	joinSlack: 'Únete a Slack',
	joinTheAcademy: 'Únete a la Academia',
	readOurDoc: 'Lee nuestra documentación',
	checkOurTutorials: 'Consulta nuestros tutoriales',
	sendUsAnEmail: 'Envíanos un correo electrónico',
	pleaseEnterYourFirstName: 'Por favor, introduzca su nombre.',
	pleaseEnterYourLastName: 'Por favor, introduzca su apellido.',
	firstname: 'Nombre',
	lastname: 'Apellido',
	pleasEnterAValidPhoneNumber: 'Por favor, introduzca un número de teléfono válido.',
	phoneNumber: 'Número de teléfono',
	pleaseEnterYourCompanyName: 'Por favor, introduzca el nombre de su empresa.',
	companyName: 'Nombre de la empresa',
	pleaseChooseYourCompanySize: 'Por favor, elija el tamaño de su empresa.',
	companySize: 'Tamaño de la empresa',
	pleaseChooseYourRoleInTheCompany: 'Por favor, elija su rol en la empresa.',
	companyRole: 'Rol en la empresa',
	startCreating: '¡Empiece a crear!',
	welcomeToNotice: '¡Bienvenido a Notice!',
	pleaseHelpUsWithForm: 'Por favor, ayúdenos con el proceso para brindarle la experiencia completa de Notice.',
	preview: 'Previsualizar',
	rename: 'Renombrar',
	duplicate: 'Duplicar',
	exportMarkdown: 'Exportar Markdown',
	delete: 'Eliminar',
	exportJSON: 'Exportar JSON',
	type: 'Tipo',
	forCommands: 'para comandos',
	basicBlocks: 'Bloques básicos',
	paragraph: 'Párrafo',
	justWriteDownSomeText: 'Solo escribe un poco de texto',
	heading: 'Encabezado',
	bigSectionHeading: 'Encabezado de sección grande',
	mediumSectionHeading: 'Encabezado de sección mediana',
	smallSectionHeading: 'Encabezado de sección pequeña',
	bulletedList: 'Lista con viñetas',
	organizeContentWithBullets: 'Organizar contenido con viñetas',
	numberedList: 'Lista numerada',
	createANumberedList: 'Crear una lista numerada',
	captureACodeSnippet: 'Capturar un fragmento de código',
	hint: 'Pista',
	provideHelpfulInformation: 'Proporcionar información útil',
	quote: 'Cita',
	highlightASpecificPassageOfText: 'Resaltar un pasaje específico del texto',
	divider: 'Divisor',
	separateDifferentBlocks: 'Separar diferentes bloques',
	toDo: 'Por hacer',
	keepTrackOfTasksOrItems: 'Llevar un registro de tareas o elementos',
	media: 'Medios',
	image: 'Imagen',
	uploadAnImageFile: 'Subir un archivo de imagen',
	document: 'Documento',
	uploadADocument: 'Subir un documento',
	video: 'Video',
	addAVideo: 'Agregar un video',
	advancedBlocks: 'Bloques avanzados',
	table: 'Tabla',
	organizeWithRowsAndColumns: 'Organizar con filas y columnas',
	expandable: 'Expandible',
	addACollapsableBlock: 'Agregar un bloque colapsable',
	textAIGeneration: 'Generación de texto AI',
	letOurRobotCreateYourContent: 'Deja que nuestro robot cree tu contenido',
	imageAIGeneration: 'Generación de imágenes AI',
	letOurRobotCreateYourImages: 'Deja que nuestro robot cree tus imágenes',
	javascript: 'Javascript',
	embedJavascript: 'Incrustar Javascript',
	youtube: 'Youtube',
	embedYoutubeVideos: 'Incrustar videos de Youtube',
	justCopyPasteTheLinkOfYourVideo:
		'Solo copia y pega el enlace de tu video en un párrafo vacío para incrustar automáticamente un video de Youtube. Ejemplo de enlace: https://www.youtube.com/watch?v=m4fDm4rdUdk',
	embedLoomVideos: 'Incrustar videos de Loom',
	justCopyPasteLoomVideo:
		'Solo copia y pega el enlace de tu video en un párrafo vacío para incrustar automáticamente un video de Loom. Ejemplo de enlace: https://www.loom.com/share/36656bc4afb84de2bb829183f46a1b40',
	embedVimeos: 'Incrustar Vimeos',
	embedVimeosInstructions:
		'Solo copia y pega el enlace de tu video en un párrafo vacío para incrustar automáticamente un video de Vimeo. Ejemplo de enlace: https://vimeo.com/251147627',
	embedAirtableInstructions:
		'Pega el enlace de tu vista de tabla en un párrafo vacío para incrustar automáticamente un AirTable. Ejemplo de enlace: https://airtable.com/appeh8s8bwMI7JjlW/shro43JbOcXFQH0tQ/tblnrBMRpvfrcqkko',
	AIIsWriting: 'La IA está escribiendo...',
	Keep: 'Mantener',
	Retry: 'Reintentar',
	DescribeWhatYouWantAI: 'Describe lo que quieres crear a nuestra IA',
	LetOurAICreate: 'Deja que nuestra IA cree tu página',
	LetOurAICreateImage: 'Crea una imagen inspirada en esta página',
	freeTrialEndsIn: 'Su prueba gratuita terminará en X días.',
	AIIsGeneratingAnImageIdea: 'La IA está generando una idea de imagen...',
	AIIsGeneratingImage: 'La IA está generando una imagen...',
	GenImagePlaceholder: 'Un campo de girasoles al final del día. Al estilo de las pinturas de Van Gogh.',
	metadata: 'Metadatos',
	pageMetadata: 'Metadatos de la página',
	giveInformationForSEO: 'Enriquezca esta página con información para mejorar el SEO y las vistas previas',
	author: 'Autor',
	editMyName: 'Editar mi nombre',
	tags: 'Etiquetas',
	datePublished: 'Fecha de publicación',
	addATag: 'Añadir una etiqueta',
	advancedOptions: 'Opciones Avanzadas',
	tellGoogleExists: 'Dile a Google que tu proyecto existe',
	tellGoogleExistsDescription: 'Para indexar correctamente tu proyecto, necesitas verificar tu sitio web en ',
	clickHereToFollowOurGuide: 'Haz clic aquí para seguir nuestra guía',
	explanationDateOfPublication: 'Al establecer una fecha en el futuro, ocultará la página hasta la fecha elegida.',
	articleHiddenDateFuture: 'Este artículo está oculto porque la fecha está en el futuro.',
	blockMenuChangeImageCover: 'Cambiar la portada de la imagen',
	blockMenuAddImageCover: 'Añadir portada de imagen',
	blockMenuDuplicate: 'Duplicar',
	blockMenuDelete: 'Eliminar',
	blockMenuOnlyText: 'Solo texto',
	blockMenuWithImage: 'Con imagen',
	blockMenuPageSummary: 'Resumen de la página',
	blockMenuBorder: 'Borde',
	blockMenuLayout: 'Diseño',
	blockMenuDisplay: 'Visualización',
	blockMenuStyle: 'Estilo',
	subPageUpgradeSucessTitle: 'Actualización Exitosa',
	subPageUpgradeSuccessMsg:
		'¡Felicidades! 🎉 Tu cuenta ha sido actualizada con éxito. Gracias por elegir Notice para mejorar tu experiencia!',
	subPageGoBack: 'Volver a la edición',
	deleteProjectDeleteProject: 'Eliminar proyecto',
	deleteProjectAreYouSure: '¿Estás seguro de que quieres eliminar este proyecto?',
	deleteWarning: 'Esta acción no se puede deshacer.',
	cancelButton: 'Cancelar',
	confirmButton: 'Confirmar',
	deletePageDeletePage: 'Eliminar página',
	deletePageAreYouSure:
		'Esta acción eliminará permanentemente esta página y todo su contenido relacionado, ¿estás seguro de que quieres continuar?',
	pasteLinkHere: 'Pegar enlace aquí',
	addLink: 'Agregar enlace',
	removeLink: 'Eliminar enlace',
	selectAnImage: 'Seleccionar una imagen',
	selectADocument: 'Seleccionar un documento',
	selectAVideo: 'Seleccionar un video',
	selectAnAudio: 'Seleccionar un audio',
	dropYourFileHere: 'Deje caer su archivo aquí para comenzar a cargar o',
	anyDocTypeAccepted: 'Se acepta cualquier tipo de documento',
	acceptedTypes: 'Tipos aceptados',
	browseFiles: 'Explorar archivos',
	filterFiles: 'Filtrar archivos',
	files: 'Archivos',
	enterAnURL: 'Introduce una URL',
}
