export const fr = {
	customization: 'Personnalisation',
	translation: 'Traduction',
	integrations: 'Intégrations',
	insights: 'Statistiques',
	FreePlan: 'Plan gratuit',
	upgrade: 'Mettre à niveau',
	yourProfile: 'Votre profil',
	general: 'Genéral',
	layout: 'Disposition',
	theme: 'Thème',
	advanced: 'Avancé',
	styling: 'Style',
	code: 'Code',
	billing: 'Facturation',
	aiSettings: 'Paramètres IA',
	aiSettingsDescription:
		"Bienvenue dans les paramètres de l'IA, où vous contrôlez comment notre IA génère du contenu pour cet espace de travail",
	aiSettingSection1Description:
		"Aidez-nous à comprendre votre ligne de travail ou l'orientation de votre entreprise. Veuillez fournir une brève description de votre entreprise ou profession.",
	aiSettingSection1Placeholder:
		'Je dirige une agence créative spécialisée dans les stratégies de marketing digital et la création de contenu',
	aiSettingSection2: 'Quel est votre ton?',
	aiSettingSection2Description:
		'Définissez le ton que vous souhaitez pour le texte de votre espace de travail. Partagez avec nous le type de ton qui correspond à votre style de communication.',
	aiSettingSection2Placeholder:
		"Nous sonnons professionnels mais amicaux, partageant notre expertise d'une manière facile à connecter",
	aiSettingSection3: "Aperçu de votre style d'écriture préféré",
	aiSettingSection3Description:
		"Fournissez un ou deux exemples de votre style d'écriture ou un passage de l'un de vos textes préférés. Notre IA s'adaptera et fournira le texte dans le même style.",
	aiSettingSection3Placeholder: `Le fort, c'est celui qui sait où il est fort, le brave, c'est celui qui va jusqu'où il est brave.`,
	aiSettingsModelSettings: "Paramètres du modèle d'IA",
	aiSettingModelSection: "Choisissez votre modèle d'IA",
	aiSettingModelSectionDescription:
		"Sélectionnez le modèle de génération d'IA qui correspond le mieux à vos préférences.",
	aiSettingGPT4Tooltip: 'Plus optimisé',
	aiSettingGPT3Tooltip: 'Plus rapide',
	edit: 'modifier',
	save: 'sauvegarder',
	skip: 'sauter',
	changeAISettings: "Modifier les paramètres de l'IA",
	aiSettingSection1: 'Que faites-vous ?',
	PleaseClickToEditTheSettings: 'Veuillez cliquer pour modifier les paramètres',
	billingDetailsAndInvoices: 'Détails de facturation & Factures',
	overview: 'Aperçu',
	currentPlan: 'Formule actuelle',
	nextBillingOn: 'Prochaine facturation le',
	nextBillingAmount: 'Montant de la prochaine facturation',
	numberOfProjects: 'Nombre de projets',
	reachesSubscriptionPage: "Accéder à la page d'abonnement",
	billingPageUpgradeButton: 'Bouton de mise à niveau de la page de facturation',
	upgradeYourPlan: 'Améliorez votre Formule',
	billingInfoAndPayment: 'Informations de facturation & Paiement',
	manageAllYourBilling: 'Gérez toutes vos informations de facturation et méthodes de paiement ici',
	manageBillingDetails: 'Gérer les détails de facturation',
	invoicesHistory: 'Historique des factures',
	invoiceID: 'ID de facture',
	date: 'Date',
	total: 'Total',
	status: 'Statut',
	invoiceReceipt: 'Facture/Reçu',
	download: 'Télécharger',
	noInfoAvailableYet: 'Aucune information disponible pour le moment',
	hideBranding: 'Masquer la marque',
	hideBrandingDescription: 'Cache la marque Notice sur vos projets.',
	handleTitleTagTitle: 'Gestion de la balise <title />',
	titleTagDescription: 'Quand activé, Notice va gérer la balise <title /> de votre projet.',
	projectLogo: 'Logo du projet',
	projectLogoDescription: 'Le logo de votre projet peut être affiché à différents endroits de votre projet.',
	faviconDescription: 'Utilisez votre logo comme favicon.',
	faviconWarning: (
		<span>
			Vous devez télécharger un <b>Logo du projet</b> ci-dessus pour activer cette fonctionnalité.
		</span>
	),
	uploadImage: 'Télécharger une image',
	configureLogoRedirect: `Configurer l'adresse vers laquelle redirige le logo`,
	navigationType: 'Type de navigation',
	navigationTypeDescription: `Query param utilisera la valeur 'page=' dans l'URL pour gérer la navigation. Slash utilisera le sous-dossier classique '/'.`,
	stopUserTracking: 'Arrêter le suivi',
	stopUserTrackingDescription: 'Notice ne collectera pas de données pour vous fournir des statistiques.',
	stopUserTrackingWarning: <span>Le tableau de bord des statistiques sera désactivé.</span>,
	headerSpace: "Espace d'en-tête",
	projectTitle: 'Titre du projet',
	homeButton: "Bouton d'accueil",
	topSpace: 'Espace supérieur',
	contactForm: 'Formulaire de contact',
	emailToReceiveMessages: 'Email pour recevoir les messages',
	themeSwitch: 'Changement de thème',
	languageSelector: 'Sélecteur de langue',
	breadcrumbNavigation: "Navigation par fil d'Ariane",
	timeToRead: 'Temps de lecture',
	shareToFacebook: 'Partager sur Facebook',
	shareToTwitter: 'Partager sur Twitter',
	shareToLinkedIn: 'Partager sur LinkedIn',
	leftSpace: 'Espace gauche',
	navigationMenu: 'Menu de navigation',
	rightSpace: 'Espace droit',
	anchorMenu: 'Menu ancre',
	bottomSpace: 'Espace inférieur',
	bottomNavigation: 'Navigation inférieure',
	readMoreArticles: "Lire plus d'articles",
	setProjectTitle: 'Définir le titre du projet',
	setProjectTitleDescription: 'Affiche le nom du projet en haut de chaque page.',
	NavMenuDesc: 'Menu de navigation à gauche qui donne un accès facile à votre projet.',
	searchDescription: 'Permet à l’utilisateur de rechercher dans votre projet. Vous aurez également',
	analyticsSupport: 'des rapports d’analyse',
	searchDescription2: 'depuis Notice à propos de ces requêtes.',
	themeSwitchDescription:
		'Vous pouvez permettre aux utilisateurs de changer le thème de votre projet. Vous pouvez configurer votre thème',
	hereInsideColors: 'ici dans les couleurs.',
	languageSwitchDescription: `Vous pouvez permettre aux utilisateurs de changer la langue de votre projet. Vous pouvez configurer vos traductions`,
	here: 'ici',
	allowNavDescription: `Permet aux utilisateurs de naviguer entre les pages en utilisant le menu de navigation.`,
	displayHomeButtonDescription: `Affiche un bouton pour permettre aux utilisateurs de naviguer vers la page d'accueil.`,
	timeToReadDescription: `Affiche le temps de lecture estimé d'une page.`,
	facebookShareDescription: `Permet aux utilisateurs de partager vos articles sur Facebook.`,
	twitterShareDescription: `Permet aux utilisateurs de partager vos articles sur Twitter.`,
	linkedinShareDescription: `Permet aux utilisateurs de partager vos articles sur LinkedIn.`,
	nextPrevDescription: 'Ajoute des boutons pour naviguer vers les pages suivantes et précédentes en bas de page.',
	anchorRightMenuDescription: `Ajoute un menu de navigation à droite qui permet aux utilisateurs de naviguer entre les titres de la page.`,
	allowRecommendedArticlesDescription: `Permet aux utilisateurs de lire plus d'articles liés à celui en cours.`,
	navMenuDesc: `Ajoute un menu de navigation à gauche qui permet aux utilisateurs de naviguer entre les pages.`,
	pageTitle: 'Titre de la page',
	colors: 'Couleurs',
	lightBgColor: 'Couleur de fond clair',
	lightFontColor: 'Couleur de police claire',
	lightHighlightColor: 'Couleur de surbrillance claire',
	darkBgColor: 'Couleur de fond sombre',
	darkFontColor: 'Couleur de police sombre',
	darkHighlightColor: 'Couleur de surbrillance sombre',
	fonts: 'Polices',
	fontFamily: 'Police de caractères',
	fontSize: 'Taille de police',
	spacing: 'Espacement',
	blockPadding: 'Espacement des blocs',
	maxWidth: 'Largeur maximale',
	maxWidthDescription: 'définir la largeur maximale pour la colonne principale',
	icons: 'Icônes',
	iconStroke: 'Épaisseur du trait',
	headings: 'Titres',
	h1Weight: 'Épaisseur H1',
	h1Size: 'Taille H1',
	h2Size: 'Taille H2',
	h2Weight: 'Épaisseur H2',
	h3Size: 'Taille H3',
	h3Weight: 'Épaisseur H3',
	headingsPadding: 'Espacement des titres',
	titleFontSize: 'Taille de police du titre',
	fontFamilyDescription:
		'Parcourez les différentes polices sur <a href="https://fonts.google.com/" target="_blank">Google Fonts.</a>',
	text: 'Texte',
	textLineHeight: 'Hauteur de ligne',
	textLetterSpacing: 'Espacement des lettres',
	codeHtmlDesc: `Le code écrit sera inséré dans la balise `,
	codeHtmlDesc2: ' de votre projet Notice.',
	CSSDesc: "Écrivez du code CSS changer l'apparence de votre projet.",
	JavascriptDesc: 'Écrivez du code Javascript pour changer le comportement de votre projet.',
	insightsDesc: 'Améliorez votre contenu et le support client avec des données sur le comportement des utilisateurs.',
	publishing: 'Publication',
	publish: 'Publier',
	visitPage: 'Visiter la page',
	newProject: 'Nouveau projet',
	createNewProject: 'Créer un nouveau projet',
	newPage: 'Nouvelle page',
	addNewPage: 'Ajouter une nouvelle page au projet actuel',
	workspaceSettings: 'Paramètres de l’espace de travail',
	accountSettings: 'Paramètres du compte',
	supportAndCommunity: 'Support & Communauté',
	signOut: 'Déconnexion',
	whatIsNew: 'Quoi de neuf',
	inviteCollaborators: 'Inviter des collaborateurs',
	inviteCollaboratorsDescription:
		'Plus on est de fous, plus on rit. Invitez vos collaborateurs à rejoindre votre projet.',
	emailAddress: 'Adresse email',
	admin: 'Administrateur',
	editor: 'Éditeur',
	viewer: 'Lecteur',
	owner: 'Propriétaire',
	close: 'Fermer',
	invite: 'Inviter',
	translationDescription: 'Traduisez votre contenu dans plus de 100 langues.',
	selectBlock: 'Vous pouvez sélectionner un bloc en cliquant sur le',
	selectProjectLanguage: 'Sélectionnez la langue par défaut de ce projet',
	validate: 'Valider',
	selectLanguageHint: 'Astuce : c’est la langue de votre projet actuel.',
	configureTranslation: 'Configurer la traduction',
	translationStatus: 'Statut de la traduction',
	selected: 'Sélectionné',
	translated: 'Traduit',
	notTranslated: 'Non traduit',
	translationOutOfDate: 'Traduction obsolète',
	translateBlock: 'Traduire le bloc',
	markAsIncomplete: 'Marquer comme incomplet',
	markAsComplete: 'Marquer comme complet',
	markAsCompleteAndGoToNext: 'Marquer comme complet et passer au suivant',
	anotherNoticeTabIsOpened: 'Une autre fenêtre Notice est ouverte',
	pleaseReloadToAvoidMismatch: 'Veuillez recharger la page pour éviter les conflits.',
	reload: 'Recharger',
	oopsNoResultsWereFound: 'Oups ! Aucun résultat n’a été trouvé.',
	tryAgainNoResults: 'Essayez de nouveau avec une autre période.',
	configureYourTranslation: 'Configurez vos traductions',
	allowUsersToChangeLang: 'Permettre aux utilisateurs de changer la langue',
	addsALangQueryLike: 'Ajoute un paramètre de langue comme',
	toYourProjectUrl: 'à vos URLs de projet',
	addLanguageQueryToUrl: 'Ajouter un paramètre de langue à l’URL',
	chooseADefaultLanguage: 'Choisissez une langue par défaut',
	availableLanguages: 'Langues disponibles',
	ifYouWantMoreLanguages: 'Si vous souhaitez plus de langues,',
	contactUs: 'Contactez-nous',
	letUsKnow: 'faites le nous savoir.',
	languageSelectorWarning: `Le sélecteur de langue peut également être géré dans la disposition en`,
	clickingHere: 'cliquant ici',
	addNew: 'Ajouter',
	translateTo: 'Traduire en',
	translateThisPage: 'Traduire cette page',
	stepByStepGuide: 'Guide étape par étape',
	manyHandsMakeLightWork: 'Plusieurs mains rendent le travail plus léger',
	createAndCustomizeContent: 'Créez et personnalisez votre contenu',
	clickOnPublish: 'Cliquez sur Publier',
	deployItAnywhere: 'Déployez-le n’importe où en cliquant sur Intégrations',
	inviteColleaguesToCollaborate: 'Invitez vos collègues pour travailler ensemble sur vos projets.',
	inviteYourTeam: 'Invitez votre équipe',
	getInTouchWithUs: 'Contactez-nous',
	getInTouchDescription: `Vous avez des suggestions ou besoin d'aide ? Envoyez-nous un message ou rejoignez notre communauté Slack.`,
	accountSettingsDescription: 'Gérez vos informations de compte, préférences et paramètres de connexion.',
	dashboardLanguage: "Langue de l'interface",
	updateEmail: 'Mettre à jour l’email',
	featureComingSoon: 'Fonctionnalité à venir prochainement...',
	signOnWithGoogle: 'Mettez en place la synchronisation avec Google en un seul clic',
	yourGoogleAccountHasBeenUnlinked: 'Votre compte Google a été déconnecté avec succès.',
	unlinkAccount: 'Déconnecter le compte',
	linkAccount: 'Connecter le compte',
	singleSignOnGithub: 'Connexion unique avec Github en un seul clic',
	githubAccountHasBeenUnlinked: 'Votre compte Github a été déconnecté avec succès.',
	signOutDescription: 'Vous pouvez vous déconnecter de votre compte Notice',
	accountDeletion: 'Suppression du compte',
	accountDeletionDescription: 'Vous pouvez supprimer votre compte Notice et toutes les données associées',
	deleteAccount: 'Supprimer le compte',
	deleteMyAccountBody: 'Bonjour, je souhaite supprimer mon compte.',
	deleteMyAccountSubject: 'Suppression du compte',
	settings: 'Paramètres',
	account: 'Compte',
	myWorkspaces: 'Mes espaces de travail',
	workspace: 'Espace de travail',
	collaborators: 'Collaborateurs',
	plans: 'Formules',
	profilePicture: 'Photo de profil',
	profilePictureDescription: `Utilisez une image carrée d'au moins 64 pixels de côté`,
	fullName: 'Nom complet',
	myWorkspacesDescription: `Une page pour visualiser l'ensemble de vos espaces de travail`,
	workspaces: 'Espaces de travail',
	created: 'Créé le',
	manageWorkspaceProfile: 'Gérer le profil de l’espace de travail',
	workspaceProfile: 'Profil de l’espace de travail',
	workspaceLogo: 'Logo de l’espace de travail',
	displayName: 'Nom d’affichage',
	workspaceDeletion: 'Suppression de l’espace de travail',
	workspaceDeletionDescription: 'Vous pouvez supprimer votre espace de travail et toutes les données associées',
	deleteWorkspace: 'Supprimer l’espace de travail',
	storage: 'Stockage',
	storageDescription: `(images, vidéos, fichiers, ...)`,
	deleteWorkspaceDescription: 'Êtes-vous sûr de voulour supprimer cet espace de travail?',
	deleteWorkspaceWarning: 'Cette action est irréversible',
	cancel: 'Annuler',
	confirm: 'Confirmer',
	visits: 'Visites',
	statistics: 'Statistiques',
	visitsByTimeSpan: 'Visites par période',
	location: 'Localisation',
	locationDescription: 'La localisation de vos visiteurs',
	device: 'Appareil',
	deviceDescription: 'L’appareil utilisé par vos visiteurs',
	browser: 'Navigateur',
	browserDescription: 'Le navigateur utilisé par vos visiteurs',
	OSdescription: 'Le système d’exploitation utilisé par vos visiteurs',
	integration: 'Intégration',
	hosting: 'Hébergement',
	noticeDomain: 'Domaine Notice',
	noticeDomainDescription: 'Changez le nom de domaine de votre projet Notice',
	allowedCharacters: 'Caractères autorisés',
	letters: 'lettres',
	numbers: 'chiffres',
	and: 'et',
	domainName: 'Nom de domaine',
	customDomainDescription: 'Vous pouvez utiliser un nom de domaine personnalisé pour votre projet.',
	customDomain: 'Domaine personnalisé',
	customDomainMissing: `Vous n'avez pas encore configuré de domaines personnalisés pour ce projet`,
	customDomainPresent: `Vous avez déjà configuré un domaine personnalisé pour ce projet`,
	configure: 'Configurer',
	whatDomainWouldYouLikeToLink: 'Quel domaine souhaitez-vous lier à votre projet ?',
	hostnameIsInvalid: 'Le nom d’hôte est invalide. Seuls les sous-domaines sont autorisés.',
	mustOwnSubdomainAndAbilityToEditDNS: `Vous devez posséder le sous-domaine et avoir la possibilité d'éditer les enregistrements DNS.`,
	configureDNS: 'Configurer les enregistrements DNS',
	others: 'Autres',
	webflowIntegration: 'Ajoutez des blocs Notice à votre site Webflow en un seul clic',
	wordpressIntegration: 'Installez le plugin Notice pour un contenu impeccable sur Wordpress',
	shopifyIntegration: `Améliorez l'expérience de vos clients sur votre boutique Shopify`,
	umsoIntegration: 'Ajoutez des blocs Notice à votre site UMSO et récupérez des statistiques sur vos visiteurs',
	unicornIntegration: `Améliorer et personnaliser votre site Web avec des blocs intelligents en un clin d'oeil`,
	wixIntegration: `Having Notice inside Wix is easy. Just add an embed block and integration is done!`,
	squarespaceIntegration: `It's fast, as usual. Add a code block and paste your Notice ID to have your content ON.`,
	reactIntegration: 'Blocs Notice facilement intégrés dans React en une seule étape.',
	nextIntegration: 'Pour les amateurs du framework frontend SSR Next.js, intégration fluide.',
	vueIntegration: "Intégrez Notice dans votre projet Vue.js en moins d'une minute.",
	nuxtIntegration: 'Pour les amateurs du framework frontend SSR Nuxt, intégration fluide.',
	linkIntegration: "La solution la plus simple, partagez juste le lien ! Vous n'avez même pas besoin d'un site web.",
	htmlIntegration: 'La solution préférée pour les sites web si vous ne trouvez pas votre framework spécifique.',
	iframeIntegration: "Facile à utiliser, les iframes s'adaptent partout, même dans les applications mobiles.",
	rawJSONIntegration: 'Pour les utilisateurs avancés qui veulent un contrôle total sur leurs projets.',
	qrcodeIntegration: 'Votre contenu au bout des doigts des utilisateurs ! Partagez votre propre QR code :)',
	integrationsDescription: 'Intégrez Notice à votre site Web en un seul clic',
	categories: 'Catégories',
	all: 'Tous',
	needADifferentIntegrationAndCannotFindItHere: 'Vous avez besoin d’une autre intégration et ne la trouvez pas ici ?',
	shareables: 'Partageables',
	useTemplates: 'Modèles',
	useAIGeneration: `Utilisez l'IA`,
	selectProjectTip: `Vous pouvez utiliser l'IA ou des projets exemples pour générer du contenu.`,
	preFilledTemplate: 'Modèle pré-rempli',
	helpCenter: 'Centre d’aide',
	termsOfuse: 'Conditions d’utilisation',
	privacyPolicy: 'Politique de confidentialité',
	jobBoard: 'Offres d’emploi',
	getStarted: 'Tutoriel',
	changelog: 'Journal des modifications',
	missionAndValues: 'Mission et valeurs',
	investorsReport: 'Rapport investisseurs',
	aboutUs: 'À propos',
	startFromScratch: 'Commencer avec une page blanche',
	helpOurAIGenerateYour: 'Aidez notre IA à générer votre',
	provideYourWebsiteURL: 'Fournissez l’URL de votre site Web',
	weFoundAWebsite: `Nous avons trouvé un site lié à votre adresse e-mail`,
	makeSureProvidedWebsiteAlreadyExists: `Assurez-vous que le site Web fourni existe déjà`,
	AIExplanation: `Notre IA va analyser votre site pour générer un(e)`,
	basedOnTheWebsiteInformation: `basé sur les informations reccueillies.`,
	youCanUseAnyExistingURL: `Vous pouvez utiliser n’importe quelle URL existante.`,
	enhanceYourGeneration: `Améliorez votre génération en ajoutant plus d'instructions`,
	giveInstructions: `Donnez des instructions à notre IA pour générer votre`,
	makeSureThisPromptIsMatching: `Assurez-vous que cette instruction correspond à votre type de projet.`,
	writeItInFrenchOnlyUsePastTense: `Exemple: Écrivez-le en français et utilisez uniquement le passé.`,
	backToList: 'Retour à la liste',
	pricingDescription: `Nos prix sont sans frais cachés et alignés avec vos objectifs.`,
	monthlyTokenAmount: 'Nombre de jetons mensuels',
	billingPeriod: 'Période de facturation',
	monthly: 'Mensuel',
	yearly: 'Annuel',
	oneMonthFree: '1 mois gratuit',
	customizeYourNewContentsHome: 'Une nouvelle maison pour votre contenu',
	manageSmartContentForYourCompany: 'Créez et gérez du contenu intelligent',
	activateContentSynergiesForYourTeam: 'Activez les synergies de contenu pour votre équipe',
	forThoseNeedingAnEnterpriseGradeSolution: 'Pour ceux qui ont besoin d’une solution "entreprise"',
	letsTalk: 'Parlons-en',
	numberOfCollaborators: 'Nombre de collaborateurs',
	numberOfWorkspaces: "Nombre d'espaces de travail",
	integrateAnywhere: 'Intégration partout',
	removeNoticeBranding: 'Supprimer le branding Notice',
	aiAssistant: 'Assistant IA',
	customSupportAndHelp: 'Support et aide personnalisés',
	premiumCdn: 'CDN premium',
	ssoEnabled: 'SSO activé',
	onPremiseData: 'Données sur site',
	contentAndSeoAudit: 'Audit de contenu & SEO',
	downgrade: 'Résilier',
	newWorkspace: 'Nouvel espace de travail',
	createANewWorkspace: 'Créez un nouvel espace de travail',
	enterNameOfNewWorkspace: 'Entrez le nom de votre nouvel espace de travail',
	create: 'Créer',
	signIn: 'Se connecter',
	signInDescription:
		'Connectez-vous à votre compte Notice avec des comptes de réseaux sociaux, ou utilisez votre email.',
	signUp: 'S’inscrire',
	continueWithGoogle: 'Continuer avec Google',
	continueWithGithub: 'Continuer avec Github',
	orSignInUsingWorkEmail: 'Ou connectez-vous avec votre email professionnel',
	enterWorkEmail: 'Entrez votre email professionnel',
	enterTemporaryCode: 'Entrez le code temporaire',
	weJustSentYouATemporaryLoginCode: 'Nous venons de vous envoyer un code de connexion éphémère',
	pleaseCheckYourInbox: 'Veuillez vérifier votre boîte de réception.',
	alreadyHaveAnAccountSignIn: 'Vous avez déjà un compte ? Connectez-vous',
	continueWithLoginCode: 'Continuer avec le code de connexion',
	continueWithEmail: 'Continuer avec l’email',
	selectYourProject: 'Sélectionnez votre projet',
	chooseYourIntegration: 'Choisissez votre intégration',
	publishingYourProject: 'Publication de votre projet',
	projectCreated:
		"Votre projet Notice a été créé ! Ajoutez ce nouveau projet à votre site Web en utilisant l'une de nos intégrations ou directement via le lien pré-généré pour vous.",
	signInMethods: 'Méthodes de connexion',
	signInMethodsDescription: 'Gérez les méthodes de connexion de votre compte',
	joinOurSlackCommunityForUpdatesAndFeedback:
		'Rejoignez notre communauté Slack pour les mises à jour et les commentaires',
	joinSlack: 'Rejoindre Slack',
	joinTheAcademy: 'Rejoignez l’Académie',
	readOurDoc: 'Lisez notre documentation',
	checkOurTutorials: 'Consultez nos tutoriels',
	sendUsAnEmail: 'Envoyez-nous un email',
	pleaseEnterYourFirstName: 'Veuillez entrer votre prénom.',
	pleaseEnterYourLastName: 'Veuillez entrer votre nom de famille.',
	firstname: 'Prénom',
	lastname: 'Nom de famille',
	pleasEnterAValidPhoneNumber: 'Veuillez entrer un numéro de téléphone valide.',
	phoneNumber: 'Numéro de téléphone',
	pleaseEnterYourCompanyName: 'Veuillez entrer le nom de votre entreprise.',
	companyName: "Nom de l'entreprise",
	pleaseChooseYourCompanySize: 'Veuillez choisir la taille de votre entreprise.',
	companySize: "Taille de l'entreprise",
	pleaseChooseYourRoleInTheCompany: "Veuillez choisir votre rôle dans l'entreprise.",
	companyRole: "Rôle dans l'entreprise",
	startCreating: 'Commencez à créer !',
	welcomeToNotice: 'Bienvenue chez Notice !',
	pleaseHelpUsWithForm: 'Nous aimerions mieux vous connaître pour vous fournir une expérience optimale.',
	preview: 'Aperçu',
	rename: 'Renommer',
	duplicate: 'Dupliquer',
	exportMarkdown: 'Exporter en Markdown',
	delete: 'Supprimer',
	exportJSON: 'Exporter en JSON',
	type: 'Tapez',
	forCommands: 'pour les commandes',
	basicBlocks: 'Blocs de base',
	paragraph: 'Paragraphe',
	justWriteDownSomeText: 'Écrivez simplement du texte',
	heading: 'Titre',
	bigSectionHeading: 'Grand titre de section',
	mediumSectionHeading: 'Titre de section moyen',
	smallSectionHeading: 'Petit titre de section',
	bulletedList: 'Liste à puces',
	organizeContentWithBullets: 'Organiser le contenu avec des puces',
	numberedList: 'Liste numérotée',
	createANumberedList: 'Créer une liste numérotée',
	captureACodeSnippet: 'Capturer un extrait de code',
	hint: 'Indice',
	provideHelpfulInformation: 'Fournir des informations utiles',
	quote: 'Citation',
	highlightASpecificPassageOfText: 'Mettre en évidence un passage spécifique du texte',
	divider: 'Diviseur',
	separateDifferentBlocks: 'Séparer différents blocs',
	toDo: 'À faire',
	keepTrackOfTasksOrItems: 'Suivre les tâches ou les éléments',
	media: 'Média',
	image: 'Image',
	uploadAnImageFile: 'Télécharger un fichier image',
	document: 'Document',
	uploadADocument: 'Télécharger un document',
	video: 'Vidéo',
	addAVideo: 'Ajouter une vidéo',
	advancedBlocks: 'Blocs avancés',
	table: 'Tableau',
	organizeWithRowsAndColumns: 'Organiser avec des rangées et des colonnes',
	expandable: 'Extensible',
	addACollapsableBlock: 'Ajouter un bloc repliable',
	textAIGeneration: 'Génération de texte IA',
	letOurRobotCreateYourContent: 'Laissez notre robot créer votre contenu',
	imageAIGeneration: "Génération d'images IA",
	letOurRobotCreateYourImages: 'Laissez notre robot créer vos images',
	javascript: 'Javascript',
	embedJavascript: 'Intégrer Javascript',
	youtube: 'Youtube',
	embedYoutubeVideos: 'Intégrer des vidéos Youtube',
	justCopyPasteTheLinkOfYourVideo:
		'Copiez et collez simplement le lien de votre vidéo dans un paragraphe vide pour intégrer automatiquement une vidéo Youtube. Lien exemple: https://www.youtube.com/watch?v=m4fDm4rdUdk',
	embedLoomVideos: 'Intégrer des vidéos Loom',
	justCopyPasteLoomVideo:
		'Copiez et collez simplement le lien de votre vidéo dans un paragraphe vide pour intégrer automatiquement une vidéo Loom. Lien exemple: https://www.loom.com/share/36656bc4afb84de2bb829183f46a1b40',
	embedVimeos: 'Intégrer des vidéos Vimeo',
	embedVimeosInstructions:
		'Copiez et collez simplement le lien de votre vidéo dans un paragraphe vide pour intégrer automatiquement une vidéo Vimeo. Lien exemple: https://vimeo.com/251147627',
	embedAirtableInstructions:
		'Collez le lien de votre vue de tableau dans un paragraphe vide pour intégrer automatiquement un AirTable. Lien exemple: https://airtable.com/appeh8s8bwMI7JjlW/shro43JbOcXFQH0tQ/tblnrBMRpvfrcqkko',
	AIIsWriting: "L'IA est en train d'écrire...",
	Keep: 'Garder',
	Retry: 'Réessayer',
	DescribeWhatYouWantAI: 'Décrivez ce que vous voulez créer à notre IA',
	LetOurAICreate: 'Laissez notre IA créer votre page',
	LetOurAICreateImage: 'Créez une image inspirée de cette page',
	freeTrialEndsIn: "Votre période d'essai se termine dans X jours.",
	AIIsGeneratingAnImageIdea: "L'IA génère une idée d'image...",
	AIIsGeneratingImage: "L'IA génère une image...",
	GenImagePlaceholder: 'Un champ de tournesols en fin de journée. Dans le style des peintures de Van Gogh.',
	metadata: 'Métadonnées',
	pageMetadata: 'Métadonnées de la page',
	giveInformationForSEO: 'Enrichissez cette page avec des informations pour améliorer le SEO et les aperçus',
	author: 'Auteur',
	editMyName: 'Modifier mon nom',
	tags: 'Thèmes',
	datePublished: 'Date de publication',
	addATag: 'Ajouter un thème',
	advancedOptions: 'Options avancées',
	tellGoogleExists: 'Dites à Google que votre projet existe',
	tellGoogleExistsDescription: 'Pour indexer correctement votre projet, vous devez vérifier votre site web sur ',
	clickHereToFollowOurGuide: 'Cliquez ici pour suivre notre guide',
	explanationDateOfPublication: "En définissant une date dans le futur, cela cachera la page jusqu'à la date choisie.",
	articleHiddenDateFuture: 'Cet article est caché car la date est dans le futur.',
	blockMenuChangeImageCover: "Changer l'image de couverture",
	blockMenuAddImageCover: 'Ajouter une image de couverture',
	blockMenuDuplicate: 'Dupliquer',
	blockMenuDelete: 'Supprimer',
	blockMenuOnlyText: 'Texte seulement',
	blockMenuWithImage: 'Avec image',
	blockMenuPageSummary: 'Résumé de la page',
	blockMenuBorder: 'Bordure',
	blockMenuLayout: 'Disposition',
	blockMenuDisplay: 'Affichage',
	blockMenuStyle: 'Style',
	subPageUpgradeSucessTitle: 'Mise à niveau Réussie',
	subPageUpgradeSuccessMsg:
		'Félicitations ! 🎉 Votre compte a été mis à niveau avec succès. Merci d’avoir choisi Notice pour améliorer votre expérience !',
	subPageGoBack: 'Retour à l’édition',
	deleteProjectDeleteProject: 'Supprimer le projet',
	deleteProjectAreYouSure: 'Êtes-vous sûr de vouloir supprimer ce projet ?',
	deleteWarning: 'Cette action ne peut pas être annulée.',
	cancelButton: 'Annuler',
	confirmButton: 'Confirmer',
	deletePageDeletePage: 'Supprimer la page',
	deletePageAreYouSure:
		'Cette action supprimera définitivement cette page et tout son contenu associé, êtes-vous sûr de vouloir continuer ?',
	pasteLinkHere: 'Coller le lien ici',
	addLink: 'Ajouter un lien',
	removeLink: 'Supprimer le lien',
	selectAnImage: 'Sélectionner une image',
	selectADocument: 'Sélectionner un document',
	selectAVideo: 'Sélectionner une vidéo',
	selectAnAudio: 'Sélectionner un audio',
	dropYourFileHere: 'Déposez votre fichier ici pour commencer le téléchargement ou',
	anyDocTypeAccepted: 'Tout type de document est accepté',
	acceptedTypes: 'Types acceptés',
	browseFiles: 'Parcourir les fichiers',
	filterFiles: 'Filtrer les fichiers',
	files: 'Fichiers',
	enterAnURL: 'Entrez un URL',
}
