export const it = {
	customization: 'Personalizzazione',
	translation: 'Traduzione',
	integrations: 'Integrazioni',
	insights: 'Approfondimenti',
	FreePlan: 'Piano Gratuito',
	upgrade: 'Aggiornamento',
	yourProfile: 'Il tuo profilo',
	general: 'Generale',
	layout: 'Layout',
	theme: 'Tema',
	advanced: 'Avanzate',
	styling: 'Stilizzazione',
	code: 'Codice',
	billing: 'Fatturazione',
	aiSettings: 'Impostazioni IA',
	aiSettingsDescription:
		'Benvenuto nelle Impostazioni IA, dove controlli come la nostra IA genera contenuto per questo spazio di lavoro',
	aiSettingSection1: 'Cosa fai?',
	aiSettingSection1Description:
		"Aiutaci a capire la tua linea di lavoro o l'obiettivo della tua azienda. Fornisci una breve descrizione della tua attività o professione.",
	aiSettingSection1Placeholder:
		"Dirigo un'agenzia creativa specializzata in strategie di marketing digitale e creazione di contenuti",
	aiSettingSection2: 'Qual è il tuo tono?',
	aiSettingSection2Description:
		'Definisci il tono che desideri per il testo nel tuo spazio di lavoro. Condividi con noi il tipo di tono che si allinea con il tuo stile di comunicazione.',
	aiSettingSection2Placeholder:
		'Siamo professionali ma amichevoli, condividendo la nostra competenza in un modo che è facile da collegare',
	aiSettingSection3: 'Anteprima del tuo stile di scrittura preferito',
	aiSettingSection3Description:
		'Fornisci uno o due esempi del tuo stile di scrittura o un passaggio di uno dei tuoi pezzi di scrittura preferiti. Il nostro AI si adatterà e fornirà il testo nello stesso stile.',
	aiSettingSection3Placeholder: `Il fatto è che bisogna avere cambiato molto per rimanere sempre lo stesso.`,
	aiSettingsModelSettings: 'Impostazioni del Modello AI',
	aiSettingModelSection: 'Scegli il tuo modello di intelligenza artificiale',
	aiSettingModelSectionDescription: 'Seleziona il modello di generazione AI che meglio si adatta alle tue preferenze.',
	aiSettingGPT4Tooltip: 'Più ottimizzato',
	aiSettingGPT3Tooltip: 'Più veloce',
	edit: 'modifica',
	save: 'salva',
	skip: 'saltare',
	changeAISettings: "Modifica le impostazioni dell'IA",
	billingDetailsAndInvoices: 'Dettagli di fatturazione & Fatture',
	PleaseClickToEditTheSettings: 'Si prega di fare clic per modificare le impostazioni',
	overview: 'Panoramica',
	currentPlan: 'Piano corrente',
	nextBillingOn: 'Prossima fatturazione il',
	nextBillingAmount: 'Importo della prossima fatturazione',
	numberOfProjects: 'Numero di progetti',
	reachesSubscriptionPage: 'Raggiunge la pagina di sottoscrizione',
	billingPageUpgradeButton: 'Pulsante di aggiornamento della pagina di fatturazione',
	upgradeYourPlan: 'Aggiorna il tuo piano',
	billingInfoAndPayment: 'Informazioni di fatturazione & Pagamento',
	manageAllYourBilling: 'Gestisci tutte le tue informazioni di fatturazione e metodi di pagamento qui',
	manageBillingDetails: 'Gestisci i dettagli di fatturazione',
	invoicesHistory: 'Cronologia fatture',
	invoiceID: 'ID Fattura',
	date: 'Data',
	total: 'Totale',
	status: 'Stato',
	invoiceReceipt: 'Ricevuta Fattura',
	download: 'Scarica',
	noInfoAvailableYet: 'Nessuna informazione disponibile ancora',
	hideBranding: 'Nascondi il branding',
	hideBrandingDescription: 'Nasconde il branding di Notice sul tuo progetto.',
	handleTitleTagTitle: 'Gestisci il tag <title />',
	titleTagDescription: 'Se abilitato, Notice gestirà il tag <title /> del tuo progetto.',
	projectLogo: 'Logo del progetto',
	projectLogoDescription: 'Il logo del tuo progetto può essere visualizzato in diverse parti del tuo progetto.',
	faviconDescription: 'Utilizza il tuo logo come favicon.',
	faviconWarning: (
		<span>
			Devi caricare un <b>Logo del progetto</b> sopra per abilitare questa funzione.
		</span>
	),
	uploadImage: 'Carica immagine',
	configureLogoRedirect: `Configura l'indirizzo verso cui il logo reindirizza`,
	navigationType: `Tipo di navigazione`,
	navigationTypeDescription: `Il parametro di query userà il valore 'page=' nell'URL per gestire la navigazione. Slash userà il classico '/' sottocartella.`,
	stopUserTracking: 'Interrompi il tracciamento degli utenti',
	stopUserTrackingDescription: 'Notice non raccoglierà dati per fornirti statistiche.',
	stopUserTrackingWarning: `<span>La dashboard delle statistiche sarà disabilitata.</span>`,
	headerSpace: `Spazio dell'intestazione`,
	projectTitle: `Titolo del progetto`,
	homeButton: 'Pulsante home',
	topSpace: 'Spazio superiore',
	contactForm: 'Modulo di contatto',
	emailToReceiveMessages: 'Email per ricevere messaggi',
	themeSwitch: 'Cambio tema',
	languageSelector: 'Selettore di lingua',
	breadcrumbNavigation: 'Navigazione breadcrumb',
	timeToRead: 'Tempo di lettura',
	shareToFacebook: 'Condividi su Facebook',
	shareToTwitter: 'Condividi su Twitter',
	shareToLinkedIn: 'Condividi su LinkedIn',
	leftSpace: 'Spazio sinistro',
	navigationMenu: 'Menu di navigazione',
	rightSpace: 'Spazio destro',
	anchorMenu: 'Menu ancoraggio',
	bottomSpace: 'Spazio inferiore',
	bottomNavigation: 'Navigazione inferiore',
	readMoreArticles: 'Leggi altri articoli',
	setProjectTitle: 'Imposta titolo del progetto',
	setProjectTitleDescription: 'Mostrerà il titolo del progetto nello spazio superiore di ogni pagina.',
	navMenuDesc: 'Menu di navigazione a sinistra che offre facile accesso al tuo progetto.',
	searchDescription: `Permetti agli utenti di cercare all'interno del tuo progetto. Avrai anche`,
	analyticsSupport: 'supporto analitico',
	searchDescription2: `da Notice per la ricerca nel tuo progetto.`,
	themeSwitchDescription: `Puoi permettere agli utenti di cambiare il tema del tuo progetto. Puoi configurare il tuo tema`,
	hereInsideColors: `qui all’interno delle opzioni di colore.`,
	languageSwitchDescription: `Puoi permettere agli utenti di cambiare la lingua del tuo progetto. Puoi configurare le tue traduzioni`,
	here: 'qui',
	allowNavDescription: `Permetti agli utenti di navigare tra le pagine usando il menu di navigazione.`,
	displayHomeButtonDescription: `Mostra un pulsante home per permettere agli utenti di navigare alla homepage.`,
	timeToReadDescription: `Mostra il tempo stimato di lettura di una pagina.`,
	facebookShareDescription: `Permetti agli utenti di condividere i tuoi articoli su Facebook.`,
	twitterShareDescription: `Permetti agli utenti di condividere i tuoi articoli su Twitter.`,
	linkedinShareDescription: `Permetti agli utenti di condividere i tuoi articoli su LinkedIn.`,
	nextPrevDescription: `Aggiungi pulsanti per navigare alle pagine successive e precedenti in fondo alla pagina.`,
	anchorRightMenuDescription: `Aggiungi un menu a destra che permette agli utenti di navigare all’interno dei sottotitoli della pagina corrente.`,
	allowRecommendedArticlesDescription: `Permetti agli utenti di leggere altri articoli correlati a quello corrente.`,
	pageTitle: 'Titolo della pagina',
	colors: 'Colori',
	lightBgColor: 'Colore di sfondo chiaro',
	lightFontColor: 'Colore del carattere chiaro',
	lightHighlightColor: 'Colore di evidenziazione chiaro',
	darkBgColor: 'Colore di sfondo scuro',
	darkFontColor: 'Colore del carattere scuro',
	darkHighlightColor: 'Colore di evidenziazione scuro',
	fonts: 'Caratteri',
	fontFamily: 'Famiglia di caratteri',
	fontSize: 'Dimensione carattere',
	spacing: 'Spaziatura',
	blockPadding: 'Padding del blocco',
	maxWidth: 'Larghezza massima',
	maxWidthDescription: `Imposta la larghezza massima per la colonna principale`,
	icons: 'Icone',
	iconStroke: 'Spessore tratto dell’icona',
	headings: 'Intestazioni',
	h1Weight: 'Peso di H1',
	h1Size: 'Dimensione di H1',
	h2Size: 'Dimensione di H2',
	h2Weight: 'Peso di H2',
	h3Size: 'Dimensione di H3',
	h3Weight: 'Peso di H3',
	headingsPadding: 'Padding delle intestazioni',
	titleFontSize: 'Dimensione del font del titolo',
	fontFamilyDescription: (
		<span>
			Per esplorare i caratteri, vai su{' '}
			<a href="https://fonts.google.com/" target="_blank">
				Google Fonts.
			</a>
		</span>
	),
	text: 'Testo',
	textLineHeight: 'Altezza della linea di testo',
	textLetterSpacing: 'Spaziatura delle lettere di testo',
	codeHtmlDesc: `Il codice scritto sarà inserito nel`,
	codeHtmlDesc2: `del tuo progetto Notice.`,
	CSSDesc: `Scrivi del codice CSS per cambiare l'aspetto del tuo progetto`,
	JavascriptDesc: `Scrivi del codice Javascript per cambiare il comportamento del tuo progetto`,
	insightsDesc: `Guida la strategia dei contenuti e migliora il supporto al cliente con dati sul comportamento degli utenti.`,
	publishing: 'Pubblicazione',
	publish: 'Pubblica',
	visitPage: 'Visita la pagina',
	newProject: 'Nuovo progetto',
	createNewProject: 'Crea un nuovo progetto',
	newPage: 'Nuova pagina',
	addNewPage: `Aggiungi una nuova pagina all'interno del progetto corrente`,
	workspaceSettings: 'Impostazioni dell’area di lavoro',
	accountSettings: 'Impostazioni dell’account',
	supportAndCommunity: 'Supporto & Comunità',
	signOut: 'Esci',
	whatIsNew: "Cosa c'è di nuovo",
	inviteCollaborators: 'Invita collaboratori',
	inviteCollaboratorsDescription: `Molte mani rendono il lavoro più leggero. Invita i tuoi colleghi a collaborare insieme ai tuoi progetti.`,
	emailAddress: 'Indirizzo email',
	admin: 'Amministratore',
	editor: 'Editore',
	viewer: 'Visualizzatore',
	owner: 'Proprietario',
	close: 'Chiudi',
	invite: 'Invita',
	translationDescription: 'Traduci il tuo contenuto in più di 100 lingue.',
	selectBlock: 'Puoi selezionare un blocco cliccando',
	selectProjectLanguage: 'Seleziona la lingua predefinita di questo progetto',
	validate: 'Convalida',
	selectLanguageHint: `Suggerimento: questa è la lingua del tuo progetto corrente.`,
	configureTranslation: 'Configura traduzione',
	translationStatus: 'Stato della traduzione',
	selected: 'Selezionato',
	translated: 'Tradotto',
	notTranslated: 'Non tradotto',
	translationOutOfDate: 'Traduzione non aggiornata',
	translateBlock: 'Traduci blocco',
	markAsIncomplete: 'Segna come incompleto',
	markAsComplete: 'Segna come completo',
	markAsCompleteAndGoToNext: 'Segna come completo e vai al successivo',
	anotherNoticeTabIsOpened: "Un'altra scheda di Notice è aperta",
	pleaseReloadToAvoidMismatch: 'Ricarica questa finestra prima di usare per evitare incongruenze.',
	reload: 'Ricarica',
	oopsNoResultsWereFound: 'Oops! Nessun risultato trovato ancora.',
	tryAgainNoResults: 'Prova ancora con un altro periodo.',
	configureYourTranslation: 'Configura la tua traduzione',
	allowUsersToChangeLang: 'Permetti agli utenti di cambiare la lingua del tuo progetto.',
	addsALangQueryLike: 'Aggiunge una query lang come',
	toYourProjectUrl: 'al tuo URL del progetto.',
	addLanguageQueryToUrl: "Aggiungi parametro di query della lingua all'URL",
	chooseADefaultLanguage: 'Scegli una lingua predefinita',
	availableLanguages: 'Lingue disponibili',
	ifYouWantMoreLanguages: 'Se desideri più lingue',
	contactUs: 'Contattaci',
	letUsKnow: 'facci sapere.',
	languageSelectorWarning:
		'Il selettore di lingua può anche essere gestito nel tuo layout dello spazio superiore cliccando',
	clickingHere: 'qui',
	addNew: 'Aggiungi Nuovo',
	translateTo: 'Traduci in',
	translateThisPage: 'Traduci questa pagina',
	stepByStepGuide: 'Guida passo dopo passo',
	manyHandsMakeLightWork: 'Molte mani rendono il lavoro leggero',
	createAndCustomizeContent: 'Crea e personalizza contenuti',
	clickOnPublish: 'Clicca su pubblica',
	deployItAnywhere: 'Distribuiscilo ovunque andando nella scheda Integrazioni',
	inviteColleaguesToCollaborate: 'Invita i colleghi a collaborare ai tuoi progetti.',
	inviteYourTeam: 'Invita il tuo team',
	makeTheMostOfNotice: 'Sfrutta al meglio Notice',
	getInTouchWithUs: 'Mettiti in contatto con noi',
	getInTouchDescription:
		'Hai bisogno di aiuto o hai richieste di funzionalità? Invia un messaggio o unisciti alla nostra community su Slack.',
	accountSettingsDescription: 'Gestisci il tuo profilo, le preferenze e le impostazioni di accesso',
	dashboardLanguage: 'Lingua del cruscotto',
	updateEmail: 'Aggiorna email',
	featureComingSoon: 'Funzionalità in arrivo...',
	signOnWithGoogle: 'Imposta il single sign-on con Google e accedi con un clic',
	yourGoogleAccountHasBeenUnlinked: 'Il tuo account Google è stato scollegato con successo dal tuo account.',
	unlinkAccount: 'Scollega account',
	linkAccount: 'Collega account',
	singleSignOnGithub: 'Imposta il single sign-on con Github e accedi con un clic',
	githubAccountHasBeenUnlinked: 'Il tuo account Github è stato scollegato con successo dal tuo account.',
	signOutDescription: 'Puoi uscire in sicurezza dalle sessioni correnti e scegliere di accedere di nuovo più tardi',
	accountDeletion: 'Eliminazione account',
	accountDeletionDescription: 'Eliminando il tuo account personale, cancelli tutti i dati associati.',
	deleteAccount: 'Elimina account',
	deleteMyAccountSubject: 'Elimina il mio account',
	deleteMyAccountBody: 'Ciao, vorrei eliminare il mio account',
	settings: 'Impostazioni',
	account: 'Account',
	myWorkspaces: 'I miei spazi di lavoro',
	workspace: 'Spazio di lavoro',
	collaborators: 'Collaboratori',
	plans: 'Piani',
	profilePicture: 'Immagine del profilo',
	profilePictureDescription: "Usa un'immagine quadrata con un minimo di 64 pixel",
	fullName: 'Nome completo',
	myWorkspacesDescription: `Visione globale su tutti gli spazi di lavoro a cui ti sei unito`,
	workspaces: 'Spazi di lavoro',
	created: 'Creato',
	manageWorkspaceProfile: 'Gestisci il profilo dello spazio di lavoro',
	workspaceProfile: 'Profilo dello spazio di lavoro',
	workspaceLogo: 'Logo dello spazio di lavoro',
	displayName: 'Nome visualizzato',
	workspaceDeletion: 'Eliminazione dello spazio di lavoro',
	workspaceDeletionDescription: 'Eliminando il tuo spazio di lavoro, cancelli tutti i dati associati.',
	deleteWorkspace: 'Elimina spazio di lavoro',
	storage: 'Memoria',
	storageDescription: `(immagini, video, file, ...)`,
	deleteWorkspaceDescription: 'Sei sicuro di voler eliminare questo spazio di lavoro?',
	deleteWorkspaceWarning: 'Questa azione non può essere annullata.',
	cancel: 'Annulla',
	confirm: 'Conferma',
	visits: 'Visite',
	statistics: 'Statistiche',
	visitsByTimeSpan: 'Visite per intervallo di tempo',
	location: 'Localizzazione',
	locationDescription: 'La localizzazione dei tuoi visitatori',
	device: 'Dispositivo',
	deviceDescription: 'Il dispositivo utilizzato dai tuoi visitatori',
	browser: 'Browser',
	browserDescription: 'Il browser utilizzato dai tuoi visitatori',
	OSdescription: 'Il sistema operativo utilizzato dai tuoi visitatori',
	integration: 'Integrazione',
	hosting: 'Hosting',
	noticeDomain: 'Dominio Notice',
	noticeDomainDescription: 'Cambia il nome del dominio ospitato da Notice.',
	allowedCharacters: 'Caratteri consentiti',
	letters: 'lettere',
	numbers: 'numeri',
	and: 'e',
	domainName: 'Nome del dominio',
	customDomainDescription: 'Aggiungi il tuo dominio personalizzato e collegalo al tuo progetto.',
	customDomain: 'Dominio personalizzato',
	customDomainMissing: `Al momento non hai un dominio personalizzato collegato a questo progetto`,
	customDomainPresent: `Al momento hai un dominio personalizzato collegato a questo progetto`,
	configure: 'Configura',
	whatDomainWouldYouLikeToLink: 'Quale dominio vorresti collegare?',
	hostnameIsInvalid: 'Nome host non valido. Sono consentiti solo i sottodomini.',
	mustOwnSubdomainAndAbilityToEditDNS:
		'Devi possedere il sottodominio e avere la capacità di modificare i suoi record DNS.',
	configureDNS: 'Configura DNS',
	others: 'Altri',
	webflowIntegration: 'Aggiungi blocchi Notice al tuo sito Webflow con un solo clic.',
	wordpressIntegration: 'Aggiungi il plugin Notice per potenziare la tua esperienza su Wordpress.',
	shopifyIntegration: "Offri un'ottima esperienza cliente utilizzando il plugin Notice nel tuo negozio.",
	umsoIntegration: 'Aggiungi blocchi Notice al sito Umso e ottieni informazioni dal tuo pubblico.',
	wixIntegration: `Integrare Notice in Wix è facile. Basta aggiungere un blocco di integrazione e il gioco è fatto!`,
	squarespaceIntegration: `È veloce, come al solito. Aggiungi un blocco di codice e incolla il tuo ID Notice per visualizzare il tuo contenuto.`,
	unicornIntegration: 'Una soluzione rapida per migliorare e personalizzare il tuo sito web con blocchi intelligenti.',
	reactIntegration: 'I blocchi Notice integrati facilmente in React in un solo passaggio.',
	nextIntegration: 'Per gli amanti del framework frontend SSR Next.js, integrazione fluida.',
	vueIntegration: 'Integra Notice nel tuo progetto Vue.js in meno di un minuto.',
	nuxtIntegration: 'Per gli amanti del framework SSR Nuxt, integrazione fluida.',
	linkIntegration: `La soluzione più semplice, basta condividere il link! Non hai nemmeno bisogno di un sito web.`,
	htmlIntegration: `La soluzione ideale per i siti web se non trovi il tuo framework specifico.`,
	iframeIntegration: 'Facili da usare, gli iframe si adattano ovunque, anche nelle applicazioni mobili.',
	rawJSONIntegration: 'Per gli utenti avanzati che vogliono il controllo totale sui loro progetti.',
	qrcodeIntegration: `Il tuo contenuto a portata di mano degli utenti! Condividi il tuo QR code personalizzato :)`,
	integrationsDescription: 'Potenzia la tua visibilità condividendo e integrando Notice ovunque.',
	categories: 'Categorie',
	all: 'Tutti',
	needADifferentIntegrationAndCannotFindItHere: "Hai bisogno di un'integrazione diversa e non la trovi qui?",
	shareables: 'Condivisibili',
	useTemplates: 'Usa Modelli',
	useAIGeneration: 'Usa Generazione AI',
	selectProjectTip: 'Puoi alternare tra generazione AI e modelli',
	preFilledTemplate: 'Modello Precompilato',
	helpCenter: 'Centro Assistenza',
	termsOfuse: 'Termini di Uso',
	privacyPolicy: 'Politica sulla Privacy',
	jobBoard: 'Bacheca di Lavoro',
	getStarted: 'Tutorial',
	changelog: 'Registro delle Modifiche',
	missionAndValues: 'Missione e Valori',
	investorsReport: 'Rapporto agli Investitori',
	startFromScratch: 'Inizia da Zero',
	helpOurAIGenerateYour: 'Aiuta la nostra IA a generare il tuo',
	provideYourWebsiteURL: `Fornisci l'URL del tuo sito web esistente`,
	weFoundAWebsite: `Abbiamo trovato un sito web collegato al tuo indirizzo email`,
	makeSureProvidedWebsiteAlreadyExists: `Assicurati che il sito web fornito esista già`,
	AIExplanation: `La nostra IA esamina il sito web fornito e genera un`,
	basedOnTheWebsiteInformation: `basato sulle informazioni del sito web.`,
	youCanUseAnyExistingURL: `Puoi usare qualsiasi URL esistente.`,
	enhanceYourGeneration: `Puoi migliorare la tua generazione aggiungendo ulteriori istruzioni`,
	giveInstructions: `Dai istruzioni per generare il tuo`,
	makeSureThisPromptIsMatching: `Assicurati che questo prompt corrisponda al tipo di progetto selezionato`,
	writeItInFrenchOnlyUsePastTense: `Esempio: Scrivilo in francese, usa solo il passato`,
	backToList: `Torna alla lista`,
	pricingDescription: 'Il nostro listino prezzi è chiaro e allineato ai tuoi obiettivi commerciali.',
	monthlyTokenAmount: 'Quantità di token mensili',
	billingPeriod: 'Periodo di fatturazione',
	monthly: 'Mensile',
	yearly: 'Annuale',
	oneMonthFree: '1 mese gratis',
	customizeYourNewContentsHome: 'Personalizza la home dei tuoi nuovi contenuti',
	manageSmartContentForYourCompany: 'Gestisci contenuti intelligenti per la tua azienda',
	activateContentSynergiesForYourTeam: 'Attiva sinergie di contenuto per il tuo team',
	forThoseNeedingAnEnterpriseGradeSolution: 'Per chi necessita di una soluzione di livello aziendale',
	letsTalk: 'Parliamone',
	numberOfCollaborators: 'Numero di collaboratori',
	numberOfWorkspaces: 'Numero di spazi di lavoro',
	integrateAnywhere: 'Integra ovunque',
	removeNoticeBranding: 'Rimuovi il branding Notice',
	aiAssistant: 'Assistente AI',
	customSupportAndHelp: 'Supporto e aiuto personalizzati',
	premiumCdn: 'CDN Premium',
	ssoEnabled: 'SSO abilitato',
	onPremiseData: 'Dati on-premise',
	contentAndSeoAudit: 'Audit dei contenuti e SEO',
	downgrade: 'Downgrade',
	newWorkspace: 'Nuovo spazio di lavoro',
	createANewWorkspace: 'Crea un nuovo spazio di lavoro',
	enterNameOfNewWorkspace: 'Inserisci il nome del nuovo spazio di lavoro',
	create: 'Crea',
	signIn: 'Accedi',
	signInDescription: 'Accedi rapidamente utilizzando uno dei tuoi account social, o usa la tua email di lavoro.',
	signUp: 'Registrati',
	continueWithGoogle: 'Continua con Google',
	continueWithGithub: 'Continua con Github',
	orSignInUsingWorkEmail: 'O accedi utilizzando la tua email di lavoro',
	enterWorkEmail: 'Inserisci la tua email di lavoro',
	enterTemporaryCode: 'Inserisci il codice temporaneo',
	weJustSentYouATemporaryLoginCode: 'Ti abbiamo appena inviato un codice di accesso temporaneo.',
	pleaseCheckYourInbox: 'Controlla la tua posta in arrivo.',
	alreadyHaveAnAccountSignIn: 'Hai già un account? Accedi',
	continueWithLoginCode: 'Continua con il codice di accesso',
	continueWithEmail: 'Continua con email',
	selectYourProject: 'Seleziona il tuo progetto',
	chooseYourIntegration: 'Scegli la tua integrazione',
	publishingYourProject: 'Pubblicazione del tuo progetto',
	projectCreated:
		'Il tuo progetto Notice è stato creato! Aggiungi questo nuovo progetto al tuo sito web utilizzando una delle nostre integrazioni o direttamente tramite il link pre-generato per te.',
	signInMethods: 'Metodi di accesso',
	signInMethodsDescription: `Aggiorna l'email utilizzata per accedere al tuo account`,
	joinOurSlackCommunityForUpdatesAndFeedback: `Unisciti alla nostra community Slack per aggiornamenti e feedback, e connettiti con noi sui social.`,
	joinSlack: 'Unisciti a Slack',
	joinTheAcademy: 'Unisciti all’Academia',
	readOurDoc: 'Leggi la nostra documentazione',
	checkOurTutorials: 'Guarda i nostri tutorial',
	sendUsAnEmail: `Invia un'email`,
	pleaseEnterYourFirstName: 'Per favore, inserisci il tuo nome.',
	pleaseEnterYourLastName: 'Per favore, inserisci il tuo cognome.',
	firstname: 'Nome',
	lastname: 'Cognome',
	pleasEnterAValidPhoneNumber: 'Per favore, inserisci un numero di telefono valido.',
	phoneNumber: 'Numero di telefono',
	pleaseEnterYourCompanyName: 'Per favore, inserisci il nome della tua azienda.',
	companyName: "Nome dell'azienda",
	pleaseChooseYourCompanySize: 'Per favore, scegli la dimensione della tua azienda.',
	companySize: "Dimensione dell'azienda",
	pleaseChooseYourRoleInTheCompany: 'Per favore, scegli il tuo ruolo in azienda.',
	companyRole: 'Ruolo in azienda',
	startCreating: 'Inizia a creare !',
	welcomeToNotice: 'Benvenuto in Notice !',
	pleaseHelpUsWithForm: 'Per favore, aiutaci nel processo di fornirti la completa esperienza di Notice.',
	preview: 'Anteprima',
	rename: 'Rinomina',
	duplicate: 'Duplica',
	exportMarkdown: 'Esporta Markdown',
	delete: 'Elimina',
	exportJSON: 'Esporta JSON',
	type: 'Tipo',
	forCommands: 'per i comandi',
	basicBlocks: 'Blocchi di base',
	paragraph: 'Paragrafo',
	justWriteDownSomeText: 'Scrivi semplicemente del testo',
	heading: 'Intestazione',
	bigSectionHeading: 'Intestazione di sezione grande',
	mediumSectionHeading: 'Intestazione di sezione media',
	smallSectionHeading: 'Intestazione di sezione piccola',
	bulletedList: 'Elenco puntato',
	organizeContentWithBullets: 'Organizza il contenuto con punti elenco',
	numberedList: 'Elenco numerato',
	createANumberedList: 'Crea un elenco numerato',
	captureACodeSnippet: 'Cattura uno snippet di codice',
	hint: 'Suggerimento',
	provideHelpfulInformation: 'Fornisci informazioni utili',
	quote: 'Citazione',
	highlightASpecificPassageOfText: 'Evidenzia un passaggio specifico del testo',
	divider: 'Divisore',
	separateDifferentBlocks: 'Separa blocchi diversi',
	toDo: 'Da fare',
	keepTrackOfTasksOrItems: 'Tieni traccia di compiti o elementi',
	media: 'Media',
	image: 'Immagine',
	uploadAnImageFile: 'Carica un file di immagine',
	document: 'Documento',
	uploadADocument: 'Carica un documento',
	video: 'Video',
	addAVideo: 'Aggiungi un video',
	advancedBlocks: 'Blocchi avanzati',
	table: 'Tabella',
	organizeWithRowsAndColumns: 'Organizza con righe e colonne',
	expandable: 'Espandibile',
	addACollapsableBlock: 'Aggiungi un blocco collassabile',
	textAIGeneration: 'Generazione di testo AI',
	letOurRobotCreateYourImages: 'Lascia che il nostro robot crei le tue immagini',
	javascript: 'Javascript',
	embedJavascript: 'Incorpora Javascript',
	youtube: 'Youtube',
	embedYoutubeVideos: 'Incorpora video di Youtube',
	justCopyPasteTheLinkOfYourVideo:
		'Basta copiare e incollare il link del tuo video in un paragrafo vuoto per incorporare automaticamente un video di Youtube. Esempio di link: https://www.youtube.com/watch?v=m4fDm4rdUdk',
	embedLoomVideos: 'Incorpora video di Loom',
	justCopyPasteLoomVideo:
		'Basta copiare e incollare il link del tuo video in un paragrafo vuoto per incorporare automaticamente un video di Loom. Esempio di link: https://www.loom.com/share/36656bc4afb84de2bb829183f46a1b40',
	embedVimeos: 'Incorpora Vimeo',
	embedVimeosInstructions:
		'Basta copiare e incollare il link del tuo video in un paragrafo vuoto per incorporare automaticamente un video di Vimeo. Esempio di link: https://vimeo.com/251147627',
	embedAirtableInstructions:
		'Incolla il link della tua vista tabella in un paragrafo vuoto per incorporare automaticamente un AirTable. Esempio di link: https://airtable.com/appeh8s8bwMI7JjlW/shro43JbOcXFQH0tQ/tblnrBMRpvfrcqkko',
	AIIsWriting: "L'IA sta scrivendo...",
	Keep: 'Mantenere',
	Retry: 'Riprova',
	DescribeWhatYouWantAI: 'Descrivi cosa vuoi creare alla nostra IA',
	LetOurAICreate: 'Lascia che la nostra IA crei la tua pagina',
	LetOurAICreateImage: "Crea un'immagine ispirata a questa pagina",
	freeTrialEndsIn: 'La prova gratuita terminerà tra X giorni.',
	AIIsGeneratingAnImageIdea: "L'IA sta generando un'idea di immagine...",
	AIIsGeneratingImage: "L'IA sta generando un'immagine...",
	GenImagePlaceholder: 'Un campo di girasoli alla fine della giornata. Nello stile dei dipinti di Van Gogh.',
	metadata: 'Metadati',
	pageMetadata: 'Metadati della pagina',
	giveInformationForSEO: 'Arricchisci questa pagina con informazioni per migliorare il SEO e le anteprime',
	author: 'Autore',
	editMyName: 'Modifica il mio nome',
	tags: 'Tag',
	datePublished: 'Data di pubblicazione',
	addATag: 'Aggiungi un tag',
	advancedOptions: 'Opzioni Avanzate',
	tellGoogleExists: "Informa Google dell'esistenza del tuo progetto",
	tellGoogleExistsDescription: 'Per indicizzare correttamente il tuo progetto, devi verificare il tuo sito web su ',
	clickHereToFollowOurGuide: 'Clicca qui per seguire la nostra guida',
	explanationDateOfPublication: 'Impostando una data futura, la pagina verrà nascosta fino alla data scelta.',
	articleHiddenDateFuture: 'Questo articolo è nascosto perché la data è nel futuro.',
	blockMenuChangeImageCover: 'Cambia copertina immagine',
	blockMenuAddImageCover: 'Aggiungi copertina immagine',
	blockMenuDuplicate: 'Duplica',
	blockMenuDelete: 'Elimina',
	blockMenuOnlyText: 'Solo testo',
	blockMenuWithImage: 'Con immagine',
	blockMenuPageSummary: 'Sommario della pagina',
	blockMenuBorder: 'Bordo',
	blockMenuLayout: 'Layout',
	blockMenuDisplay: 'Visualizzazione',
	blockMenuStyle: 'Stile',
	subPageUpgradeSucessTitle: 'Aggiornamento Riuscito',
	subPageUpgradeSuccessMsg:
		'Congratulazioni! 🎉 Il tuo account è stato aggiornato con successo. Grazie per aver scelto Notice per migliorare la tua esperienza!',
	subPageGoBack: 'Torna alla modifica',
	deleteProjectDeleteProject: 'Elimina progetto',
	deleteProjectAreYouSure: 'Sei sicuro di voler eliminare questo progetto?',
	deleteWarning: 'Questa azione non può essere annullata.',
	cancelButton: 'Annulla',
	confirmButton: 'Conferma',
	deletePageDeletePage: 'Elimina Pagina',
	deletePageAreYouSure:
		'Questa azione eliminerà permanentemente questa pagina e tutto il suo contenuto correlato, sei sicuro di voler continuare?',
	pasteLinkHere: 'Incolla link qui',
	addLink: 'Aggiungi link',
	removeLink: 'Rimuovi link',
	selectAnImage: "Seleziona un'immagine",
	selectADocument: 'Seleziona un documento',
	selectAVideo: 'Seleziona un video',
	selectAnAudio: 'Seleziona un audio',
	dropYourFileHere: "Rilascia il tuo file qui per iniziare l'upload o",
	anyDocTypeAccepted: 'Qualsiasi tipo di documento è accettato',
	acceptedTypes: 'Tipi accettati',
	browseFiles: 'Sfoglia i file',
	filterFiles: 'Filtra i file',
	files: 'File',
	enterAnURL: 'Inserisci un URL',
}
