export const ja = {
	customization: 'カスタマイズ',
	translation: '翻訳',
	integrations: '統合',
	insights: 'インサイト',
	FreePlan: '無料プラン',
	upgrade: 'アップグレード',
	yourProfile: 'あなたのプロフィール',
	general: '一般',
	layout: 'レイアウト',
	theme: 'テーマ',
	advanced: '高度な',
	styling: 'スタイリング',
	code: 'コード',
	billing: '課金',
	aiSettings: 'AI設定',
	aiSettingsDescription: 'AI設定へようこそ、ここではAIがこのワークスペースのコンテンツを生成する方法を制御します',
	aiSettingSection1: 'あなたは何をしますか？',
	aiSettingSection1Description:
		'あなたの仕事や会社の焦点を理解するのに役立ちます。あなたのビジネスや職業について簡単な説明を提供してください。',
	aiSettingSection1Placeholder:
		'デジタルマーケティング戦略とコンテンツ作成に特化したクリエイティブエージェンシーを運営しています',
	aiSettingSection2: 'あなたのトーンは何ですか？',
	aiSettingSection2Description:
		'ワークスペースのテキストに求めるトーンを定義してください。あなたのコミュニケーションスタイルに合ったトーンを共有してください。',
	aiSettingSection2Placeholder:
		'私たちはプロフェッショナルでありながらもフレンドリーに聞こえ、つながりやすい方法で専門知識を共有します',
	aiSettingSection3: 'あなたの好みのライティングスタイルの一部',
	aiSettingSection3Description:
		'あなたのライティングスタイルや、お気に入りの文章の一部の例を1つまたは2つ提供してください。私たちのAIはそれに適応し、同じスタイルのテキストを提供します。',

	aiSettingSection3Placeholder: `春はあけぼの。やうやう白くなりゆく山ぎは　少し明かりて、紫だちたる雲の細くたなびきたる。`,
	aiSettingsModelSettings: 'AIモデル設定',
	aiSettingModelSection: 'AIモデルの選択',
	aiSettingModelSectionDescription: '好みに最も適したAI生成モデルを選択します。',
	aiSettingGPT4Tooltip: 'より最適化されています',
	aiSettingGPT3Tooltip: 'より高速です',
	edit: '編集',
	save: '保存',
	skip: 'スキップ',
	changeAISettings: 'AI設定を変更',
	billingDetailsAndInvoices: '課金の詳細と請求書',
	PleaseClickToEditTheSettings: '設定を編集するにはクリックしてください',
	overview: '概要',
	currentPlan: '現在のプラン',
	nextBillingOn: '次回の課金日',
	nextBillingAmount: '次回の課金額',
	numberOfProjects: 'プロジェクト数',
	reachesSubscriptionPage: 'サブスクリプションページに到達',
	billingPageUpgradeButton: '課金ページのアップグレードボタン',
	upgradeYourPlan: 'プランをアップグレードする',
	billingInfoAndPayment: '課金情報と支払い',
	manageAllYourBilling: 'すべての課金情報と支払い方法をここで管理する',
	manageBillingDetails: '課金の詳細を管理する',
	invoicesHistory: '請求書の履歴',
	invoiceID: '請求書ID',
	date: '日付',
	total: '合計',
	status: 'ステータス',
	invoiceReceipt: '請求書/領収書',
	download: 'ダウンロード',
	noInfoAvailableYet: 'まだ情報はありません',
	hideBranding: 'ブランディングを隠す',
	hideBrandingDescription: 'プロジェクトにNoticeブランディングを表示しない。',
	handleTitleTagTitle: '<title />タグを扱う',
	titleTagDescription: '有効にすると、Noticeがプロジェクトの<title />タグを扱う。',
	projectLogo: 'プロジェクトのロゴ',
	projectLogoDescription: 'プロジェクトのロゴはプロジェクトのさまざまな場所に表示できる。',
	faviconDescription: 'ロゴをファビコンとして使用する。',
	faviconWarning: (
		<span>
			この機能を有効にするには、上の<b>プロジェクトのロゴ</b>をアップロードする必要があります。
		</span>
	),
	uploadImage: '画像をアップロード',
	configureLogoRedirect: 'ロゴがリダイレクトするアドレスを設定する',
	navigationType: 'ナビゲーションの種類',
	navigationTypeDescription: `'page='の値をURLで使用してナビゲーションを扱う。スラッシュは通常の'/'サブフォルダを使用する。`,
	stopUserTracking: 'ユーザー追跡を停止',
	stopUserTrackingDescription: '統計情報を提供するためのデータ収集をNoticeが行わない。',
	stopUserTrackingWarning: <span>統計ダッシュボードが無効になります。</span>,
	headerSpace: 'ヘッダーのスペース',
	projectTitle: 'プロジェクトのタイトル',
	homeButton: 'ホームボタン',
	topSpace: '上のスペース',
	contactForm: 'お問い合わせフォーム',
	emailToReceiveMessages: 'メッセージを受信するメールアドレス',
	themeSwitch: 'テーマスイッチ',
	languageSelector: '言語セレクター',
	breadcrumbNavigation: 'パンくずリストナビゲーション',
	timeToRead: '読むのにかかる時間',
	shareToFacebook: 'Facebookで共有',
	shareToTwitter: 'Twitterで共有',
	shareToLinkedIn: 'LinkedInで共有',
	leftSpace: '左のスペース',
	navigationMenu: 'ナビゲーションメニュー',
	rightSpace: '右のスペース',
	anchorMenu: 'アンカーメニュー',
	bottomSpace: '下のスペース',
	bottomNavigation: '下のナビゲーション',
	readMoreArticles: '他の記事を読む',
	setProjectTitle: 'プロジェクトのタイトルを設定',
	setProjectTitleDescription: '各ページの上部にプロジェクトのタイトルを表示します。',
	navMenuDesc: 'プロジェクトに簡単にアクセスできる左側のナビゲーションメニュー。',
	searchDescription: 'プロジェクト内でユーザーが検索できるようにする。また、Noticeの',
	analyticsSupport: '分析サポート',
	searchDescription2: 'もプロジェクトの検索のために提供される。',
	themeSwitchDescription: 'ユーザーにプロジェクトのテーマを変更することを許可する。テーマは',
	hereInsideColors: 'こちらの色の中で設定する。',
	languageSwitchDescription: 'ユーザーにプロジェクトの言語を変更することを許可できます。翻訳の設定はこちらで行えます。',
	here: 'こちら',
	allowNavDescription: 'ナビゲーションメニューを使用してページ間を移動することを許可できます。',
	displayHomeButtonDescription: 'ユーザーがホームページに移動できるようにホームボタンを表示します。',
	timeToReadDescription: 'ページの読むのにかかる見込み時間を表示します。',
	facebookShareDescription: 'ユーザーが記事をFacebookで共有できるようにします。',
	twitterShareDescription: 'ユーザーが記事をTwitterで共有できるようにします。',
	linkedinShareDescription: 'ユーザーが記事をLinkedInで共有できるようにします。',
	nextPrevDescription: 'ページの底部に次へおよび前へのボタンを追加します。',
	anchorRightMenuDescription: '現在のページのサブタイトル内をナビゲートできるメニューを右側に追加します。',
	allowRecommendedArticlesDescription: '関連する記事を表示し、ユーザーに読むことを許可できます。',
	pageTitle: 'ページタイトル',
	colors: 'カラー',
	lightBgColor: 'ライトバックグラウンドカラー',
	lightFontColor: 'ライトフォントカラー',
	lightHighlightColor: 'ライトハイライトカラー',
	darkBgColor: 'ダークバックグラウンドカラー',
	darkFontColor: 'ダークフォントカラー',
	darkHighlightColor: 'ダークハイライトカラー',
	fonts: 'フォント',
	fontFamily: 'フォントファミリー',
	fontSize: 'フォントサイズ',
	spacing: 'スペーシング',
	blockPadding: 'ブロックパディング',
	maxWidth: '最大幅',
	maxWidthDescription: 'メインカラムの最大幅を設定します。',
	icons: 'アイコン',
	iconStroke: 'アイコンストローク幅',
	headings: '見出し',
	h1Weight: 'H1のウェイト',
	h1Size: 'H1のサイズ',
	h2Size: 'H2のサイズ',
	h2Weight: 'H2のウェイト',
	h3Size: 'H3のサイズ',
	h3Weight: 'H3のウェイト',
	headingsPadding: '見出しのパディング',
	titleFontSize: 'タイトルのフォントサイズ',
	fontFamilyDescription: (
		<span>
			フォントを探索するには、
			<a href="https://fonts.google.com/" target="_blank">
				Google Fonts
			</a>
			にアクセスしてください。
		</span>
	),
	text: 'テキスト',
	textLineHeight: 'テキスト行の高さ',
	textLetterSpacing: 'テキスト文字間隔',
	codeHtmlDesc: '書かれたコードは、Noticeプロジェクトの',
	codeHtmlDesc2: 'に挿入されます。',
	CSSDesc: 'プロジェクトの外観を変更するためのCSSコードを記述します',
	JavascriptDesc: 'プロジェクトの動作を変更するためのJavascriptコードを記述します',
	insightsDesc: 'ユーザーの行動に関するデータを活用してコンテンツ戦略を進化させ、カスタマーサポートを向上させます。',
	publishing: '公開',
	publish: '公開',
	visitPage: 'ページを訪れる',
	newProject: '新しいプロジェクト',
	createNewProject: '新しいプロジェクトを作成',
	newPage: '新しいページ',
	addNewPage: '現在のプロジェクトに新しいページを追加',
	workspaceSettings: 'ワークスペース設定',
	accountSettings: 'アカウント設定',
	supportAndCommunity: 'サポート＆コミュニティ',
	signOut: 'サインアウト',
	whatIsNew: '新着情報',
	inviteCollaborators: '共同作業者を招待',
	inviteCollaboratorsDescription: '多くの手がかりは作業を軽くします。同僚をプロジェクトで協力させましょう。',
	emailAddress: 'メールアドレス',
	admin: '管理者',
	editor: 'エディター',
	viewer: 'ビューアー',
	owner: 'オーナー',
	close: '閉じる',
	invite: '招待',
	translationDescription: '100以上の言語でコンテンツを翻訳します。',
	selectBlock: 'ブロックを選択できます',
	selectProjectLanguage: 'このプロジェクトのデフォルト言語を選択',
	validate: '検証',
	selectLanguageHint: 'ヒント：これは現在のプロジェクトの言語です。',
	configureTranslation: '翻訳を設定',
	translationStatus: '翻訳ステータス',
	selected: '選択済み',
	translated: '翻訳済み',
	notTranslated: '未翻訳',
	translationOutOfDate: '翻訳が古い',
	addsALangQueryLike: '言語クエリのようなものを追加します',
	toYourProjectUrl: 'プロジェクトのURLに',
	translateBlock: 'ブロックを翻訳',
	markAsIncomplete: '不完全としてマーク',
	markAsComplete: '完了としてマーク',
	markAsCompleteAndGoToNext: '完了としてマークして次に進む',
	anotherNoticeTabIsOpened: '別のNoticeタブが開かれています',
	pleaseReloadToAvoidMismatch: '別のNoticeタブが開かれています',
	reload: '再読み込み',
	oopsNoResultsWereFound: 'おっと、まだ結果が見つかりませんでした。',
	tryAgainNoResults: '別の期間で再試行してみてください。',
	configureYourTranslation: '翻訳を設定',
	allowUsersToChangeLang: 'ユーザーにプロジェクトの言語を変更することを許可します。',
	addLanguageQueryToUrl: 'URLに言語クエリパラメータを追加',
	chooseADefaultLanguage: 'デフォルトの言語を選択',
	availableLanguages: '利用可能な言語',
	ifYouWantMoreLanguages: 'さらに多くの言語が必要な場合は、',
	contactUs: 'お問い合わせください',
	letUsKnow: '私にお知らせください。',
	languageSelectorWarning: '言語セレクターはトップスペースのレイアウトで管理することもできます。',
	clickingHere: 'ここをクリック',
	addNew: '新しい追加',
	translateTo: '翻訳先',
	translateThisPage: 'このページを翻訳',
	stepByStepGuide: 'ステップバイステップガイド',
	manyHandsMakeLightWork: '協力すれば重荷も軽くなる',
	createAndCustomizeContent: 'コンテンツを作成しカスタマイズする',
	clickOnPublish: '公開をクリック',
	deployItAnywhere: '統合タブに移動してどこにでもデプロイ',
	inviteColleaguesToCollaborate: '同僚を共同作業に招待',
	inviteYourTeam: 'チームを招待',
	makeTheMostOfNotice: 'Noticeを最大限に活用',
	getInTouchWithUs: 'お問い合わせ',
	getInTouchDescription:
		'助けが必要な場合、または機能のリクエストがある場合は、メッセージを送信するか、Slackコミュニティに参加してください。',
	accountSettingsDescription: 'プロフィール、設定、ログイン設定を管理します',
	dashboardLanguage: 'ダッシュボード言語',
	updateEmail: 'メールアドレスを更新',
	featureComingSoon: '近日公開予定...',
	signOnWithGoogle: 'Googleとのシングルサインオンを設定して、ワンクリックでログイン',
	yourGoogleAccountHasBeenUnlinked: 'Googleアカウントが正常にアカウントから切断されました。',
	unlinkAccount: 'アカウントのリンク解除',
	linkAccount: 'アカウントをリンク',
	singleSignOnGithub: 'Githubとのシングルサインオンを設定して、ワンクリックでログイン',
	githubAccountHasBeenUnlinked: 'Githubアカウントが正常にアカウントから切断されました。',
	signOutDescription: '現在のセッションから安全にサインアウトし、後でサインインすることを選択できます',
	accountDeletion: 'アカウントの削除',
	accountDeletionDescription: '個人アカウントを削除すると、関連するすべてのデータが削除されます。',
	deleteAccount: 'アカウントを削除',
	deleteMyAccountSubject: 'アカウントを削除',
	deleteMyAccountBody: 'こんにちは、アカウントを削除したいです',
	settings: '設定',
	account: 'アカウント',
	myWorkspaces: '私のワークスペース',
	workspace: 'ワークスペース',
	collaborators: '共同作業者',
	plans: 'プラン',
	profilePicture: 'プロフィール写真',
	profilePictureDescription: '最小サイズ64ピクセルの正方形の画像を使用します',
	fullName: 'フルネーム',
	myWorkspacesDescription: '参加したすべてのワークスペースを総合的に確認',
	workspaces: 'ワークスペース',
	created: '作成',
	manageWorkspaceProfile: 'ワークスペースプロフィールを管理',
	workspaceProfile: 'ワークスペースプロフィール',
	workspaceLogo: 'ワークスペースロゴ',
	displayName: '表示名',
	workspaceDeletion: 'ワークスペースの削除',
	workspaceDeletionDescription: 'ワークスペースを削除すると、関連するすべてのデータが削除されます。',
	deleteWorkspace: 'ワークスペースを削除',
	storage: 'ストレージ',
	storageDescription: '（画像、動画、ファイルなど）',
	deleteWorkspaceDescription: 'このワークスペースを削除してもよろしいですか？',
	deleteWorkspaceWarning: 'この操作は元に戻せません。',
	cancel: 'キャンセル',
	confirm: '確認',
	visits: '訪問数',
	statistics: '統計',
	visitsByTimeSpan: '時間帯別の訪問数',
	location: '場所',
	locationDescription: '訪問者の場所',
	device: 'デバイス',
	deviceDescription: '訪問者が使用したデバイス',
	browser: 'ブラウザ',
	OSdescription: '訪問者が使用したオペレーティングシステム',
	integration: '統合',
	hosting: 'ホスティング',
	noticeDomain: 'Noticeドメイン',
	noticeDomainDescription: 'Noticeホストドメインの名前を変更します。',
	allowedCharacters: '許可されている文字',
	letters: '文字',
	numbers: '数字',
	and: 'および',
	domainName: 'ドメイン名',
	customDomainDescription: '独自のカスタムドメインを追加し、プロジェクトにリンクします。',
	customDomain: 'カスタムドメイン',
	customDomainMissing: 'このプロジェクトには現在、カスタムドメインへのリンクがありません。',
	customDomainPresent: 'このプロジェクトには現在、カスタムドメインへのリンクがあります。',
	configure: '設定',
	whatDomainWouldYouLikeToLink: 'どのドメインにリンクしたいですか？',
	hostnameIsInvalid: 'ホスト名が無効です。サブドメインのみが許可されています。',
	mustOwnSubdomainAndAbilityToEditDNS: 'サブドメインを所有し、DNSレコードを編集できる必要があります。',
	configureDNS: 'DNSを設定',
	others: 'その他',
	webflowIntegration: 'WebflowウェブサイトにNoticeブロックを1クリックで追加します。',
	wordpressIntegration: 'Wordpressでの利用を強化するためにNoticeプラグインを追加します。',
	shopifyIntegration: 'ストアでNoticeプラグインを使用して優れた顧客体験を提供します。',
	umsoIntegration: 'UmsoウェブサイトにNoticeブロックを追加し、観客からのインサイトを取得します。',
	wixIntegration: 'WixにNoticeを統合するのは簡単です。 統合ブロックを追加するだけです。',
	squarespaceIntegration:
		'迅速で、いつも通りです。コードブロックを追加し、コンテンツを表示するためにNotice IDを貼り付けます。',
	unicornIntegration: 'スマートブロックを使用してウェブサイトを改善およびパーソナライズするためのクイックウィン。',
	reactIntegration: 'NoticeブロックをReactに簡単に統合できます。わずか1ステップ。',
	nextIntegration: 'Next.js SSRフロントエンドフレームワークの愛用者向けに、スムーズな統合。',
	vueIntegration: 'Vue.jsプロジェクト内にNoticeを統合するのは1分以内。',
	nuxtIntegration: 'Nuxt SSRフロントエンドフレームワークの愛用者向けに、スムーズな統合。',
	linkIntegration: '最も簡単なソリューション、リンクを共有するだけです！ ウェブサイトすら必要ありません。',
	htmlIntegration: '特定のフレームワークが見つからない場合のウェブサイトのデフォルトソリューション。',
	iframeIntegration: 'どこでも適合するiframes、モバイルアプリケーションにも適合します。',
	rawJSONIntegration: 'プロジェクト全体を制御するための高度なユーザー向け。',
	qrcodeIntegration: 'ユーザーの指先にコンテンツを提供します！ 独自のQRコードを共有します：）',
	integrationsDescription: 'Noticeを共有し、どこにでも統合して可視性を向上させます。',
	categories: 'カテゴリー',
	all: 'すべて',
	needADifferentIntegrationAndCannotFindItHere: '異なる統合が必要で、ここで見つからない場合は？',
	shareables: '共有可能',
	useTemplates: 'テンプレートを使用',
	useAIGeneration: 'AIジェネレーションを使用',
	selectProjectTip: 'AIジェネレーションとテンプレートを切り替えることができます',
	preFilledTemplate: '事前に埋められたテンプレート',
	helpCenter: 'ヘルプセンター',
	termsOfuse: '利用規約',
	privacyPolicy: 'プライバシーポリシー',
	jobBoard: '求人情報',
	getStarted: 'チュートリアル',
	changelog: '変更履歴',
	missionAndValues: 'ミッション＆バリュー',
	investorsReport: '投資家レポート',
	startFromScratch: 'ゼロから始める',
	helpOurAIGenerateYour: 'AIにあなたの生成を手伝ってもらう',
	provideYourWebsiteURL: '既存のウェブサイトのURLを提供',
	weFoundAWebsite: 'あなたのメールアドレスにリンクされたウェブサイトが見つかりました',
	makeSureProvidedWebsiteAlreadyExists: '提供されたウェブサイトが既に存在することを確認してください',
	AIExplanation: 'AIは提供されたウェブサイトを調査し、カスタム生成を生成します',
	basedOnTheWebsiteInformation: 'ウェブサイト情報に基づいて',
	youCanUseAnyExistingURL: '既存のURLを使用できます',
	enhanceYourGeneration: '生成を向上させることができます',
	giveInstructions: '指示を提供して生成',
	browserDescription: '訪問者が使用されたブラウザ',
	makeSureThisPromptIsMatching: 'このプロジェクトタイプと一致していることを確認してください',
	writeItInFrenchOnlyUsePastTense: '例: フランス語で書いてください、過去形のみを使用してください',
	backToList: 'リストに戻る',
	pricingDescription: '私たちの価格設定はシンプルで、ビジネス目標に合わせています。',
	monthlyTokenAmount: '月間トークン数',
	billingPeriod: '請求期間',
	monthly: '月次',
	yearly: '年次',
	oneMonthFree: '1か月無料',
	customizeYourNewContentsHome: '新しいコンテンツのホームをカスタマイズ',
	manageSmartContentForYourCompany: '会社のスマートコンテンツを管理',
	activateContentSynergiesForYourTeam: 'チームのコンテンツ連携を活性化',
	forThoseNeedingAnEnterpriseGradeSolution: '企業向けのエンタープライズグレードのソリューションが必要な方に',
	letsTalk: 'お話ししましょう',
	numberOfCollaborators: '協力者の数',
	numberOfWorkspaces: 'ワークスペースの数',
	integrateAnywhere: 'どこでも統合',
	removeNoticeBranding: 'Noticeブランドを削除',
	aiAssistant: 'AIアシスタント',
	customSupportAndHelp: 'カスタムサポートとヘルプ',
	premiumCdn: 'プレミアムCDN',
	ssoEnabled: 'SSO有効',
	onPremiseData: 'オンプレミスデータ',
	contentAndSeoAudit: 'コンテンツとSEO監査',
	downgrade: 'ダウングレード',
	newWorkspace: '新しいワークスペース',
	createANewWorkspace: '新しいワークスペースを作成',
	enterNameOfNewWorkspace: '新しいワークスペースの名前を入力してください',
	create: '作成',
	signIn: 'サインイン',
	signInDescription:
		'ソーシャルアカウントのいずれかを使用してサインインするか、職場のメールアドレスを使用してサインインします。',
	signUp: 'サインアップ',
	continueWithGoogle: 'Googleで続行',
	continueWithGithub: 'Githubで続行',
	orSignInUsingWorkEmail: 'または職場のメールアドレスを使用してサインイン',
	enterWorkEmail: '職場のメールアドレスを入力',
	enterTemporaryCode: '一時コードを入力',
	weJustSentYouATemporaryLoginCode: '一時的なログインコードを送信しました。',
	pleaseCheckYourInbox: '受信トレイを確認してください。',
	alreadyHaveAnAccountSignIn: 'すでにアカウントをお持ちですか？ サインイン',
	continueWithLoginCode: 'ログインコードで続行',
	continueWithEmail: 'メールで続行',
	selectYourProject: 'プロジェクトを選択',
	chooseYourIntegration: 'あなたの統合を選択してください',
	publishingYourProject: 'プロジェクトの公開',
	projectCreated:
		'あなたのNoticeプロジェクトが作成されました！私たちの統合の一つを使用して、または直接生成されたリンクを通じて、この新しいプロジェクトをあなたのウェブサイトに追加してください。',
	signInMethods: 'サインイン方法',
	signInMethodsDescription: 'アカウントにログインするために使用するメールを更新します',
	joinOurSlackCommunityForUpdatesAndFeedback:
		'アップデートとフィードバックのために当社のSlackコミュニティに参加し、ソーシャルメディアで当社と連絡を取りましょう。',
	joinSlack: 'Slackに参加',
	joinTheAcademy: 'アカデミーに参加',
	readOurDoc: 'ドキュメントを読む',
	checkOurTutorials: 'チュートリアルをチェック',
	sendUsAnEmail: 'メールを送信',
	pleaseEnterYourFirstName: '名を入力してください。',
	pleaseEnterYourLastName: '姓を入力してください。',
	firstname: '名',
	lastname: '姓',
	pleasEnterAValidPhoneNumber: '有効な電話番号を入力してください。',
	phoneNumber: '電話番号',
	pleaseEnterYourCompanyName: '会社名を入力してください。',
	companyName: '会社名',
	pleaseChooseYourCompanySize: '会社の規模を選択してください。',
	companySize: '会社の規模',
	pleaseChooseYourRoleInTheCompany: '会社での役割を選択してください。',
	companyRole: '会社での役割',
	startCreating: '作成を始めましょう !',
	welcomeToNotice: 'Noticeへようこそ !',
	pleaseHelpUsWithForm: '完全なNotice体験を提供する過程でお手伝いください。',
	preview: 'プレビュー',
	rename: '名前を変更',
	duplicate: '複製',
	exportMarkdown: 'Markdownをエクスポート',
	delete: '削除',
	exportJSON: 'JSONをエクスポート',
	type: 'タイプ',
	forCommands: 'コマンド用',
	basicBlocks: '基本ブロック',
	heading: '見出し',
	bigSectionHeading: '大セクション見出し',
	mediumSectionHeading: '中セクション見出し',
	smallSectionHeading: '小セクション見出し',
	bulletedList: '箇条書きリスト',
	organizeContentWithBullets: '箇条書きで内容を整理',
	numberedList: '番号付きリスト',
	createANumberedList: '番号付きリストを作成',
	captureACodeSnippet: 'コードスニペットをキャプチャ',
	hint: 'ヒント',
	provideHelpfulInformation: '役立つ情報を提供',
	quote: '引用',
	highlightASpecificPassageOfText: '特定のテキストの一節をハイライト',
	divider: '区切り',
	separateDifferentBlocks: '異なるブロックを分離',
	toDo: 'ToDo',
	keepTrackOfTasksOrItems: 'タスクや項目を追跡',
	media: 'メディア',
	image: '画像',
	uploadAnImageFile: '画像ファイルをアップロード',
	document: 'ドキュメント',
	uploadADocument: 'ドキュメントをアップロード',
	video: 'ビデオ',
	addAVideo: 'ビデオを追加',
	advancedBlocks: '高度なブロック',
	table: 'テーブル',
	organizeWithRowsAndColumns: '行と列で整理',
	expandable: '展開可能',
	addACollapsableBlock: '折りたたみ可能なブロックを追加',
	textAIGeneration: 'テキストAI生成',
	letOurRobotCreateYourContent: 'ロボットにコンテンツを作成させる',
	imageAIGeneration: 'イメージAI生成',
	letOurRobotCreateYourImages: 'ロボットにイメージを作成させる',
	javascript: 'JavaScript',
	embedJavascript: 'JavaScriptを埋め込む',
	youtube: 'YouTube',
	embedYoutubeVideos: 'YouTubeビデオを埋め込む',
	justCopyPasteTheLinkOfYourVideo:
		'ビデオのリンクをコピー＆ペーストするだけでYouTubeビデオを自動埋め込み。例：https://www.youtube.com/watch?v=m4fDm4rdUdk',
	embedLoomVideos: 'Loomビデオを埋め込む',
	justCopyPasteLoomVideo:
		'ビデオのリンクをコピー＆ペーストするだけでLoomビデオを自動埋め込み。例：https://www.loom.com/share/36656bc4afb84de2bb829183f46a1b40',
	embedVimeos: 'Vimeoを埋め込む',
	embedVimeosInstructions:
		'ビデオのリンクをコピー＆ペーストするだけでVimeoビデオを自動埋め込み。例：https://vimeo.com/251147627',
	embedAirtableInstructions:
		'テーブルビューのリンクをコピー＆ペーストしてAirTableを自動埋め込み。例：https://airtable.com/appeh8s8bwMI7JjlW/shro43JbOcXFQH0tQ/tblnrBMRpvfrcqkko',
	AIIsWriting: 'AIが書いています...',
	Keep: '保持',
	Retry: '再試行',
	DescribeWhatYouWantAI: 'AIに作成したいものを説明してください',
	LetOurAICreate: '私たちのAIにあなたのページを作成させてください',
	LetOurAICreateImage: 'このページに触發された画像を作成する',
	freeTrialEndsIn: '無料トライアルはX日で終了します。',
	AIIsGeneratingAnImageIdea: 'AIが画像のアイデアを生成しています...',
	AIIsGeneratingImage: 'AIが画像を生成しています...',
	GenImagePlaceholder: '一日の終わりにひまわり畑。ゴッホの絵画スタイルで。',
	metadata: 'メタデータ',
	pageMetadata: 'ページのメタデータ',
	giveInformationForSEO: 'SEOとプレビューの向上のためにこのページに情報を追加してください',
	author: '著者',
	editMyName: '私の名前を編集する',
	tags: 'タグ',
	datePublished: '公開日',
	addATag: 'タグを追加',
	advancedOptions: '高度なオプション',
	tellGoogleExists: 'Googleにプロジェクトの存在を知らせる',
	tellGoogleExistsDescription:
		'プロジェクトを適切にインデックスするためには、あなたのウェブサイトをこちらで確認する必要があります ',
	clickHereToFollowOurGuide: '当社のガイドに従うにはこちらをクリック',
	explanationDateOfPublication: '将来の日付を設定することで、選択した日付までページが隠されます。',
	articleHiddenDateFuture: 'この記事は、日付が将来であるため隠されています。',
	blockMenuChangeImageCover: '画像カバーを変更',
	blockMenuAddImageCover: '画像カバーを追加',
	blockMenuDuplicate: '複製',
	blockMenuDelete: '削除',
	blockMenuOnlyText: 'テキストのみ',
	blockMenuWithImage: '画像付き',
	blockMenuPageSummary: 'ページの要約',
	blockMenuBorder: '境界',
	blockMenuLayout: 'レイアウト',
	blockMenuDisplay: '表示',
	blockMenuStyle: 'スタイル',
	subPageUpgradeSucessTitle: 'アップグレード成功',
	subPageUpgradeSuccessMsg:
		'おめでとうございます！ 🎉 あなたのアカウントは成功裏にアップグレードされました。Noticeを選んでいただき、ありがとうございます！',
	subPageGoBack: '編集に戻る',
	deleteProjectDeleteProject: 'プロジェクトを削除',
	deleteProjectAreYouSure: 'このプロジェクトを削除してもよろしいですか？',
	deletePageDeletePage: 'ページを削除',
	deletePageAreYouSure: 'この操作は、このページとそのすべての関連コンテンツを永久に削除します。本当に続けますか？',
	deleteWarning: 'この操作は元に戻すことができません。',
	cancelButton: 'キャンセル',
	confirmButton: '確認',
	pasteLinkHere: 'ここにリンクを貼り付ける',
	addLink: 'リンクを追加',
	removeLink: 'リンクを削除',
	selectAnImage: '画像を選択',
	selectADocument: 'ドキュメントを選択',
	selectAVideo: 'ビデオを選択',
	selectAnAudio: 'オーディオを選択',
	dropYourFileHere: 'アップロードを開始するには、ここにファイルをドロップするか',
	anyDocTypeAccepted: '任意の種類のドキュメントが受け入れられます',
	acceptedTypes: '受け入れられる種類',
	browseFiles: 'ファイルを閲覧',
	filterFiles: 'ファイルをフィルタリング',
	files: 'ファイル',
	enterAnURL: 'URLを入力してください',
}
