export const ko = {
	customization: '맞춤 설정',
	translation: '번역',
	integrations: '통합',
	insights: '통찰력',
	FreePlan: '무료 플랜',
	upgrade: '업그레이드',
	yourProfile: '당신의 프로필',
	general: '일반',
	layout: '레이아웃',
	theme: '테마',
	advanced: '고급',
	styling: '스타일링',
	code: '코드',
	billing: '청구',
	aiSettings: 'AI 설정',
	aiSettingsDescription:
		'AI 설정에 오신 것을 환영합니다, 여기에서는 AI가 이 작업 공간에 대한 콘텐츠를 생성하는 방법을 제어합니다',
	aiSettingSection1: '당신은 무엇을 하나요?',
	aiSettingSection1Description:
		'당신의 업무 라인이나 회사의 초점을 이해하는 데 도움이 됩니다. 귀하의 사업이나 직업에 대한 간략한 설명을 제공하십시오.',
	aiSettingSection1Placeholder: '디지털 마케팅 전략 및 콘텐츠 생성에 전문화된 창의적인 에이전시를 운영합니다',
	aiSettingSection2: '당신의 톤은 무엇인가요?',
	aiSettingSection2Description:
		'워크스페이스의 텍스트에 원하는 톤을 정의하세요. 우리와 당신의 커뮤니케이션 스타일에 맞는 톤을 공유하세요.',
	aiSettingSection2Placeholder: '우리는 전문적이지만 친근하게 소리나며, 연결하기 쉬운 방식으로 전문 지식을 공유합니다',
	aiSettingSection3: '선호하는 작성 스타일의 일부를 살펴보세요',
	aiSettingSection3Description:
		'당신의 글쓰기 스타일이나 가장 좋아하는 글의 일부에 대한 한 두 가지 예를 제공하십시오. 우리의 AI는 이를 적응하고 동일한 스타일로 텍스트를 제공할 것입니다.',
	aiSettingSection3Placeholder: `사실 나는 죽어가는 중이었다. 숨 쉬는 행위는 그저 몸을 끌어당기는 힘이고, 마음은 이미 어떤 불가능한 곳으로 떠나 있었다. 시간이 나를 소모하고 있었다. 한 칸씩 내몰려 들어와 나를 허물어뜨리고 있었다. 난 이제부터 천천히 쇠퇴하는 죽어가는 존재가 되어갔다`,
	aiSettingsModelSettings: 'AI 모델 설정',
	aiSettingModelSection: '당신의 AI 모델 선택',
	aiSettingModelSectionDescription: '당신의 선호에 가장 적합한 AI 생성 모델을 선택하세요.',
	aiSettingGPT4Tooltip: '더 최적화됨',
	aiSettingGPT3Tooltip: '더 빠름',
	edit: '편집',
	save: '저장',
	skip: '건너뛰기',
	changeAISettings: 'AI 설정 변경',
	PleaseClickToEditTheSettings: '설정을 편집하려면 클릭하세요',
	billingDetailsAndInvoices: '청구 세부사항 및 인보이스',
	overview: '개요',
	currentPlan: '현재 플랜',
	nextBillingOn: '다음 청구 날짜',
	nextBillingAmount: '다음 청구 금액',
	numberOfProjects: '프로젝트 수',
	reachesSubscriptionPage: '구독 페이지에 도달',
	billingPageUpgradeButton: '청구 페이지 업그레이드 버튼',
	upgradeYourPlan: '플랜 업그레이드',
	billingInfoAndPayment: '청구 정보 및 결제',
	manageAllYourBilling: '모든 청구 정보 및 결제 방법을 여기에서 관리하세요',
	manageBillingDetails: '청구 세부사항 관리',
	invoicesHistory: '인보이스 기록',
	invoiceID: '인보이스 ID',
	date: '날짜',
	total: '총계',
	status: '상태',
	invoiceReceipt: '송장/영수증',
	download: '다운로드',
	noInfoAvailableYet: '아직 정보가 없습니다',
	hideBranding: '브랜딩 숨기기',
	hideBrandingDescription: '프로젝트에서 Notice 브랜딩을 숨깁니다.',
	handleTitleTagTitle: '<title /> 태그 처리',
	titleTagDescription: '활성화되면, Notice가 프로젝트의 <title /> 태그를 처리합니다.',
	projectLogo: '프로젝트 로고',
	projectLogoDescription: '프로젝트 로고는 프로젝트의 다양한 위치에 표시될 수 있습니다.',
	faviconDescription: '로고를 파비콘으로 사용하세요.',
	faviconWarning: '이 기능을 사용하려면 위에 <b>프로젝트 로고</b>를 업로드해야 합니다.',
	uploadImage: '이미지 업로드',
	configureLogoRedirect: '로고가 리다이렉트되는 주소 구성',
	navigationType: '내비게이션 유형',
	navigationTypeDescription: `쿼리 파라미터는 URL에서 'page=' 값을 사용하여 내비게이션을 처리합니다. 슬래시는 클래식 '/' 서브폴더를 사용합니다.`,
	stopUserTracking: '사용자 추적 중지',
	stopUserTrackingDescription: 'Notice는 사용자 통계 제공을 위한 데이터 수집을 중지합니다.',
	stopUserTrackingWarning: '통계 대시보드가 비활성화됩니다.',
	headerSpace: '헤더 공간',
	projectTitle: '프로젝트 제목',
	homeButton: '홈 버튼',
	topSpace: '상단 공간',
	contactForm: '연락처 양식',
	emailToReceiveMessages: '메시지를 받을 이메일',
	themeSwitch: '테마 전환',
	languageSelector: '언어 선택기',
	breadcrumbNavigation: '브레드크럼 내비게이션',
	timeToRead: '읽는 데 걸리는 시간',
	shareToFacebook: 'Facebook에 공유하기',
	shareToTwitter: 'Twitter에 공유하기',
	shareToLinkedIn: 'LinkedIn에 공유하기',
	leftSpace: '왼쪽 공간',
	navigationMenu: '내비게이션 메뉴',
	rightSpace: '오른쪽 공간',
	anchorMenu: '앵커 메뉴',
	bottomSpace: '아래쪽 공간',
	bottomNavigation: '하단 내비게이션',
	readMoreArticles: '더 많은 기사 읽기',
	setProjectTitle: '프로젝트 제목 설정',
	setProjectTitleDescription: '각 페이지 상단에 프로젝트 이름 표시.',
	NavMenuDesc: '프로젝트에 쉽게 접근할 수 있게 하는 왼쪽 내비게이션 메뉴.',
	searchDescription: '프로젝트 내에서 사용자가 검색할 수 있게 합니다. 또한',
	analyticsSupport: '분석 보고서',
	searchDescription2: '이러한 요청에 대해 Notice에서 받을 수 있습니다.',
	themeSwitchDescription: '사용자가 프로젝트의 테마를 변경할 수 있게 합니다. 테마를 설정할 수 있습니다',
	hereInsideColors: '여기 색상에서.',
	languageSwitchDescription: '사용자가 프로젝트의 언어를 변경할 수 있게 합니다. 번역을 설정할 수 있습니다',
	here: '여기',
	allowNavDescription: '사용자가 내비게이션 메뉴를 사용하여 페이지 간에 이동할 수 있게 합니다.',
	displayHomeButtonDescription: '사용자가 홈 페이지로 이동할 수 있는 버튼을 표시합니다.',
	timeToReadDescription: '페이지의 예상 읽기 시간을 표시합니다.',
	facebookShareDescription: '사용자가 기사를 Facebook에서 공유할 수 있게 합니다.',
	twitterShareDescription: '사용자가 기사를 Twitter에서 공유할 수 있게 합니다.',
	linkedinShareDescription: '사용자가 기사를 LinkedIn에서 공유할 수 있게 합니다.',
	nextPrevDescription: '페이지 하단에 다음 및 이전 페이지로 이동하는 버튼을 추가합니다.',
	anchorRightMenuDescription: '사용자가 페이지의 제목 사이를 이동할 수 있게 하는 오른쪽 내비게이션 메뉴를 추가합니다.',
	allowRecommendedArticlesDescription: '사용자가 관련 기사를 더 읽을 수 있게 합니다.',
	navMenuDesc: '사용자가 페이지 사이를 이동할 수 있게 하는 왼쪽 내비게이션 메뉴를 추가합니다.',
	pageTitle: '페이지 제목',
	colors: '색상',
	lightBgColor: '밝은 배경 색상',
	lightFontColor: '밝은 글꼴 색상',
	lightHighlightColor: '밝은 강조 색상',
	darkBgColor: '어두운 배경 색상',
	darkFontColor: '어두운 글꼴 색상',
	darkHighlightColor: '어두운 강조 색상',
	fonts: '글꼴',
	fontFamily: '글꼴 가족',
	fontSize: '글꼴 크기',
	spacing: '간격',
	blockPadding: '블록 패딩',
	maxWidth: '최대 너비',
	maxWidthDescription: '주요 컬럼의 최대 너비를 설정합니다',
	icons: '아이콘',
	iconStroke: '아이콘 선 굵기',
	headings: '제목',
	h1Weight: 'H1 두께',
	h1Size: 'H1 크기',
	h2Size: 'H2 크기',
	h2Weight: 'H2 두께',
	h3Size: 'H3 크기',
	h3Weight: 'H3 두께',
	headingsPadding: '제목 패딩',
	titleFontSize: '제목 글꼴 크기',
	fontFamilyDescription:
		'<a href="https://fonts.google.com/" target="_blank">Google Fonts</a>에서 다양한 글꼴을 찾아보세요.',
	text: '텍스트',
	textLineHeight: '텍스트 줄 높이',
	textLetterSpacing: '글자 간격',
	codeHtmlDesc: '작성한 코드는 프로젝트의 ',
	codeHtmlDesc2: '태그 안에 삽입됩니다.',
	CSSDesc: 'CSS 코드를 작성하여 프로젝트의 외관을 변경하세요.',
	JavascriptDesc: '자바스크립트 코드를 작성하여 프로젝트의 동작을 변경하세요.',
	insightsDesc: '사용자 행동에 대한 데이터로 콘텐츠와 고객 지원을 개선하세요.',
	publishing: '게시',
	publish: '게시하기',
	visitPage: '페이지 방문하기',
	newProject: '새 프로젝트',
	createNewProject: '새 프로젝트 만들기',
	newPage: '새 페이지',
	addNewPage: '현재 프로젝트에 새 페이지 추가하기',
	workspaceSettings: '작업 공간 설정',
	accountSettings: '계정 설정',
	supportAndCommunity: '지원 및 커뮤니티',
	signOut: '로그아웃',
	whatIsNew: '새로운 소식',
	inviteCollaborators: '협력자 초대하기',
	inviteCollaboratorsDescription: '함께하는 즐거움을 느껴보세요. 프로젝트에 협력자를 초대하세요.',
	emailAddress: '이메일 주소',
	admin: '관리자',
	editor: '편집자',
	viewer: '조회자',
	owner: '소유자',
	close: '닫기',
	invite: '초대하기',
	translationDescription: '100개 이상의 언어로 콘텐츠를 번역하세요.',
	selectBlock: '블록을 클릭하여 선택하세요',
	selectProjectLanguage: '이 프로젝트의 기본 언어를 선택하세요',
	validate: '확인',
	selectLanguageHint: '힌트: 이것은 현재 프로젝트의 언어입니다.',
	configureTranslation: '번역 구성',
	translationStatus: '번역 상태',
	selected: '선택됨',
	translated: '번역됨',
	notTranslated: '번역되지 않음',
	translationOutOfDate: '번역이 오래됨',
	translateBlock: '블록 번역하기',
	markAsIncomplete: '미완성으로 표시',
	markAsComplete: '완성으로 표시',
	markAsCompleteAndGoToNext: '완료로 표시하고 다음으로 넘어가기',
	anotherNoticeTabIsOpened: '다른 Notice 탭이 열려 있습니다',
	pleaseReloadToAvoidMismatch: '충돌을 방지하기 위해 페이지를 새로고침 해주세요.',
	reload: '새로고침',
	oopsNoResultsWereFound: '이런! 결과를 찾을 수 없습니다.',
	tryAgainNoResults: '다른 기간으로 다시 시도해 보세요.',
	configureYourTranslation: '번역을 구성하세요',
	allowUsersToChangeLang: '사용자가 언어를 변경할 수 있게 허용',
	addsALangQueryLike: '와 같은 언어 쿼리를 추가합니다',
	toYourProjectUrl: '당신의 프로젝트 URL에',
	addLanguageQueryToUrl: 'URL에 언어 쿼리 추가',
	chooseADefaultLanguage: '기본 언어를 선택하세요',
	availableLanguages: '사용 가능한 언어',
	ifYouWantMoreLanguages: '더 많은 언어를 원하시면,',
	contactUs: '연락주세요',
	letUsKnow: '알려주세요.',
	languageSelectorWarning: '언어 선택기는 또한 레이아웃에서 관리될 수 있습니다',
	clickingHere: '여기를 클릭하면',
	addNew: '새로 추가',
	translateTo: '~로 번역하기',
	translateThisPage: '이 페이지 번역하기',
	stepByStepGuide: '단계별 가이드',
	manyHandsMakeLightWork: '많은 손이 일을 가볍게 만든다',
	createAndCustomizeContent: '콘텐츠 생성 및 사용자 정의',
	clickOnPublish: '게시를 클릭하세요',
	deployItAnywhere: '어디에나 배포하기 위해 통합을 클릭하세요',
	inviteColleaguesToCollaborate: '동료를 초대하여 프로젝트에 협력하세요.',
	inviteYourTeam: '팀을 초대하세요',
	getInTouchWithUs: '저희에게 연락하세요',
	getInTouchDescription: '제안이 있거나 도움이 필요하신가요? 메시지를 보내주시거나 슬랙 커뮤니티에 참여하세요.',
	accountSettingsDescription: '계정 정보, 선호도 및 로그인 설정을 관리하세요.',
	dashboardLanguage: '대시보드 언어',
	updateEmail: '이메일 업데이트',
	featureComingSoon: '곧 출시되는 기능...',
	signOnWithGoogle: 'Google과의 연동을 한 번의 클릭으로 설정하세요',
	yourGoogleAccountHasBeenUnlinked: 'Google 계정 연동이 성공적으로 해제되었습니다.',
	unlinkAccount: '계정 연동 해제',
	linkAccount: '계정 연동',
	singleSignOnGithub: 'Github과의 단일 로그인을 한 번의 클릭으로 설정하세요',
	githubAccountHasBeenUnlinked: 'Github 계정 연동이 성공적으로 해제되었습니다.',
	signOutDescription: 'Notice 계정에서 로그아웃할 수 있습니다.',
	accountDeletion: '계정 삭제',
	accountDeletionDescription: 'Notice 계정 및 모든 관련 데이터를 삭제할 수 있습니다.',
	deleteAccount: '계정 삭제',
	deleteMyAccountBody: '안녕하세요, 제 계정을 삭제하고 싶습니다.',
	deleteMyAccountSubject: '계정 삭제 요청',
	settings: '설정',
	account: '계정',
	myWorkspaces: '내 작업 공간',
	workspace: '작업 공간',
	collaborators: '협업자',
	plans: '플랜',
	profilePicture: '프로필 사진',
	profilePictureDescription: '최소 64픽셀 크기의 정사각형 이미지를 사용하세요',
	fullName: '전체 이름',
	myWorkspacesDescription: '모든 작업 공간을 볼 수 있는 페이지입니다',
	workspaces: '작업 공간들',
	created: '생성된 날짜',
	manageWorkspaceProfile: '작업 공간 프로필 관리',
	workspaceProfile: '작업 공간 프로필',
	workspaceLogo: '작업 공간 로고',
	displayName: '표시 이름',
	workspaceDeletion: '작업 공간 삭제',
	workspaceDeletionDescription: '작업 공간 및 모든 관련 데이터를 삭제할 수 있습니다',
	deleteWorkspace: '작업 공간 삭제',
	storage: '저장소',
	storageDescription: '이미지, 비디오, 파일 등',
	deleteWorkspaceDescription: '이 작업 공간을 정말 삭제하시겠습니까?',
	deleteWorkspaceWarning: '이 작업은 되돌릴 수 없습니다',
	cancel: '취소',
	confirm: '확인',
	visits: '방문자 수',
	statistics: '통계',
	visitsByTimeSpan: '시간대별 방문자 수',
	location: '위치',
	locationDescription: '방문자의 위치',
	device: '기기',
	deviceDescription: '방문자가 사용하는 기기',
	browser: '브라우저',
	browserDescription: '방문자가 사용하는 브라우저',
	OSdescription: '방문자가 사용하는 운영 체제',
	integration: '통합',
	hosting: '호스팅',
	noticeDomain: 'Notice 도메인',
	noticeDomainDescription: 'Notice 프로젝트의 도메인 이름 변경',
	allowedCharacters: '허용된 문자',
	letters: '문자',
	numbers: '숫자',
	and: '그리고',
	domainName: '도메인 이름',
	customDomainDescription: '프로젝트에 사용자 정의 도메인 이름을 사용할 수 있습니다',
	customDomain: '사용자 정의 도메인',
	customDomainMissing: '이 프로젝트에 아직 사용자 정의 도메인을 설정하지 않았습니다',
	customDomainPresent: '이 프로젝트에 사용자 정의 도메인을 이미 설정했습니다',
	configure: '구성',
	whatDomainWouldYouLikeToLink: '어떤 도메인을 프로젝트에 연결하고 싶으신가요?',
	hostnameIsInvalid: '호스트 이름이 유효하지 않습니다. 서브도메인만 허용됩니다.',
	mustOwnSubdomainAndAbilityToEditDNS: '서브도메인을 소유하고 DNS 레코드를 편집할 수 있어야 합니다.',
	configureDNS: 'DNS 레코드 구성',
	others: '기타',
	webflowIntegration: '한 번의 클릭으로 Webflow 사이트에 Notice 블록 추가',
	wordpressIntegration: 'Wordpress에서 완벽한 콘텐츠를 위한 Notice 플러그인 설치',
	shopifyIntegration: 'Shopify 상점에서 고객 경험 개선',
	umsoIntegration: 'UMSO 사이트에 Notice 블록 추가 및 방문자 통계 수집',
	unicornIntegration: '한 번의 클릭으로 웹사이트에 스마트 블록을 추가하여 개선 및 사용자 정의',
	wixIntegration: 'Wix 내부에 Notice를 추가하는 것은 쉽습니다. 임베드 블록을 추가하고 통합 완료!',
	squarespaceIntegration: '항상 빠르게. 코드 블록을 추가하고 Notice ID를 붙여넣어 콘텐츠를 ON 하세요.',
	reactIntegration: 'React에서 단 한 단계로 Notice 블록을 쉽게 통합합니다.',
	nextIntegration: 'SSR 프론트엔드 프레임워크 Next.js를 사용하는 팬들을 위한 원활한 통합.',
	vueIntegration: 'Vue.js 프로젝트에 Notice를 더하기만 하면 1분 안에 통합할 수 있습니다.',
	nuxtIntegration: 'SSR 프론트엔드 프레임워크 Nuxt를 사용하는 팬들을 위한 원활한 통합.',
	linkIntegration: '가장 간단한 솔루션, 링크만 공유하세요! 웹사이트조차 필요 없습니다.',
	htmlIntegration: '특정 프레임워크를 찾을 수 없는 경우 웹사이트에 가장 선호되는 솔루션입니다.',
	iframeIntegration: '사용하기 쉽고, 모바일 앱을 포함한 모든 곳에 맞춤형으로 적용할 수 있는 iframes.',
	rawJSONIntegration: '프로젝트에 대한 완전한 제어를 원하는 고급 사용자를 위해.',
	qrcodeIntegration: '사용자의 손끝에서 콘텐츠를! 자체 QR 코드를 공유하세요 :)',
	integrationsDescription: '한 번의 클릭으로 귀하의 웹사이트에 Notice를 통합하세요',
	categories: '카테고리',
	all: '전체',
	needADifferentIntegrationAndCannotFindItHere: '다른 통합이 필요하고 여기서 찾을 수 없나요?',
	shareables: '공유 가능한 항목들',
	useTemplates: '템플릿 사용하기',
	useAIGeneration: '인공 지능 사용하기',
	selectProjectTip: '인공 지능 또는 예시 프로젝트를 사용하여 콘텐츠를 생성할 수 있습니다.',
	preFilledTemplate: '미리 채워진 템플릿',
	helpCenter: '도움말 센터',
	termsOfuse: '이용 약관',
	privacyPolicy: '개인정보 처리방침',
	jobBoard: '구인 게시판',
	getStarted: '시작하기',
	changelog: '변경 로그',
	missionAndValues: '미션과 가치',
	investorsReport: '투자자 보고서',
	aboutUs: '회사 소개',
	startFromScratch: '처음부터 시작하기',
	helpOurAIGenerateYour: '우리의 인공지능이 당신의 것을 생성하도록 도와주세요',
	provideYourWebsiteURL: '웹사이트 URL을 제공해주세요',
	weFoundAWebsite: '귀하의 이메일 주소와 연결된 웹사이트를 찾았습니다',
	makeSureProvidedWebsiteAlreadyExists: '제공된 웹사이트가 이미 존재하는지 확인해주세요',
	AIExplanation: '우리의 인공지능은 귀하의 사이트를 분석하여 생성합니다',
	basedOnTheWebsiteInformation: '웹사이트 정보에 기반하여.',
	youCanUseAnyExistingURL: '기존의 어떤 URL도 사용할 수 있습니다.',
	enhanceYourGeneration: '추가 지침을 통해 생성물을 개선하세요',
	giveInstructions: '당신의 것을 생성하기 위해 인공지능에 지침을 제공하세요',
	makeSureThisPromptIsMatching: '이 지침이 당신의 프로젝트 유형에 맞는지 확인하세요.',
	writeItInFrenchOnlyUsePastTense: '예: 프랑스어로만 작성하고 과거시제만 사용하세요.',
	backToList: '목록으로 돌아가기',
	pricingDescription: '우리의 가격은 숨겨진 비용이 없고 귀하의 목표와 일치합니다.',
	monthlyTokenAmount: '월간 토큰 수',
	billingPeriod: '청구 기간',
	monthly: '월간',
	yearly: '연간',
	oneMonthFree: '1개월 무료',
	customizeYourNewContentsHome: '컨텐츠의 새로운 홈을 맞춤 설정하세요',
	manageSmartContentForYourCompany: '회사를 위한 스마트 컨텐츠 관리',
	activateContentSynergiesForYourTeam: '팀을 위한 컨텐츠 시너지 활성화',
	forThoseNeedingAnEnterpriseGradeSolution: '엔터프라이즈급 솔루션이 필요한 분들을 위해',
	letsTalk: '상의합시다',
	numberOfCollaborators: '협업자 수',
	numberOfWorkspaces: '작업 공간 수',
	integrateAnywhere: '어디서나 통합',
	removeNoticeBranding: 'Notice 브랜딩 제거',
	aiAssistant: '인공지능 어시스턴트',
	customSupportAndHelp: '맞춤형 지원 및 도움말',
	premiumCdn: '프리미엄 CDN',
	ssoEnabled: 'SSO 사용 가능',
	onPremiseData: '현장 데이터',
	contentAndSeoAudit: '콘텐츠 및 SEO 감사',
	downgrade: '다운그레이드',
	newWorkspace: '새 작업 공간',
	createANewWorkspace: '새 작업 공간 만들기',
	enterNameOfNewWorkspace: '새 작업 공간의 이름 입력',
	create: '생성하기',
	signIn: '로그인',
	signInDescription: '소셜 네트워크 계정으로 Notice 계정에 로그인하거나 이메일을 사용하세요.',
	signUp: '가입하기',
	continueWithGoogle: 'Google 계정으로 계속하기',
	continueWithGithub: 'Github 계정으로 계속하기',
	orSignInUsingWorkEmail: '또는 업무 이메일을 사용하여 로그인하세요',
	enterWorkEmail: '업무 이메일 입력',
	enterTemporaryCode: '임시 코드 입력',
	weJustSentYouATemporaryLoginCode: '방금 귀하에게 임시 로그인 코드를 보냈습니다.',
	pleaseCheckYourInbox: '받은 편지함을 확인하세요.',
	alreadyHaveAnAccountSignIn: '이미 계정이 있으신가요? 로그인하세요',
	continueWithLoginCode: '로그인 코드로 계속하기',
	continueWithEmail: '이메일로 계속하기',
	selectYourProject: '프로젝트 선택',
	chooseYourIntegration: '통합을 선택하세요',
	publishingYourProject: '프로젝트 게시',
	projectCreated:
		'귀하의 Notice 프로젝트가 생성되었습니다! 우리의 통합 또는 직접 생성된 링크를 통해 이 새 프로젝트를 웹사이트에 추가하세요.',
	signInMethods: '로그인 방법',
	signInMethodsDescription: '계정의 로그인 방법을 관리하세요',
	joinOurSlackCommunityForUpdatesAndFeedback: '업데이트와 피드백을 위해 Slack 커뮤니티에 가입하세요',
	joinSlack: 'Slack에 가입하기',
	joinTheAcademy: '아카데미에 가입하기',
	readOurDoc: '문서를 읽기',
	checkOurTutorials: '튜토리얼 확인하기',
	sendUsAnEmail: '이메일 보내기',
	pleaseEnterYourFirstName: '성을 입력해주세요.',
	pleaseEnterYourLastName: '이름을 입력해주세요.',
	firstname: '이름',
	lastname: '성',
	pleasEnterAValidPhoneNumber: '유효한 전화번호를 입력해주세요.',
	phoneNumber: '전화번호',
	pleaseEnterYourCompanyName: '회사 이름을 입력해주세요.',
	companyName: '회사 이름',
	pleaseChooseYourCompanySize: '회사 규모를 선택해주세요.',
	companySize: '회사 규모',
	pleaseChooseYourRoleInTheCompany: '회사에서의 역할을 선택해주세요.',
	companyRole: '회사 역할',
	startCreating: '창작 시작하기 !',
	welcomeToNotice: 'Notice에 오신 것을 환영합니다 !',
	pleaseHelpUsWithForm: 'Notice 경험을 제공하는 과정에서 도와주세요.',
	preview: '미리 보기',
	rename: '이름 바꾸기',
	duplicate: '복제',
	exportMarkdown: '마크다운 내보내기',
	delete: '삭제',
	exportJSON: 'JSON 내보내기',
	type: '유형',
	forCommands: '명령어용',
	paragraph: '문단',
	justWriteDownSomeText: '텍스트를 작성하세요',
	basicBlocks: '기본 블록',
	heading: '제목',
	bigSectionHeading: '큰 섹션 제목',
	mediumSectionHeading: '중간 섹션 제목',
	smallSectionHeading: '작은 섹션 제목',
	bulletedList: '글머리 기호 목록',
	organizeContentWithBullets: '글머리 기호로 내용 정리',
	numberedList: '번호 매긴 목록',
	createANumberedList: '번호 매긴 목록 만들기',
	captureACodeSnippet: '코드 스니펫 캡처',
	hint: '힌트',
	provideHelpfulInformation: '도움이 되는 정보 제공',
	quote: '인용',
	highlightASpecificPassageOfText: '특정 텍스트 구절 강조',
	divider: '구분선',
	separateDifferentBlocks: '다른 블록 분리',
	toDo: '할 일',
	keepTrackOfTasksOrItems: '할 일 또는 항목 추적',
	media: '미디어',
	image: '이미지',
	uploadAnImageFile: '이미지 파일 업로드',
	document: '문서',
	uploadADocument: '문서 업로드',
	video: '비디오',
	addAVideo: '비디오 추가',
	advancedBlocks: '고급 블록',
	table: '테이블',
	organizeWithRowsAndColumns: '행과 열로 정리',
	expandable: '확장 가능',
	addACollapsableBlock: '접을 수 있는 블록 추가',
	textAIGeneration: '텍스트 AI 생성',
	letOurRobotCreateYourContent: '우리 로봇이 콘텐츠 만들기',
	imageAIGeneration: '이미지 AI 생성',
	letOurRobotCreateYourImages: '우리 로봇이 이미지 만들기',
	javascript: '자바스크립트',
	embedJavascript: '자바스크립트 삽입',
	youtube: '유튜브',
	embedYoutubeVideos: '유튜브 비디오 삽입',
	justCopyPasteTheLinkOfYourVideo:
		'비디오 링크를 그냥 복사 붙여넣기하여 유튜브 비디오 자동 삽입. 예시 링크: https://www.youtube.com/watch?v=m4fDm4rdUdk',
	embedLoomVideos: 'Loom 비디오 삽입',
	justCopyPasteLoomVideo:
		'비디오 링크를 그냥 복사 붙여넣기하여 Loom 비디오 자동 삽입. 예시 링크: https://www.loom.com/share/36656bc4afb84de2bb829183f46a1b40',
	embedVimeos: 'Vimeo 삽입',
	embedVimeosInstructions:
		'비디오 링크를 그냥 복사 붙여넣기하여 Vimeo 비디오 자동 삽입. 예시 링크: https://vimeo.com/251147627',
	embedAirtableInstructions:
		'테이블 뷰 링크를 그냥 복사 붙여넣기하여 AirTable 자동 삽입. 예시 링크: https://airtable.com/appeh8s8bwMI7JjlW/shro43JbOcXFQH0tQ/tblnrBMRpvfrcqkko',
	AIIsWriting: 'AI가 작성 중...',
	Keep: '유지',
	Retry: '재시도',
	DescribeWhatYouWantAI: 'AI에게 만들고 싶은 것을 설명하세요',
	LetOurAICreate: '우리 AI가 당신의 페이지를 만들게 하세요',
	LetOurAICreateImage: '이 페이지에서 영감을 받은 이미지를 만들기',
	freeTrialEndsIn: '무료 평가판은 X일 후에 종료됩니다.',
	AIIsGeneratingAnImageIdea: 'AI가 이미지 아이디어를 생성하고 있습니다...',
	AIIsGeneratingImage: 'AI가 이미지를 생성하고 있습니다...',
	GenImagePlaceholder: '하루의 끝에 있는 해바라기 밭입니다. 반 고흐 그림 스타일로.',
	metadata: '메타데이터',
	pageMetadata: '페이지 메타데이터',
	giveInformationForSEO: 'SEO 및 미리보기 개선을 위해 이 페이지에 정보를 제공하세요',
	author: '저자',
	editMyName: '내 이름 편집하기',
	tags: '태그',
	datePublished: '게시 날짜',
	addATag: '태그 추가',
	advancedOptions: '고급 옵션',
	tellGoogleExists: 'Google에 귀하의 프로젝트가 존재한다고 알리기',
	tellGoogleExistsDescription: '프로젝트를 올바르게 색인화하려면 웹사이트를 여기에서 확인해야 합니다 ',
	clickHereToFollowOurGuide: '저희 가이드를 따르려면 여기를 클릭하세요',
	explanationDateOfPublication: '미래의 날짜를 설정하면 선택한 날짜까지 페이지가 숨겨집니다.',
	articleHiddenDateFuture: '이 기사는 날짜가 미래이기 때문에 숨겨져 있습니다.',
	blockMenuChangeImageCover: '이미지 커버 변경',
	blockMenuAddImageCover: '이미지 커버 추가',
	blockMenuDuplicate: '복제',
	blockMenuDelete: '삭제',
	blockMenuOnlyText: '텍스트만',
	blockMenuWithImage: '이미지 포함',
	blockMenuPageSummary: '페이지 요약',
	blockMenuBorder: '테두리',
	blockMenuLayout: '레이아웃',
	blockMenuDisplay: '표시',
	blockMenuStyle: '스타일',
	subPageUpgradeSucessTitle: '업그레이드 성공',
	subPageUpgradeSuccessMsg:
		'축하합니다! 🎉 귀하의 계정이 성공적으로 업그레이드되었습니다. 귀하의 경험을 향상시키기 위해 Notice를 선택해주셔서 감사합니다!',
	subPageGoBack: '편집으로 돌아가기',
	deleteProjectDeleteProject: '프로젝트 삭제',
	deleteProjectAreYouSure: '이 프로젝트를 삭제하시겠습니까?',
	deleteWarning: '이 작업은 취소할 수 없습니다.',
	cancelButton: '취소',
	confirmButton: '확인',
	deletePageDeletePage: '페이지 삭제',
	deletePageAreYouSure: '이 작업은 이 페이지와 모든 관련 콘텐츠를 영구적으로 삭제합니다. 계속하시겠습니까?',
	pasteLinkHere: '여기에 링크 붙여넣기',
	addLink: '링크 추가',
	removeLink: '링크 제거',
	selectAnImage: '이미지 선택',
	selectADocument: '문서 선택',
	selectAVideo: '비디오 선택',
	selectAnAudio: '오디오 선택',
	dropYourFileHere: '업로드를 시작하려면 파일을 여기에 놓거나',
	anyDocTypeAccepted: '모든 종류의 문서가 허용됩니다',
	acceptedTypes: '허용된 유형',
	browseFiles: '파일 찾아보기',
	filterFiles: '파일 필터링',
	files: '파일',
	enterAnURL: 'URL을 입력하세요',
}
