export const pt = {
	customization: 'Personalização',
	translation: 'Tradução',
	integrations: 'Integrações',
	insights: 'Insights',
	FreePlan: 'Plano Gratuito',
	upgrade: 'Atualizar',
	yourProfile: 'Seu perfil',
	general: 'Geral',
	layout: 'Layout',
	theme: 'Tema',
	advanced: 'Avançado',
	styling: 'Estilização',
	code: 'Código',
	billing: 'Faturamento',
	aiSettings: 'Configurações de IA',
	aiSettingsDescription:
		'Bem-vindo às Configurações de IA, onde você controla como nossa IA gera conteúdo para este espaço de trabalho',
	aiSettingSection1: 'O que você faz?',
	aiSettingSection1Description:
		'Ajude-nos a entender sua linha de trabalho ou o foco de sua empresa. Por favor, forneça uma breve descrição de seu negócio ou profissão.',
	aiSettingSection1Placeholder:
		'Eu dirijo uma agência criativa que se especializa em estratégias de marketing digital e criação de conteúdo',
	aiSettingSection2: 'Qual é o seu tom?',
	aiSettingSection2Description:
		'Defina o tom que você deseja para o texto em seu espaço de trabalho. Compartilhe conosco o tipo de tom que se alinha com seu estilo de comunicação.',
	aiSettingSection2Placeholder:
		'Soamos profissionais, mas amigáveis, compartilhando nossa expertise de uma maneira fácil de se conectar',
	aiSettingSection3: 'Vislumbre do seu estilo de escrita preferido',
	aiSettingSection3Description:
		'Forneça um ou dois exemplos do seu estilo de escrita ou um trecho de um dos seus textos favoritos. Nosso AI irá adaptar e fornecer o texto no mesmo estilo.',
	aiSettingSection3Placeholder: `Não é bastante não ser cego para ver as árvores e as flores. É preciso também não ter filosofia nenhuma.`,
	aiSettingsModelSettings: 'Configurações do Modelo de IA',
	aiSettingModelSection: 'Escolha o seu modelo de IA',
	aiSettingModelSectionDescription: 'Selecione o modelo de geração de IA que melhor se adapta às suas preferências.',
	aiSettingGPT4Tooltip: 'Mais otimizado',
	aiSettingGPT3Tooltip: 'Mais rápido',
	edit: 'editar',
	save: 'salvar',
	skip: 'pular',
	changeAISettings: 'Alterar configurações de IA',
	PleaseClickToEditTheSettings: 'Por favor, clique para editar as configurações',
	billingDetailsAndInvoices: 'Detalhes de faturamento e Faturas',
	overview: 'Visão geral',
	currentPlan: 'Plano atual',
	nextBillingOn: 'Próximo faturamento em',
	nextBillingAmount: 'Valor do próximo faturamento',
	numberOfProjects: 'Número de projetos',
	reachesSubscriptionPage: 'Acessa a página de assinatura',
	billingPageUpgradeButton: 'Botão de atualização da página de faturamento',
	upgradeYourPlan: 'Atualize seu Plano',
	billingInfoAndPayment: 'Informações de Faturamento e Pagamento',
	manageAllYourBilling: 'Gerencie todas as suas informações de faturamento e métodos de pagamento aqui',
	manageBillingDetails: 'Gerenciar detalhes de faturamento',
	invoicesHistory: 'Histórico de faturas',
	invoiceID: 'ID da Fatura',
	date: 'Data',
	total: 'Total',
	status: 'Status',
	invoiceReceipt: 'Nota fiscal/Recibo',
	download: 'Baixar',
	noInfoAvailableYet: 'Ainda não há informações disponíveis',
	hideBranding: 'Ocultar marca',
	hideBrandingDescription: 'Oculta a marca Notice no seu projeto.',
	handleTitleTagTitle: 'Manipular a tag <title />',
	titleTagDescription: 'Quando ativado, o Notice manipulará a tag <title /> do seu projeto.',
	projectLogo: 'Logo do projeto',
	projectLogoDescription: 'O logo do seu projeto pode ser exibido em diferentes locais do seu projeto.',
	faviconDescription: 'Use o seu logo como favicon.',
	faviconWarning: (
		<span>
			Você precisa fazer upload de um <b>Logo do projeto</b> acima para habilitar este recurso.
		</span>
	),
	uploadImage: 'Fazer upload de imagem',
	configureLogoRedirect: 'Configure o endereço para o qual o logo redireciona',
	navigationType: 'Tipo de navegação',
	navigationTypeDescription: `O parâmetro 'page=' será usado na URL para manipular a navegação. Slash usará o clássico '/' subdiretório.`,
	stopUserTracking: 'Parar rastreamento do usuário',
	stopUserTrackingDescription: 'O Notice não coletará dados para fornecer estatísticas.',
	stopUserTrackingWarning: <span>O painel de estatísticas será desativado.</span>,
	headerSpace: 'Espaço do cabeçalho',
	projectTitle: 'Título do projeto',
	homeButton: 'Botão Início',
	topSpace: 'Espaço superior',
	contactForm: 'Formulário de contato',
	emailToReceiveMessages: 'E-mail para receber mensagens',
	themeSwitch: 'Alternador de tema',
	languageSelector: 'Seletor de idioma',
	breadcrumbNavigation: 'Navegação breadcrumb',
	timeToRead: 'Tempo de leitura',
	shareToFacebook: 'Compartilhar no Facebook',
	shareToTwitter: 'Compartilhar no Twitter',
	shareToLinkedIn: 'Compartilhar no LinkedIn',
	leftSpace: 'Espaço esquerdo',
	navigationMenu: 'Menu de navegação',
	rightSpace: 'Espaço direito',
	anchorMenu: 'Menu de âncora',
	bottomSpace: 'Espaço inferior',
	bottomNavigation: 'Navegação inferior',
	readMoreArticles: 'Ler mais artigos',
	setProjectTitle: 'Definir título do projeto',
	setProjectTitleDescription: 'Exibirá o título do projeto no espaço superior de cada página.',
	navMenuDesc: 'Menu de navegação à esquerda que facilita o acesso ao seu projeto.',
	searchDescription: 'Permitir que o usuário pesquise dentro do seu projeto. você também terá',
	analyticsSupport: 'suporte de análise',
	searchDescription2: 'do notice para a pesquisa do seu projeto.',
	themeSwitchDescription:
		'Você pode permitir que os usuários mudem o tema do seu projeto. você pode configurar seu tema',
	hereInsideColors: 'aqui dentro de cores.',
	languageSwitchDescription:
		'Você pode permitir que os usuários mudem o idioma do seu projeto. Você pode configurar suas traduções',
	here: 'aqui',
	allowNavDescription: 'Permitir que os usuários naveguem entre as páginas usando o menu de navegação.',
	displayHomeButtonDescription: 'Exibir um botão de início para os usuários navegarem para a página inicial.',
	timeToReadDescription: 'Exibir o tempo estimado de leitura de uma página.',
	facebookShareDescription: 'Permitir que os usuários compartilhem seus artigos no Facebook.',
	twitterShareDescription: 'Permitir que os usuários compartilhem seus artigos no Twitter.',
	linkedinShareDescription: 'Permitir que os usuários compartilhem seus artigos no LinkedIn.',
	nextPrevDescription:
		'Adicionar botões para navegar para as próximas e anteriores páginas na parte inferior da página.',
	anchorRightMenuDescription:
		'Adicionar um menu à direita que permite aos usuários navegar dentro dos subtítulos da página atual.',
	allowRecommendedArticlesDescription: 'Permitir que os usuários leiam mais artigos relacionados ao atual.',
	pageTitle: 'Título da página',
	colors: 'Cores',
	lightBgColor: 'Cor de Fundo Claro',
	lightFontColor: 'Cor da Fonte Clara',
	lightHighlightColor: 'Cor de Destaque Clara',
	darkBgColor: 'Cor de Fundo Escura',
	darkFontColor: 'Cor da Fonte Escura',
	darkHighlightColor: 'Cor de Destaque Escura',
	fonts: 'Fontes',
	fontFamily: 'Família de fontes',
	fontSize: 'Tamanho da fonte',
	spacing: 'Espaçamento',
	blockPadding: 'Preenchimento do bloco',
	maxWidth: 'Largura Máxima',
	maxWidthDescription: 'definir largura máxima para a coluna principal',
	icons: 'Ícones',
	iconStroke: 'Largura do traço do ícone',
	headings: 'Cabeçalhos',
	h1Weight: 'Peso do H1',
	h1Size: 'Tamanho do H1',
	h2Size: 'Tamanho do H2',
	h2Weight: 'Peso do H2',
	h3Size: 'Tamanho do H3',
	h3Weight: 'Peso do H3',
	headingsPadding: 'Preenchimento dos Cabeçalhos',
	titleFontSize: 'Tamanho da fonte do título',
	fontFamilyDescription: `Para explorar fontes, vá para <a href="https://fonts.google.com/" target="_blank">Google Fonts.</a>`,
	text: 'Texto',
	textLineHeight: 'Altura da linha do texto',
	textLetterSpacing: 'Espaçamento entre letras do texto',
	codeHtmlDesc: 'O código escrito será inserido no ',
	codeHtmlDesc2: ' do seu projeto notice.',
	CSSDesc: 'Escreva algum código CSS para mudar a aparência do seu projeto',
	JavascriptDesc: 'Escreva algum código Javascript para mudar o comportamento do seu projeto',
	insightsDesc:
		'Direcione a estratégia de conteúdo e melhore o suporte ao cliente com dados sobre o comportamento do usuário.',
	publishing: 'Publicação',
	publish: 'Publicar',
	visitPage: 'Visitar página',
	newProject: 'Novo projeto',
	createNewProject: 'Criar novo projeto',
	newPage: 'Nova página',
	addNewPage: 'Adicionar uma nova página ao projeto atual',
	workspaceSettings: 'Configurações de Espaço de Trabalho',
	accountSettings: 'Configurações da Conta',
	supportAndCommunity: 'Suporte & Comunidade',
	signOut: 'Sair',
	whatIsNew: 'Novidades',
	inviteCollaborators: 'Convidar colaboradores',
	inviteCollaboratorsDescription:
		'Muitas mãos tornam o trabalho leve. Convide seus colegas para colaborarem juntos em seus projetos.',
	emailAddress: 'Endereço de email',
	admin: 'Administrador',
	editor: 'Editor',
	viewer: 'Visualizador',
	owner: 'Proprietário',
	close: 'Fechar',
	invite: 'Convidar',
	translationDescription: 'Traduza seu conteúdo em mais de 100 idiomas.',
	selectBlock: 'Você pode selecionar um bloco clicando no',
	selectProjectLanguage: 'Selecione o idioma padrão deste projeto',
	validate: 'Validar',
	selectLanguageHint: 'Dica: este é o idioma do seu projeto atual.',
	configureTranslation: 'Configurar tradução',
	translationStatus: 'Status da tradução',
	selected: 'Selecionado',
	translated: 'Traduzido',
	notTranslated: 'Não traduzido',
	translationOutOfDate: 'Tradução desatualizada',
	translateBlock: 'Traduzir bloco',
	markAsIncomplete: 'Marcar como incompleto',
	markAsComplete: 'Marcar como completo',
	markAsCompleteAndGoToNext: 'Marcar como completo e ir para o próximo',
	anotherNoticeTabIsOpened: 'Outra aba do Notice está aberta',
	pleaseReloadToAvoidMismatch:
		'Por favor, recarregue esta janela antes de usar para evitar incompatibilidade de dados.',
	reload: 'Recarregar',
	oopsNoResultsWereFound: 'Ops! Ainda não foram encontrados resultados.',
	tryAgainNoResults: 'Tente novamente com outro período.',
	configureYourTranslation: 'Configure sua tradução',
	allowUsersToChangeLang: 'Permita que os usuários mudem o idioma do seu projeto.',
	addsALangQueryLike: 'Adiciona uma consulta lang como',
	toYourProjectUrl: 'à URL do seu projeto.',
	addLanguageQueryToUrl: 'Adicionar parâmetro de idioma à URL',
	chooseADefaultLanguage: 'Escolha um idioma padrão',
	availableLanguages: 'idiomas disponíveis',
	ifYouWantMoreLanguages: 'Se você quiser mais idiomas',
	contactUs: 'Fale conosco',
	letUsKnow: 'nos avise.',
	languageSelectorWarning: 'O seletor de idiomas também pode ser gerenciado no layout do seu espaço superior por',
	clickingHere: 'clicando aqui',
	addNew: 'Adicionar Novo',
	translateTo: 'Traduzir para',
	translateThisPage: 'Traduzir esta página',
	stepByStepGuide: 'Guia passo a passo',
	manyHandsMakeLightWork: 'Muitas mãos tornam o trabalho mais leve',
	createAndCustomizeContent: 'Criar e personalizar conteúdo',
	clickOnPublish: 'Clique em publicar',
	deployItAnywhere: 'Distribua em qualquer lugar acessando a aba de Integrações',
	inviteColleaguesToCollaborate: 'Convide colegas para trabalharem juntos em seus projetos.',
	inviteYourTeam: 'Convide sua equipe',
	makeTheMostOfNotice: 'Aproveite ao máximo o Notice',
	getInTouchWithUs: 'Entre em contato conosco',
	getInTouchDescription:
		'Precisa de ajuda ou tem solicitações de recursos? Envie-nos uma mensagem ou junte-se à nossa comunidade no Slack.',
	accountSettingsDescription: 'Gerencie seu perfil, preferências e configurações de login',
	dashboardLanguage: 'Idioma do painel',
	updateEmail: 'Atualizar email',
	featureComingSoon: 'Recurso em breve...',
	signOnWithGoogle: 'Configure o login único com o Google e entre com um clique',
	yourGoogleAccountHasBeenUnlinked: 'Sua conta Google foi desvinculada com sucesso da sua conta.',
	unlinkAccount: 'Desvincular conta',
	linkAccount: 'Vincular conta',
	singleSignOnGithub: 'Configure o login único com o Github e entre com um clique',
	githubAccountHasBeenUnlinked: 'Sua conta do Github foi desvinculada com sucesso da sua conta.',
	signOutDescription: 'Você pode sair com segurança das sessões atuais e optar por entrar novamente mais tarde',
	accountDeletion: 'Exclusão de conta',
	accountDeletionDescription: 'Ao excluir sua conta pessoal, você apaga todos os dados associados.',
	deleteAccount: 'Excluir conta',
	deleteMyAccountSubject: 'Excluir minha conta',
	deleteMyAccountBody: 'Olá, quero excluir minha conta',
	settings: 'Configurações',
	account: 'Conta',
	myWorkspaces: 'Meus espaços de trabalho',
	workspace: 'Espaço de trabalho',
	collaborators: 'Colaboradores',
	plans: 'Planos',
	profilePicture: 'Foto de perfil',
	profilePictureDescription: 'Use uma imagem quadrada com um mínimo de 64 pixels',
	fullName: 'Nome completo',
	myWorkspacesDescription: `Visão global de todos os espaços de trabalho que você participa`,
	workspaces: 'Espaços de trabalho',
	created: 'Criado',
	manageWorkspaceProfile: 'Gerenciar perfil do espaço de trabalho',
	workspaceProfile: 'Perfil do espaço de trabalho',
	workspaceLogo: 'Logo do espaço de trabalho',
	displayName: 'Nome de exibição',
	workspaceDeletion: 'Exclusão do espaço de trabalho',
	workspaceDeletionDescription: 'Ao excluir seu espaço de trabalho, você apaga todos os dados associados.',
	deleteWorkspace: 'Excluir espaço de trabalho',
	storage: 'Armazenamento',
	storageDescription: `(imagens, vídeos, arquivos, ...)`,
	deleteWorkspaceDescription: 'Tem certeza de que deseja excluir este espaço de trabalho?',
	deleteWorkspaceWarning: 'Esta ação não pode ser desfeita.',
	cancel: 'Cancelar',
	confirm: 'Confirmar',
	visits: 'Visitas',
	statistics: 'Estatísticas',
	visitsByTimeSpan: 'Visitas por intervalo de tempo',
	location: 'Localização',
	locationDescription: 'A localização dos seus visitantes',
	device: 'Dispositivo',
	deviceDescription: 'O dispositivo usado pelos seus visitantes',
	browser: 'Navegador',
	browserDescription: 'O navegador usado pelos seus visitantes',
	OSdescription: 'O sistema operacional usado pelos seus visitantes',
	integration: 'Integração',
	hosting: 'Hospedagem',
	noticeDomain: 'Domínio Notice',
	noticeDomainDescription: 'Altere o nome do domínio hospedado pelo Notice.',
	allowedCharacters: 'Caracteres permitidos',
	letters: 'letras',
	numbers: 'números',
	and: 'e',
	domainName: 'Nome de domínio',
	customDomainDescription: 'Adicione seu próprio domínio personalizado e vincule-o ao seu projeto.',
	customDomain: 'Domínio personalizado',
	customDomainMissing: `Atualmente você não tem um domínio personalizado vinculado a este projeto`,
	customDomainPresent: `Atualmente você tem um domínio personalizado vinculado a este projeto`,
	configure: 'Configurar',
	whatDomainWouldYouLikeToLink: 'Qual domínio você gostaria de vincular?',
	hostnameIsInvalid: 'Nome do host inválido. Apenas subdomínios são permitidos.',
	mustOwnSubdomainAndAbilityToEditDNS:
		'Você deve possuir o subdomínio e ter a capacidade de editar seus registros DNS.',
	configureDNS: 'Configurar DNS',
	others: 'Outros',
	webflowIntegration: 'Adicione blocos Notice ao seu site Webflow com um único clique.',
	wordpressIntegration: 'Adicione o Plugin Notice para potencializar sua experiência no Wordpress.',
	shopifyIntegration: 'Ofereça uma excelente experiência ao cliente usando o Plugin Notice em sua loja.',
	umsoIntegration: 'Adicione blocos Notice ao site Umso e obtenha insights do seu público.',
	wixIntegration: 'Integrar o Notice no Wix é fácil. Basta adicionar um bloco de integração e pronto!',
	squarespaceIntegration:
		'É rápido, como sempre. Adicione um bloco de código e cole o seu ID Notice para exibir seu conteúdo.',
	unicornIntegration: 'Ganho rápido para melhorar e personalizar seu site com blocos inteligentes.',
	reactIntegration: 'Blocos Notice facilmente integrados ao React em apenas um passo.',
	nextIntegration: 'Para os amantes do framework frontend SSR Next.js, integração tranquila.',
	vueIntegration: 'Integre o Notice dentro do seu projeto Vue.js em menos de um minuto.',
	nuxtIntegration: 'Para os amantes do framework SSR Nuxt, integração tranquila.',
	linkIntegration: `A solução mais fácil, apenas compartilhe o link! Você nem precisa de um site.`,
	htmlIntegration: `A solução ideal para sites se você não encontrar seu framework específico.`,
	iframeIntegration: 'Fácil de usar, iframes se encaixam em qualquer lugar, até em aplicativos móveis.',
	rawJSONIntegration: 'Para usuários avançados que desejam controle total sobre seus projetos.',
	qrcodeIntegration: `Seu conteúdo na ponta dos dedos dos usuários! Compartilhe seu próprio código QR :)`,
	integrationsDescription: 'Aumente sua visibilidade compartilhando e integrando seu Notice em qualquer lugar.',
	categories: 'Categorias',
	all: 'Todos',
	needADifferentIntegrationAndCannotFindItHere: 'Precisa de uma integração diferente e não consegue encontrá-la aqui?',
	shareables: 'Compartilháveis',
	useTemplates: 'Usar Modelos',
	useAIGeneration: 'Usar Geração por IA',
	selectProjectTip: 'Você pode alternar entre geração por IA e modelos',
	preFilledTemplate: 'Modelo pré-preenchido',
	helpCenter: 'Central de Ajuda',
	termsOfuse: 'Termos de Uso',
	privacyPolicy: 'Política de Privacidade',
	jobBoard: 'Quadro de Empregos',
	getStarted: 'Tutorial',
	changelog: 'Registro de Mudanças',
	missionAndValues: 'Missão e Valores',
	investorsReport: 'Relatório para Investidores',
	startFromScratch: 'Começar do zero',
	helpOurAIGenerateYour: 'Ajude nossa IA a gerar seu',
	provideYourWebsiteURL: `Forneça a URL do seu site existente`,
	weFoundAWebsite: `Encontramos um site vinculado ao seu endereço de e-mail`,
	makeSureProvidedWebsiteAlreadyExists: `Certifique-se de que o site fornecido já existe`,
	AIExplanation: `Nossa IA analisa o site fornecido e gera um customizado`,
	basedOnTheWebsiteInformation: `com base nas informações do site.`,
	youCanUseAnyExistingURL: `Você pode usar qualquer URL existente.`,
	enhanceYourGeneration: `Você pode melhorar sua geração adicionando mais instruções`,
	giveInstructions: `Dê instruções para gerar seu`,
	makeSureThisPromptIsMatching: `Por favor, certifique-se de que este prompt corresponde ao tipo de projeto selecionado`,
	writeItInFrenchOnlyUsePastTense: `Exemplo: Escreva em Francês, usando apenas o tempo passado`,
	backToList: `Voltar à lista`,
	pricingDescription: 'Nossa precificação é direta e alinhada com os objetivos do seu negócio.',
	monthlyTokenAmount: 'Quantidade mensal de tokens',
	billingPeriod: 'Período de faturamento',
	monthly: 'Mensal',
	yearly: 'Anual',
	oneMonthFree: '1 mês grátis',
	customizeYourNewContentsHome: 'Personalize a casa do seu novo conteúdo',
	manageSmartContentForYourCompany: 'Gerencie conteúdo inteligente para sua empresa',
	activateContentSynergiesForYourTeam: 'Ative sinergias de conteúdo para sua equipe',
	forThoseNeedingAnEnterpriseGradeSolution: 'Para aqueles que precisam de uma solução de nível empresarial',
	letsTalk: 'Vamos conversar',
	numberOfCollaborators: 'Número de colaboradores',
	numberOfWorkspaces: 'Número de espaços de trabalho',
	integrateAnywhere: 'Integrar em qualquer lugar',
	removeNoticeBranding: 'Remover marca Notice',
	aiAssistant: 'Assistente de IA',
	customSupportAndHelp: 'Suporte e ajuda personalizados',
	premiumCdn: 'CDN Premium',
	ssoEnabled: 'SSO habilitado',
	onPremiseData: 'Dados On-Premise',
	contentAndSeoAudit: 'Auditoria de conteúdo e SEO',
	downgrade: 'Rebaixar',
	newWorkspace: 'Novo espaço de trabalho',
	createANewWorkspace: 'Criar um novo espaço de trabalho',
	enterNameOfNewWorkspace: 'Digite o nome do seu novo espaço de trabalho',
	create: 'Criar',
	signIn: 'Entrar',
	signInDescription: 'Entre rapidamente usando uma de suas contas sociais, ou use seu e-mail de trabalho.',
	signUp: 'Registrar',
	continueWithGoogle: 'Continuar com o Google',
	continueWithGithub: 'Continuar com o Github',
	orSignInUsingWorkEmail: 'Ou entre usando seu e-mail de trabalho',
	enterWorkEmail: 'Digite seu e-mail de trabalho',
	enterTemporaryCode: 'Digite o código temporário',
	weJustSentYouATemporaryLoginCode: 'Acabamos de enviar um código de login temporário.',
	pleaseCheckYourInbox: 'Por favor, verifique sua caixa de entrada.',
	alreadyHaveAnAccountSignIn: 'Já tem uma conta? Entrar',
	continueWithLoginCode: 'Continuar com o código de login',
	continueWithEmail: 'Continuar com e-mail',
	selectYourProject: 'Selecione seu projeto',
	chooseYourIntegration: 'Escolha a sua integração',
	publishingYourProject: 'Publicando seu projeto',
	projectCreated:
		'Seu projeto Notice foi criado! Adicione este novo projeto ao seu site usando uma de nossas integrações ou diretamente através do link pré-gerado para você.',
	signInMethods: 'Métodos de entrada',
	signInMethodsDescription: 'Atualize o e-mail usado para entrar na sua conta',
	joinOurSlackCommunityForUpdatesAndFeedback:
		'Junte-se à nossa comunidade no Slack para atualizações e feedback, e conecte-se conosco nas redes sociais.',
	joinSlack: 'Entrar no Slack',
	joinTheAcademy: 'Junte-se à Academia',
	readOurDoc: 'Leia nossa documentação',
	checkOurTutorials: 'Confira nossos tutoriais',
	sendUsAnEmail: 'Envie-nos um e-mail',
	pleaseEnterYourFirstName: 'Por favor, insira seu primeiro nome.',
	pleaseEnterYourLastName: 'Por favor, insira seu sobrenome.',
	firstname: 'Primeiro nome',
	lastname: 'Sobrenome',
	pleasEnterAValidPhoneNumber: 'Por favor, insira um número de telefone válido.',
	phoneNumber: 'Número de telefone',
	pleaseEnterYourCompanyName: 'Por favor, insira o nome da sua empresa.',
	companyName: 'Nome da empresa',
	pleaseChooseYourCompanySize: 'Por favor, escolha o tamanho da sua empresa.',
	companySize: 'Tamanho da empresa',
	pleaseChooseYourRoleInTheCompany: 'Por favor, escolha o seu papel na empresa.',
	companyRole: 'Função na empresa',
	startCreating: 'Comece a criar !',
	welcomeToNotice: 'Bem-vindo ao Notice !',
	pleaseHelpUsWithForm: 'Por favor, ajude-nos no processo de fornecer a você a experiência completa do Notice.',
	preview: 'Visualização',
	rename: 'Renomear',
	duplicate: 'Duplicar',
	exportMarkdown: 'Exportar Markdown',
	delete: 'Excluir',
	exportJSON: 'Exportar JSON',
	type: 'Tipo',
	forCommands: 'para comandos',
	paragraph: 'Parágrafo',
	justWriteDownSomeText: 'Basta escrever um texto',
	basicBlocks: 'Blocos básicos',
	heading: 'Cabeçalho',
	bigSectionHeading: 'Cabeçalho de seção grande',
	mediumSectionHeading: 'Cabeçalho de seção média',
	smallSectionHeading: 'Cabeçalho de seção pequena',
	bulletedList: 'Lista com marcadores',
	organizeContentWithBullets: 'Organize o conteúdo com marcadores',
	numberedList: 'Lista numerada',
	createANumberedList: 'Crie uma lista numerada',
	captureACodeSnippet: 'Capture um trecho de código',
	hint: 'Dica',
	provideHelpfulInformation: 'Forneça informações úteis',
	quote: 'Citação',
	highlightASpecificPassageOfText: 'Destaque um trecho específico do texto',
	divider: 'Divisor',
	separateDifferentBlocks: 'Separe diferentes blocos',
	toDo: 'A fazer',
	keepTrackOfTasksOrItems: 'Mantenha o controle de tarefas ou itens',
	media: 'Mídia',
	image: 'Imagem',
	uploadAnImageFile: 'Faça o upload de um arquivo de imagem',
	document: 'Documento',
	uploadADocument: 'Faça o upload de um documento',
	video: 'Vídeo',
	addAVideo: 'Adicionar um vídeo',
	advancedBlocks: 'Blocos avançados',
	table: 'Tabela',
	organizeWithRowsAndColumns: 'Organize com linhas e colunas',
	expandable: 'Expansível',
	addACollapsableBlock: 'Adicione um bloco colapsável',
	textAIGeneration: 'Geração de texto por IA',
	letOurRobotCreateYourContent: 'Deixe nosso robô criar seu conteúdo',
	imageAIGeneration: 'Geração de imagem por IA',
	letOurRobotCreateYourImages: 'Deixe nosso robô criar suas imagens',
	javascript: 'Javascript',
	embedJavascript: 'Incorporar Javascript',
	youtube: 'Youtube',
	embedYoutubeVideos: 'Incorporar vídeos do Youtube',
	justCopyPasteTheLinkOfYourVideo:
		'Basta copiar e colar o link do seu vídeo em um parágrafo vazio para incorporar automaticamente um vídeo do Youtube. Exemplo de link: https://www.youtube.com/watch?v=m4fDm4rdUdk',
	embedLoomVideos: 'Incorporar vídeos do Loom',
	justCopyPasteLoomVideo:
		'Basta copiar e colar o link do seu vídeo em um parágrafo vazio para incorporar automaticamente um vídeo do Loom. Exemplo de link: https://www.loom.com/share/36656bc4afb84de2bb829183f46a1b40',
	embedVimeos: 'Incorporar vídeos do Vimeo',
	embedVimeosInstructions:
		'Basta copiar e colar o link do seu vídeo em um parágrafo vazio para incorporar automaticamente um vídeo do Vimeo. Exemplo de link: https://vimeo.com/251147627',
	embedAirtableInstructions:
		'Cole o link da sua visualização de tabela em um parágrafo vazio para incorporar automaticamente um AirTable. Exemplo de link: https://airtable.com/appeh8s8bwMI7JjlW/shro43JbOcXFQH0tQ/tblnrBMRpvfrcqkko',
	AIIsWriting: 'A IA está escrevendo...',
	Keep: 'Manter',
	Retry: 'Tentar novamente',
	DescribeWhatYouWantAI: 'Descreva o que você quer criar para a nossa IA',
	LetOurAICreate: 'Deixe a nossa IA criar a sua página',
	LetOurAICreateImage: 'Crie uma imagem inspirada nesta página',
	freeTrialEndsIn: 'Sua avaliação gratuita terminará em X dias.',
	AIIsGeneratingAnImageIdea: 'A IA está gerando uma ideia de imagem...',
	AIIsGeneratingImage: 'A IA está gerando uma imagem...',
	GenImagePlaceholder: 'Um campo de girassóis ao final do dia. Ao estilo das pinturas de Van Gogh.',
	metadata: 'Metadados',
	pageMetadata: 'Metadados da página',
	giveInformationForSEO: 'Enriqueça esta página com informações para melhorar o SEO e as pré-visualizações',
	author: 'Autor',
	editMyName: 'Editar o meu nome',
	tags: 'Etiquetas',
	datePublished: 'Data de publicação',
	addATag: 'Adicionar uma etiqueta',
	advancedOptions: 'Opções Avançadas',
	tellGoogleExists: 'Informe ao Google que seu projeto existe',
	tellGoogleExistsDescription: 'Para indexar corretamente o seu projeto, você precisa verificar seu site em ',
	clickHereToFollowOurGuide: 'Clique aqui para seguir o nosso guia',
	explanationDateOfPublication: 'Ao definir uma data no futuro, a página ficará oculta até a data escolhida.',
	articleHiddenDateFuture: 'Este artigo está oculto porque a data está no futuro.',
	blockMenuChangeImageCover: 'Alterar Capa da Imagem',
	blockMenuAddImageCover: 'Adicionar Capa de Imagem',
	blockMenuDuplicate: 'Duplicar',
	blockMenuDelete: 'Excluir',
	blockMenuOnlyText: 'Apenas Texto',
	blockMenuWithImage: 'Com Imagem',
	blockMenuPageSummary: 'Resumo da Página',
	blockMenuBorder: 'Borda',
	blockMenuLayout: 'Layout',
	blockMenuDisplay: 'Exibição',
	blockMenuStyle: 'Estilo',
	subPageUpgradeSucessTitle: 'Atualização Bem-Sucedida',
	subPageUpgradeSuccessMsg:
		'Parabéns! 🎉 Sua conta foi atualizada com sucesso. Obrigado por escolher o Notice para melhorar a sua experiência!',
	subPageGoBack: 'Voltar à edição',
	deleteProjectDeleteProject: 'Excluir Projeto',
	deleteProjectAreYouSure: 'Tem certeza de que deseja excluir este projeto?',
	deleteWarning: 'Esta ação não pode ser desfeita.',
	cancelButton: 'Cancelar',
	confirmButton: 'Confirmar',
	deletePageDeletePage: 'Excluir Página',
	deletePageAreYouSure:
		'Esta ação irá excluir permanentemente esta página e todo o seu conteúdo relacionado, tem certeza de que deseja continuar?',
	pasteLinkHere: 'Cole o link aqui',
	addLink: 'Adicionar link',
	removeLink: 'Remover link',
	selectAnImage: 'Selecionar uma imagem',
	selectADocument: 'Selecionar um documento',
	selectAVideo: 'Selecionar um vídeo',
	selectAnAudio: 'Selecionar um áudio',
	dropYourFileHere: 'Solte seu arquivo aqui para iniciar o upload ou',
	anyDocTypeAccepted: 'Qualquer tipo de documento é aceito',
	acceptedTypes: 'Tipos aceitos',
	browseFiles: 'Navegar pelos arquivos',
	filterFiles: 'Filtrar arquivos',
	files: 'Arquivos',
	enterAnURL: 'Insira um URL',
}
