export const zhTW = {
	customization: '定制',
	translation: '翻譯',
	integrations: '整合',
	insights: '洞察',
	FreePlan: '免費方案',
	upgrade: '升級',
	yourProfile: '您的個人資料',
	general: '一般',
	layout: '佈局',
	theme: '主題',
	advanced: '進階',
	styling: '樣式',
	code: '代碼',
	billing: '賬單',
	aiSettings: 'AI 設置',
	aiSettingsDescription: '歡迎來到 AI 設置，這裡您可以控制 AI 如何為這個工作區生成內容',
	aiSettingSection1: '您做什麼工作？',
	aiSettingSection1Description: '幫助我們了解您的工作行業或公司重點。請簡要描述您的業務或專業。',
	aiSettingSection1Placeholder: '我經營一家專注於數位行銷策略和內容創建的創意機構',
	aiSettingSection2: '您的語氣是？',
	aiSettingSection2Description: '定義您希望工作區中文本的語氣。與我們分享符合您溝通風格的語氣。',
	aiSettingSection2Placeholder: '我們聽起來專業但友好，以易於連接的方式分享我們的專業知識',
	aiSettingSection3: '您偏好的寫作風格',
	aiSettingSection3Description:
		'提供一到兩個您寫作風格的例子，或您喜歡的寫作片段，我們的 AI 將作為其自己的風格進行調整。',
	aiSettingSection3Placeholder: '過度的理智可能是瘋狂，最瘋狂的是將生活視為它本來的樣子而不是它應該是的樣子',
	aiSettingsModelSettings: 'AI 模型設置',
	aiSettingModelSection: '選擇您的 AI 模型',
	aiSettingModelSectionDescription: '選擇最適合您偏好的 AI 生成模型。',
	aiSettingGPT4Tooltip: '更優化',
	aiSettingGPT3Tooltip: '更快速',
	edit: '編輯',
	save: '保存',
	skip: '跳過',
	changeAISettings: '更改 AI 設置',
	PleaseClickToEditTheSettings: '請點擊以編輯設置',
	billingDetailsAndInvoices: '賬單詳情與發票',
	overview: '概覽',
	currentPlan: '當前計劃',
	nextBillingOn: '下次賬單日期',
	nextBillingAmount: '下次賬單金額',
	numberOfProjects: '項目數量',
	reachesSubscriptionPage: '到達訂閱頁面',
	billingPageUpgradeButton: '賬單頁面升級按鈕',
	upgradeYourPlan: '升級您的方案',
	billingInfoAndPayment: '賬單信息與付款',
	manageAllYourBilling: '在這裡管理您所有的賬單信息和支付方式',
	manageBillingDetails: '管理賬單詳情',
	invoicesHistory: '發票歷史',
	invoiceID: '發票 ID',
	date: '日期',
	total: '總計',
	status: '狀態',
	invoiceReceipt: '發票/收據',
	download: '下載',
	noInfoAvailableYet: '尚無信息',
	hideBranding: '隱藏品牌標識',
	hideBrandingDescription: '隱藏您項目中的 Notice 品牌標識。',
	handleTitleTagTitle: '處理 <title /> 標籤',
	titleTagDescription: '啟用時，Notice 將處理您項目的 <title /> 標籤。',
	projectLogo: '項目標誌',
	projectLogoDescription: '您的項目標誌可以在項目的不同地方顯示。',
	faviconDescription: '將您的標誌用作網站圖標。',
	faviconWarning: (
		<span>
			您需要上傳一個 <b>項目標誌</b> 來啟用此功能。
		</span>
	),
	uploadImage: '上傳圖片',
	configureLogoRedirect: '配置標誌重定向的地址',
	navigationType: '導航類型',
	navigationTypeDescription: `利用 URL 中的 'page=' 值進行導航的查詢參數。斜杠將使用典型的 '/' 子文件夾。`,
	stopUserTracking: '停止用戶追蹤',
	stopUserTrackingDescription: 'Notice 將不收集數據以提供統計信息。',
	stopUserTrackingWarning: <span>統計儀表板將被禁用。</span>,
	headerSpace: '頭部空間',
	projectTitle: '項目標題',
	homeButton: '首頁按鈕',
	topSpace: '頂部空間',
	contactForm: '聯絡表單',
	emailToReceiveMessages: '接收消息的電子郵件',
	themeSwitch: '主題切換',
	languageSelector: '語言選擇器',
	breadcrumbNavigation: '麵包屑導航',
	timeToRead: '閱讀時間',
	shareToFacebook: '分享至 Facebook',
	shareToTwitter: '分享至 Twitter',
	shareToLinkedIn: '分享至 LinkedIn',
	leftSpace: '左側空間',
	navigationMenu: '導航菜單',
	rightSpace: '右側空間',
	anchorMenu: '錨點菜單',
	bottomSpace: '底部空間',
	bottomNavigation: '底部導航',
	readMoreArticles: '閱讀更多文章',
	setProjectTitle: '設置項目標題',
	setProjectTitleDescription: '在每個頁面的頂部空間顯示項目標題。',
	navMenuDesc: '位於左側的導航菜單，方便訪問您的項目。',
	searchDescription: '允許用戶在您的項目內搜索。您還將擁有',
	analyticsSupport: '分析支持',
	searchDescription2: '來自 Notice 為您的項目搜索提供的支持。',
	themeSwitchDescription: '您可以允許用戶更改項目的主題。您可以在',
	hereInsideColors: '這裡設置您的主題顏色。',
	languageSwitchDescription: '您可以允許用戶更改項目的語言。您可以在這裡配置您的翻譯',
	here: '這裡',
	allowNavDescription: '允許用戶使用導航菜單在頁面之間導航。',
	displayHomeButtonDescription: '顯示一個首頁按鈕，方便用戶導航到首頁。',
	timeToReadDescription: '顯示閱讀頁面的估計時間。',
	facebookShareDescription: '允許用戶在 Facebook 上分享您的文章。',
	twitterShareDescription: '允許用戶在 Twitter 上分享您的文章。',
	linkedinShareDescription: '允許用戶在 LinkedIn 上分享您的文章。',
	nextPrevDescription: '在頁面底部添加按鈕，以導航至下一頁和前一頁。',
	anchorRightMenuDescription: '在右側添加一個菜單，允許用戶在當前頁面內的子標題之間導航。',
	allowRecommendedArticlesDescription: '允許用戶閱讀與當前文章相關的更多文章。',
	pageTitle: '頁面標題',
	colors: '顏色',
	lightBgColor: '亮色背景顏色',
	lightFontColor: '亮色字體顏色',
	lightHighlightColor: '亮色突出顏色',
	darkBgColor: '暗色背景顏色',
	darkFontColor: '暗色字體顏色',
	darkHighlightColor: '暗色突出顏色',
	fonts: '字體',
	fontFamily: '字體家族',
	fontSize: '字體大小',
	spacing: '間距',
	blockPadding: '區塊填充',
	maxWidth: '最大寬度',
	maxWidthDescription: '設置主欄目的最大寬度',
	icons: '圖標',
	iconStroke: '圖標描邊寬度',
	headings: '標題',
	h1Weight: 'H1 字重',
	h1Size: 'H1 大小',
	h2Size: 'H2 大小',
	h2Weight: 'H2 字重',
	h3Size: 'H3 大小',
	h3Weight: 'H3 字重',
	headingsPadding: '標題填充',
	titleFontSize: '標題字體大小',
	fontFamilyDescription: `要探索字體，請訪問 <a href="https://fonts.google.com/" target="_blank">Google 字體。</a>`,
	text: '文本',
	textLineHeight: '文本行高',
	textLetterSpacing: '文本字母間距',
	codeHtmlDesc: '所寫代碼將被插入到您的 Notice 項目的',
	codeHtmlDesc2: '之中。',
	CSSDesc: '編寫一些 CSS 代碼來改變您的項目外觀',
	JavascriptDesc: '編寫一些 Javascript 代碼來改變您的項目行為',
	insightsDesc: '利用用戶行為數據驅動內容策略，改善客戶支持。',
	publishing: '發佈',
	publish: '發佈',
	visitPage: '訪問頁面',
	newProject: '新項目',
	createNewProject: '創建新項目',
	newPage: '新頁面',
	addNewPage: '在當前項目中添加新頁面',
	workspaceSettings: '工作區設置',
	accountSettings: '帳戶設置',
	supportAndCommunity: '支持與社區',
	signOut: '登出',
	whatIsNew: '最新動態',
	inviteCollaborators: '邀請合作者',
	inviteCollaboratorsDescription: '眾人拾柴火焰高。邀請您的同事共同合作您的項目。',
	emailAddress: '電子郵件地址',
	admin: '管理員',
	editor: '編輯',
	viewer: '查看者',
	owner: '擁有者',
	close: '關閉',
	invite: '邀請',
	translationDescription: '將您的內容翻譯成超過 100 種語言。',
	selectBlock: '點擊選擇一個區塊',
	selectProjectLanguage: '選擇這個項目的默認語言',
	validate: '驗證',
	selectLanguageHint: '提示：這是您當前項目的語言。',
	configureTranslation: '配置翻譯',
	translationStatus: '翻譯狀態',
	selected: '已選擇',
	translated: '已翻譯',
	notTranslated: '未翻譯',
	translationOutOfDate: '翻譯過時',
	translateBlock: '翻譯區塊',
	markAsIncomplete: '標記為未完成',
	markAsComplete: '標記為完成',
	markAsCompleteAndGoToNext: '標記為完成並進入下一個',
	anotherNoticeTabIsOpened: '另一個 Notice 標籤已打開',
	pleaseReloadToAvoidMismatch: '請重新加載此窗口以避免數據不匹配。',
	reload: '重新加載',
	oopsNoResultsWereFound: '哎呀！還沒有找到結果。',
	tryAgainNoResults: '嘗試使用另一個時段再試一次。',
	configureYourTranslation: '配置您的翻譯',
	allowUsersToChangeLang: '允許用戶更改您項目的語言。',
	addsALangQueryLike: '添加像',
	toYourProjectUrl: '這樣的語言查詢到您的項目 URL。',
	addLanguageQueryToUrl: '添加語言查詢參數到 URL',
	chooseADefaultLanguage: '選擇一個默認語言',
	availableLanguages: '可用语言',
	ifYouWantMoreLanguages: '如果您需要更多語言',
	contactUs: '聯絡我們',
	letUsKnow: '讓我們知道。',
	languageSelectorWarning: '語言選擇器也可以通過',
	clickingHere: '點擊這裡',
	addNew: '新增',
	translateTo: '翻譯成',
	translateThisPage: '翻譯此頁面',
	stepByStepGuide: '分步指南',
	manyHandsMakeLightWork: '眾人拾柴火焰高',
	createAndCustomizeContent: '創建和定制內容',
	clickOnPublish: '點擊發佈',
	deployItAnywhere: '通過轉到整合標籤隨處部署',
	inviteColleaguesToCollaborate: '邀請同事一起合作您的項目。',
	inviteYourTeam: '邀請您的團隊',
	makeTheMostOfNotice: '充分利用 Notice',
	getInTouchWithUs: '與我們聯繫',
	getInTouchDescription: '需要幫助或有功能請求？給我們發消息或加入我們在 Slack 的社群。',
	accountSettingsDescription: '管理您的個人資料、偏好設定和登入設置',
	dashboardLanguage: '儀表板語言',
	updateEmail: '更新電子郵件',
	featureComingSoon: '功能即將推出...',
	signOnWithGoogle: '設置使用 Google 單一登入，一鍵登入',
	yourGoogleAccountHasBeenUnlinked: '您的 Google 帳戶已成功與您的帳戶解除連接。',
	unlinkAccount: '取消連接帳戶',
	linkAccount: '連接帳戶',
	singleSignOnGithub: '設置使用 Github 單一登入，一鍵登入',
	githubAccountHasBeenUnlinked: '您的 Github 帳戶已成功與您的帳戶解除連接。',
	signOutDescription: '您可以安全地從當前會話登出，並選擇稍後再登入。',
	accountDeletion: '帳戶刪除',
	accountDeletionDescription: '刪除您的個人帳戶，將刪除所有相關數據。',
	deleteAccount: '刪除帳戶',
	deleteMyAccountSubject: '刪除我的帳戶',
	deleteMyAccountBody: '您好，我想刪除我的帳戶',
	settings: '設置',
	account: '帳戶',
	myWorkspaces: '我的工作區',
	workspace: '工作區',
	collaborators: '合作者',
	plans: '方案',
	profilePicture: '個人資料圖片',
	profilePictureDescription: '使用最小尺寸為 64 像素的正方形圖片',
	fullName: '全名',
	myWorkspacesDescription: '您參與的所有工作區的全局視圖',
	workspaces: '工作區',
	created: '已創建',
	manageWorkspaceProfile: '管理工作區資料',
	workspaceProfile: '工作區資料',
	workspaceLogo: '工作區標誌',
	displayName: '顯示名稱',
	workspaceDeletion: '工作區刪除',
	workspaceDeletionDescription: '刪除您的工作區，將刪除所有相關數據。',
	deleteWorkspace: '刪除工作區',
	storage: '儲存空間',
	storageDescription: '（圖片、視頻、文件等）',
	deleteWorkspaceDescription: '您確定要刪除這個工作區嗎？',
	deleteWorkspaceWarning: '此操作無法撤銷。',
	cancel: '取消',
	confirm: '確認',
	visits: '訪問',
	statistics: '統計',
	visitsByTimeSpan: '按時間跨度的訪問',
	location: '位置',
	locationDescription: '您的訪客所在位置',
	device: '設備',
	deviceDescription: '您的訪客使用的設備',
	browser: '瀏覽器',
	browserDescription: '您的訪客使用的瀏覽器',
	OSdescription: '您的訪客使用的操作系統',
	integration: '整合',
	hosting: '寄存',
	noticeDomain: 'Notice 域名',
	noticeDomainDescription: '更改 Notice 托管域名的名稱。',
	allowedCharacters: '允許的字符',
	letters: '字母',
	numbers: '數字',
	and: '和',
	domainName: '域名',
	customDomainDescription: '添加您自己的自定義域名並將其連接到您的項目。',
	customDomain: '自定義域名',
	customDomainMissing: '您目前沒有將自定義域名連接到這個項目',
	customDomainPresent: '您目前有一個自定義域名連接到這個項目',
	configure: '配置',
	whatDomainWouldYouLikeToLink: '您希望連接哪個域名？',
	hostnameIsInvalid: '主機名無效。僅允許子域名。',
	mustOwnSubdomainAndAbilityToEditDNS: '您必須擁有子域名並有能力編輯其 DNS 記錄。',
	configureDNS: '配置 DNS',
	others: '其他',
	webflowIntegration: '單擊添加 Notice 區塊到您的 Webflow 網站。',
	wordpressIntegration: '添加 Notice 插件以增強您在 Wordpress 上的體驗。',
	shopifyIntegration: '通過在您的商店使用 Notice 插件提供出色的客戶體驗。',
	umsoIntegration: '添加 Notice 區塊到 Umso 網站，並從您的受眾那裡獲取見解。',
	wixIntegration: '將 Notice 整合到 Wix 很簡單。只需添加一個整合區塊就完成了！',
	squarespaceIntegration: '像往常一樣快速。添加一個代碼區塊並粘貼您的 Notice ID 以顯示您的內容。',
	unicornIntegration: '快速提升和個性化您的網站與智能區塊。',
	reactIntegration: 'Notice 區塊輕鬆整合到 React，只需一步。',
	nextIntegration: '對於 Next.js SSR 前端框架的愛好者來說，整合流暢。',
	vueIntegration: '在不到一分鐘的時間內將 Notice 整合到您的 Vue.js 項目中。',
	nuxtIntegration: '對於 Nuxt SSR 前端框架的愛好者來說，整合流暢。',
	linkIntegration: '最簡單的解決方案，只需分享鏈接！您甚至不需要一個網站。',
	htmlIntegration: '如果您沒有找到特定框架，這是網站的首選解決方案。',
	iframeIntegration: '易於使用，iframe 適用於任何地方，甚至在移動應用中。',
	rawJSONIntegration: '適用於想要對其項目擁有完全控制權的高級用戶。',
	qrcodeIntegration: '您的內容在用戶指尖！分享您自己的 QR 碼 :)',
	integrationsDescription: '通過在各處分享和整合您的 Notice 提升您的能見度。',
	categories: '類別',
	all: '全部',
	needADifferentIntegrationAndCannotFindItHere: '需要不同的整合且在這裡找不到？',
	shareables: '可分享',
	useTemplates: '使用模板',
	useAIGeneration: '使用 AI 生成',
	selectProjectTip: '您可以在 AI 生成和模板之間切換',
	preFilledTemplate: '預填充模板',
	helpCenter: '幫助中心',
	termsOfuse: '使用條款',
	privacyPolicy: '隱私政策',
	jobBoard: '工作板',
	getStarted: '教程',
	changelog: '更改日誌',
	missionAndValues: '使命與價值',
	investorsReport: '投資者報告',
	startFromScratch: '從頭開始',
	helpOurAIGenerateYour: '幫助我們的 AI 生成您的',
	provideYourWebsiteURL: '提供您現有的網站 URL',
	weFoundAWebsite: '我們找到了一個與您的電子郵件地址關聯的網站',
	makeSureProvidedWebsiteAlreadyExists: '確保提供的網站已經存在',
	AIExplanation: '我們的 AI 將通過提供的網站進行查看，並基於網站信息生成一個自定義',
	basedOnTheWebsiteInformation: '。',
	youCanUseAnyExistingURL: '您可以使用任何現有的 URL。',
	enhanceYourGeneration: '通過添加更多指示來增強您的生成',
	giveInstructions: '給出指示以生成您的',
	makeSureThisPromptIsMatching: '請確保此提示與選定的項目類型匹配',
	writeItInFrenchOnlyUsePastTense: '例如：用法語書寫，只使用過去時',
	backToList: '返回列表',
	pricingDescription: '我們的定價簡單，並與您的業務目標保持一致。',
	monthlyTokenAmount: '每月代幣數量',
	billingPeriod: '計費周期',
	monthly: '每月',
	yearly: '每年',
	oneMonthFree: '1 個月免費',
	customizeYourNewContentsHome: '開始個人項目',
	manageSmartContentForYourCompany: '為您的公司管理智能內容',
	activateContentSynergiesForYourTeam: '為您的團隊啟動內容協同作用',
	forThoseNeedingAnEnterpriseGradeSolution: '為企業需求量身定制',
	letsTalk: '讓我們談談',
	numberOfCollaborators: '合作者數量',
	numberOfWorkspaces: '工作區數量',
	integrateAnywhere: '隨處整合',
	removeNoticeBranding: '移除 Notice 品牌標識',
	aiAssistant: 'AI 助手',
	customSupportAndHelp: '定制支持與幫助',
	premiumCdn: '高級 CDN',
	ssoEnabled: '啟用 SSO',
	onPremiseData: '現場數據',
	contentAndSeoAudit: '內容與 SEO 審計',
	downgrade: '降級',
	newWorkspace: '新工作區',
	createANewWorkspace: '創建一個新工作區',
	enterNameOfNewWorkspace: '輸入您的新工作區名稱',
	create: '創建',
	signIn: '登入',
	signInDescription: '使用您的社交帳戶快速登入，或使用您的工作電子郵件。',
	signUp: '註冊',
	continueWithGoogle: '繼續使用 Google',
	continueWithGithub: '繼續使用 Github',
	orSignInUsingWorkEmail: '或使用您的工作電子郵件登入',
	enterWorkEmail: '輸入您的工作電子郵件',
	enterTemporaryCode: '輸入臨時代碼',
	weJustSentYouATemporaryLoginCode: '我們剛剛向您發送了一個臨時登入代碼。',
	pleaseCheckYourInbox: '請檢查您的收件箱。',
	alreadyHaveAnAccountSignIn: '已經有帳戶？登入',
	continueWithLoginCode: '繼續使用登入代碼',
	continueWithEmail: '繼續使用電子郵件',
	selectYourProject: '選擇您的項目',
	chooseYourIntegration: '選擇您的整合',
	publishingYourProject: '發佈您的項目',
	projectCreated:
		'您的 Notice 項目已創建！使用我們的整合之一將這個新項目添加到您的網站，或直接使用為您生成的預生成鏈接。',
	signInMethods: '登入方法',
	signInMethodsDescription: '更新用於登入您帳戶的電子郵件',
	joinOurSlackCommunityForUpdatesAndFeedback: '加入我們的 Slack 社群以獲取更新和反饋，並在社交媒體上與我們聯繫。',
	joinSlack: '加入 Slack',
	joinTheAcademy: '加入學院',
	readOurDoc: '閱讀我們的文件',
	checkOurTutorials: '查看我們的教程',
	sendUsAnEmail: '給我們發郵件',
	pleaseEnterYourFirstName: '請輸入您的名字。',
	pleaseEnterYourLastName: '請輸入您的姓氏。',
	firstname: '名字',
	lastname: '姓氏',
	pleasEnterAValidPhoneNumber: '請輸入有效的電話號碼。',
	phoneNumber: '電話號碼',
	pleaseEnterYourCompanyName: '請輸入您的公司名稱。',
	companyName: '公司名稱',
	pleaseChooseYourCompanySize: '請選擇您的公司規模。',
	companySize: '公司規模',
	pleaseChooseYourRoleInTheCompany: '請選擇您在公司中的角色。',
	companyRole: '公司角色',
	startCreating: '開始創建！',
	welcomeToNotice: '歡迎來到 Notice！',
	pleaseHelpUsWithForm: '請幫助我們完成為您提供完整 Notice 體驗的過程。',
	preview: '預覽',
	rename: '重命名',
	duplicate: '複製',
	exportMarkdown: '導出 Markdown',
	delete: '刪除',
	exportJSON: '導出 JSON',
	type: '類型',
	forCommands: '命令',
	paragraph: '段落',
	justWriteDownSomeText: '只需寫下一些文字',
	basicBlocks: '基礎區塊',
	heading: '標題',
	bigSectionHeading: '大節標題',
	mediumSectionHeading: '中節標題',
	smallSectionHeading: '小節標題',
	bulletedList: '項目符號列表',
	organizeContentWithBullets: '使用項目符號組織內容',
	numberedList: '編號列表',
	createANumberedList: '創建一個編號列表',
	captureACodeSnippet: '捕獲代碼片段',
	hint: '提示',
	provideHelpfulInformation: '提供有用的信息',
	quote: '引用',
	highlightASpecificPassageOfText: '突出顯示特定文本段落',
	divider: '分隔線',
	separateDifferentBlocks: '分隔不同的區塊',
	toDo: '待辦事項',
	keepTrackOfTasksOrItems: '跟踪任務或項目',
	media: '媒體',
	image: '圖片',
	uploadAnImageFile: '上傳圖片文件',
	document: '文檔',
	uploadADocument: '上傳文檔',
	video: '視頻',
	addAVideo: '添加視頻',
	advancedBlocks: '高級區塊',
	table: '表格',
	organizeWithRowsAndColumns: '使用行和列組織',
	expandable: '可展開',
	addACollapsableBlock: '添加一個可摺疊區塊',
	textAIGeneration: '文本 AI 生成',
	letOurRobotCreateYourContent: '讓我們的機器人為您創建內容',
	imageAIGeneration: '圖片 AI 生成',
	letOurRobotCreateYourImages: '讓我們的機器人為您創建圖片',
	javascript: 'Javascript',
	embedJavascript: '嵌入 Javascript',
	youtube: 'Youtube',
	embedYoutubeVideos: '嵌入 Youtube 視頻',
	justCopyPasteTheLinkOfYourVideo:
		'只需將您的視頻鏈接復制粘貼到空白段落中，即可自動嵌入 Youtube 視頻。示例鏈接：https://www.youtube.com/watch?v=m4fDm4rdUdk',
	embedLoomVideos: '嵌入 Loom 視頻',
	justCopyPasteLoomVideo:
		'只需將您的視頻鏈接復制粘貼到空白段落中，即可自動嵌入 Loom 視頻。示例鏈接：https://www.loom.com/share/36656bc4afb84de2bb829183f46a1b40',
	embedVimeos: '嵌入 Vimeo',
	embedVimeosInstructions:
		'只需將您的視頻鏈接復制粘貼到空白段落中，即可自動嵌入 Vimeo 視頻。示例鏈接：https://vimeo.com/251147627',
	embedAirtableInstructions:
		'將您的表格視圖鏈接粘貼到空白段落中，即可自動嵌入 AirTable。示例鏈接：https://airtable.com/appeh8s8bwMI7JjlW/shro43JbOcXFQH0tQ/tblnrBMRpvfrcqkko',
	AIIsWriting: 'AI 正在寫作...',
	Keep: '保留',
	Retry: '重試',
	DescribeWhatYouWantAI: '向我們的 AI 描述您想創建的內容',
	LetOurAICreate: '讓我們的 AI 為您的頁面創建內容',
	LetOurAICreateImage: '創建靈感來自此頁面的圖片',
	freeTrialEndsIn: '您的免費試用將在 X 天後結束。',
	AIIsGeneratingAnImageIdea: 'AI 正在生成圖片創意...',
	AIIsGeneratingImage: 'AI 正在生成圖片...',
	GenImagePlaceholder: '一片向日葵田在日落時分。以梵高畫風呈現。',
	metadata: '元數據',
	pageMetadata: '頁面元數據',
	giveInformationForSEO: '豐富此頁面的信息以改善 SEO 和預覽',
	author: '作者',
	editMyName: '編輯我的名字',
	tags: '標籤',
	datePublished: '發佈日期',
	addATag: '添加標籤',
	advancedOptions: '高級選項',
	tellGoogleExists: '告訴 Google 您的項目存在',
	tellGoogleExistsDescription: '為了正確索引您的項目，您需要在',
	clickHereToFollowOurGuide: '點擊這裡跟隨我們的指南',
	explanationDateOfPublication: '設置未來日期將隱藏頁面，直到選定的日期。',
	articleHiddenDateFuture: '由於日期設在未來，這篇文章被隱藏',
	blockMenuChangeImageCover: '更改圖像封面',
	blockMenuAddImageCover: '添加圖像封面',
	blockMenuDuplicate: '複製',
	blockMenuDelete: '刪除',
	blockMenuOnlyText: '僅文字',
	blockMenuWithImage: '包含圖像',
	blockMenuPageSummary: '頁面摘要',
	blockMenuBorder: '邊框',
	blockMenuLayout: '佈局',
	blockMenuDisplay: '顯示',
	blockMenuStyle: '風格',
	subPageUpgradeSucessTitle: '升級成功',
	subPageUpgradeSuccessMsg: '恭喜！🎉 您的帳戶已成功升級。感謝您選擇Notice來提升您的體驗！',
	subPageGoBack: '返回編輯',
	deleteProjectDeleteProject: '刪除專案',
	deleteProjectAreYouSure: '您確定要刪除這個專案嗎？',
	deleteWarning: '此操作無法撤銷。',
	cancelButton: '取消',
	confirmButton: '確認',
	deletePageDeletePage: '刪除頁面',
	deletePageAreYouSure: '此操作將永久刪除此頁面及其所有相關內容，您確定要繼續嗎？',
	pasteLinkHere: '在此粘貼連結',
	addLink: '新增連結',
	removeLink: '移除連結',
	selectAnImage: '選擇圖片',
	selectADocument: '選擇文件',
	selectAVideo: '選擇視頻',
	selectAnAudio: '選擇音頻',
	dropYourFileHere: '將文件拖放到此處開始上傳或',
	anyDocTypeAccepted: '接受任何類型的文件',
	acceptedTypes: '接受的類型',
	browseFiles: '瀏覽文件',
	filterFiles: '篩選文件',
	files: '文件',
	enterAnURL: '輸入網址',
}
