export const zh = {
	customization: '定制',
	translation: '翻译',
	integrations: '集成',
	insights: '见解',
	FreePlan: '免费计划',
	upgrade: '升级',
	yourProfile: '你的个人资料',
	general: '一般',
	layout: '布局',
	theme: '主题',
	advanced: '高级',
	styling: '样式设计',
	code: '代码',
	billing: '账单',
	aiSettings: 'AI 设置',
	aiSettingsDescription: '欢迎来到 AI 设置，您可以控制我们的 AI 如何为这个工作区生成内容',
	aiSettingSection1: '你做什么？',
	aiSettingSection1Description: '帮助我们了解您的工作领域或您公司的重点。请简要描述您的业务或职业。',
	aiSettingSection1Placeholder: '我经营一家专注于数字营销策略和内容创作的创意机构',
	aiSettingSection2: '你的语气是什么？',
	aiSettingSection2Description: '定义您希望工作区中文本的语气。与我们分享符合您沟通风格的语气类型。',
	aiSettingSection2Placeholder: '我们听起来专业但友好，以一种容易连接的方式分享我们的专业知识',
	aiSettingSection3: '你喜欢的写作风格简介',
	aiSettingSection3Description: '提供一两个您写作风格的例子或您喜欢的文章片段，我们的 AI 将作为其自己的写作风格。',
	aiSettingSection3Placeholder: '过多的理智可能是疯狂，而最疯狂的是将生活看作它本来的样子而不是它应该是的样子',
	aiSettingsModelSettings: 'AI 模型设置',
	aiSettingModelSection: '选择您的 AI 模型',
	aiSettingModelSectionDescription: '选择最适合您偏好的 AI 生成模型。',
	aiSettingGPT4Tooltip: '更优化',
	aiSettingGPT3Tooltip: '更快',
	edit: '编辑',
	save: '保存',
	skip: '跳过',
	changeAISettings: '更改 AI 设置',
	PleaseClickToEditTheSettings: '请点击以编辑设置',
	billingDetailsAndInvoices: '账单详情和发票',
	overview: '概览',
	currentPlan: '当前计划',
	nextBillingOn: '下次账单日期',
	nextBillingAmount: '下次账单金额',
	numberOfProjects: '项目数量',
	reachesSubscriptionPage: '到达订阅页面',
	billingPageUpgradeButton: '账单页面升级按钮',
	upgradeYourPlan: '升级您的计划',
	billingInfoAndPayment: '账单信息和支付',
	manageAllYourBilling: '在这里管理您所有的账单信息和支付方式',
	manageBillingDetails: '管理账单详情',
	invoicesHistory: '发票历史',
	invoiceID: '发票 ID',
	date: '日期',
	total: '总计',
	status: '状态',
	invoiceReceipt: '发票/收据',
	download: '下载',
	noInfoAvailableYet: '暂无信息',
	hideBranding: '隐藏品牌',
	hideBrandingDescription: '在您的项目中隐藏 Notice 品牌。',
	handleTitleTagTitle: '处理 <title /> 标签',
	titleTagDescription: '启用后，Notice 将处理您项目的 <title /> 标签。',
	projectLogo: '项目徽标',
	projectLogoDescription: '您的项目徽标可以在项目的不同位置显示。',
	faviconDescription: '将您的徽标用作网站图标。',
	faviconWarning: '您需要上传上方的 <b>项目徽标</b> 才能启用此功能。',
	uploadImage: '上传图片',
	configureLogoRedirect: '配置徽标重定向的地址',
	navigationType: '导航类型',
	navigationTypeDescription: `查询参数将使用 URL 中的 'page=' 值来处理导航。斜杠将使用经典的 '/' 子文件夹。`,
	stopUserTracking: '停止用户跟踪',
	stopUserTrackingDescription: 'Notice 将不会收集数据以提供统计信息。',
	stopUserTrackingWarning: '统计信息仪表板将被禁用。',
	headerSpace: '头部空间',
	projectTitle: '项目标题',
	homeButton: '主页按钮',
	topSpace: '顶部空间',
	contactForm: '联系表单',
	emailToReceiveMessages: '接收消息的电子邮箱',
	themeSwitch: '主题切换',
	languageSelector: '语言选择器',
	breadcrumbNavigation: '面包屑导航',
	timeToRead: '阅读时间',
	shareToFacebook: '分享至 Facebook',
	shareToTwitter: '分享至 Twitter',
	shareToLinkedIn: '分享至 LinkedIn',
	leftSpace: '左侧空间',
	navigationMenu: '导航菜单',
	rightSpace: '右侧空间',
	anchorMenu: '锚点菜单',
	bottomSpace: '底部空间',
	bottomNavigation: '底部导航',
	readMoreArticles: '阅读更多文章',
	setProjectTitle: '设置项目标题',
	setProjectTitleDescription: '将在每个页面的顶部空间显示项目标题。',
	navMenuDesc: '位于左侧的导航菜单，方便访问您的项目。',
	searchDescription: '允许用户在您的项目中搜索。您还将获得',
	analyticsSupport: '分析支持',
	searchDescription2: '来自 notice 的您项目搜索。',
	themeSwitchDescription: '您可以允许用户更改项目的主题。您可以在',
	hereInsideColors: '这里的颜色里设置您的主题。',
	languageSwitchDescription: '您可以允许用户更改项目的语言。您可以在',
	here: '这里',
	allowNavDescription: '允许用户使用导航菜单在页面之间导航。',
	displayHomeButtonDescription: '显示主页按钮，让用户导航到主页。',
	timeToReadDescription: '显示页面的预计阅读时间。',
	facebookShareDescription: '允许用户在 Facebook 上分享您的文章。',
	twitterShareDescription: '允许用户在 Twitter 上分享您的文章。',
	linkedinShareDescription: '允许用户在 LinkedIn 上分享您的文章。',
	nextPrevDescription: '在页面底部添加按钮，导航至下一页和上一页。',
	anchorRightMenuDescription: '在右侧添加一个菜单，允许用户在当前页面的子标题内导航。',
	allowRecommendedArticlesDescription: '允许用户阅读与当前文章相关的更多文章。',
	pageTitle: '页面标题',
	colors: '颜色',
	lightBgColor: '浅色背景颜色',
	lightFontColor: '浅色字体颜色',
	lightHighlightColor: '浅色高亮颜色',
	darkBgColor: '深色背景颜色',
	darkFontColor: '深色字体颜色',
	darkHighlightColor: '深色高亮颜色',
	fonts: '字体',
	fontFamily: '字体家族',
	fontSize: '字体大小',
	spacing: '间距',
	blockPadding: '块填充',
	maxWidth: '最大宽度',
	maxWidthDescription: '设置主列的最大宽度',
	icons: '图标',
	iconStroke: '图标描边宽度',
	headings: '标题',
	h1Weight: 'H1 字重',
	h1Size: 'H1 尺寸',
	h2Size: 'H2 尺寸',
	h2Weight: 'H2 字重',
	h3Size: 'H3 尺寸',
	h3Weight: 'H3 字重',
	headingsPadding: '标题填充',
	titleFontSize: '标题字体大小',
	fontFamilyDescription: `要探索字体，请访问 <a href="https://fonts.google.com/" target="_blank">Google Fonts.</a>`,
	text: '文本',
	textLineHeight: '文本行高',
	textLetterSpacing: '文本字母间距',
	codeHtmlDesc: '编写的代码将被插入到 ',
	codeHtmlDesc2: ' 您的 notice 项目中。',
	CSSDesc: '编写一些 CSS 代码来改变您的项目外观',
	JavascriptDesc: '编写一些 Javascript 代码来改变您的项目行为',
	insightsDesc: '通过用户行为数据驱动内容策略并改善客户支持。',
	publishing: '发布',
	publish: '发布',
	visitPage: '访问页面',
	newProject: '新项目',
	createNewProject: '创建新项目',
	newPage: '新页面',
	addNewPage: '在当前项目中添加新页面',
	workspaceSettings: '工作区设置',
	accountSettings: '帐户设置',
	supportAndCommunity: '支持和社区',
	signOut: '登出',
	whatIsNew: '最新动态',
	inviteCollaborators: '邀请协作者',
	inviteCollaboratorsDescription: '多人合作轻松工作。邀请您的同事一起合作您的项目。',
	emailAddress: '电子邮件地址',
	admin: '管理员',
	editor: '编辑',
	viewer: '查看者',
	owner: '所有者',
	close: '关闭',
	invite: '邀请',
	translationDescription: '将您的内容翻译成100多种语言。',
	selectBlock: '通过点击选择一个块',
	selectProjectLanguage: '选择这个项目的默认语言',
	validate: '验证',
	selectLanguageHint: '提示：这是您当前项目的语言。',
	configureTranslation: '配置翻译',
	translationStatus: '翻译状态',
	selected: '已选择',
	translated: '已翻译',
	notTranslated: '未翻译',
	translationOutOfDate: '翻译已过时',
	translateBlock: '翻译块',
	markAsIncomplete: '标记为未完成',
	markAsComplete: '标记为完成',
	markAsCompleteAndGoToNext: '标记为完成并转到下一个',
	anotherNoticeTabIsOpened: '另一个 Notice 标签页已打开',
	pleaseReloadToAvoidMismatch: '请在使用前重新加载此窗口，以避免数据不匹配。',
	reload: '重新加载',
	oopsNoResultsWereFound: '哎呀！还没有找到结果。',
	tryAgainNoResults: '尝试用另一个时间段再试一次。',
	configureYourTranslation: '配置您的翻译',
	allowUsersToChangeLang: '允许用户更改项目的语言。',
	addsALangQueryLike: '添加一个类似',
	toYourProjectUrl: '的语言查询到您的项目 URL。',
	addLanguageQueryToUrl: '将语言查询参数添加到 URL',
	chooseADefaultLanguage: '选择默认语言',
	availableLanguages: '可用语言',
	ifYouWantMoreLanguages: '如果您想要更多语言',
	contactUs: '联系我们',
	letUsKnow: '让我们知道。',
	languageSelectorWarning: '语言选择器也可以通过',
	clickingHere: '点击这里',
	addNew: '添加新的',
	translateTo: '翻译成',
	translateThisPage: '翻译此页面',
	stepByStepGuide: '一步一步的指南',
	manyHandsMakeLightWork: '众人拾柴火焰高',
	createAndCustomizeContent: '创建和定制内容',
	clickOnPublish: '点击发布',
	deployItAnywhere: '通过转到集成标签页在任何地方部署',
	inviteColleaguesToCollaborate: '邀请同事一起参与您的项目。',
	inviteYourTeam: '邀请您的团队',
	makeTheMostOfNotice: '充分利用 Notice',
	getInTouchWithUs: '与我们取得联系',
	getInTouchDescription: '需要帮助或有功能请求？给我们发消息或加入我们的 Slack 社区。',
	accountSettingsDescription: '管理您的个人资料、偏好和登录设置',
	dashboardLanguage: '仪表板语言',
	updateEmail: '更新电子邮件',
	featureComingSoon: '功能即将推出...',
	signOnWithGoogle: '设置单点登录（Google），一键登录',
	yourGoogleAccountHasBeenUnlinked: '您的 Google 账户已成功从您的账户中解绑。',
	unlinkAccount: '解除账户链接',
	linkAccount: '链接账户',
	singleSignOnGithub: '设置单点登录（Github），一键登录',
	githubAccountHasBeenUnlinked: '您的 Github 账户已成功从您的账户中解绑。',
	signOutDescription: '您可以安全地从当前会话中登出，并选择稍后重新登录',
	accountDeletion: '账户删除',
	accountDeletionDescription: '通过删除您的个人账户，您将删除所有关联数据。',
	deleteAccount: '删除账户',
	deleteMyAccountSubject: '删除我的账户',
	deleteMyAccountBody: '您好，我想删除我的账户',
	settings: '设置',
	account: '账户',
	myWorkspaces: '我的工作区',
	workspace: '工作区',
	collaborators: '协作者',
	plans: '计划',
	profilePicture: '头像',
	profilePictureDescription: '使用至少64像素的正方形图片',
	fullName: '全名',
	myWorkspacesDescription: `您加入的所有工作区的全局视图`,
	workspaces: '工作区',
	created: '已创建',
	manageWorkspaceProfile: '管理工作区配置文件',
	workspaceProfile: '工作区配置文件',
	workspaceLogo: '工作区徽标',
	displayName: '显示名称',
	workspaceDeletion: '工作区删除',
	workspaceDeletionDescription: '通过删除您的工作区，您将删除所有关联数据。',
	deleteWorkspace: '删除工作区',
	storage: '存储',
	storageDescription: '（图片、视频、文件等）',
	deleteWorkspaceDescription: '您确定要删除这个工作区吗？',
	deleteWorkspaceWarning: '此操作无法撤销。',
	cancel: '取消',
	confirm: '确认',
	visits: '访问量',
	statistics: '统计数据',
	visitsByTimeSpan: '时间跨度的访问量',
	location: '位置',
	locationDescription: '您的访客所在位置',
	device: '设备',
	deviceDescription: '您的访客所使用的设备',
	browser: '浏览器',
	browserDescription: '您的访客所使用的浏览器',
	OSdescription: '您的访客所使用的操作系统',
	integration: '集成',
	hosting: '托管',
	noticeDomain: 'Notice 域名',
	noticeDomainDescription: '更改 Notice 托管域名的名称。',
	allowedCharacters: '允许的字符',
	letters: '字母',
	numbers: '数字',
	and: '和',
	domainName: '域名',
	customDomainDescription: '添加您自己的自定义域名并将其链接到您的项目。',
	customDomain: '自定义域名',
	customDomainMissing: `您当前没有将自定义域名链接到此项目`,
	customDomainPresent: `您当前已将自定义域名链接到此项目`,
	configure: '配置',
	whatDomainWouldYouLikeToLink: '您希望链接哪个域名？',
	hostnameIsInvalid: '主机名无效。仅允许子域名。',
	mustOwnSubdomainAndAbilityToEditDNS: '您必须拥有该子域名并具有编辑其 DNS 记录的能力。',
	configureDNS: '配置 DNS',
	others: '其他',
	webflowIntegration: '一键将 Notice 区块添加到您的 Webflow 网站。',
	wordpressIntegration: '添加 Notice 插件以增强您在 Wordpress 上的体验。',
	shopifyIntegration: '通过在您的商店中使用 Notice 插件提供卓越的客户体验。',
	umsoIntegration: '将 Notice 区块添加到 Umso 网站，从您的观众中获取洞察。',
	wixIntegration: '将 Notice 集成到 Wix 是容易的。只需添加一个集成块，就搞定了！',
	squarespaceIntegration: '快速如往常。添加一个代码块并粘贴您的 Notice ID 来显示您的内容。',
	unicornIntegration: '快速提高和个性化您的网站体验，使用智能区块。',
	reactIntegration: '在 React 中轻松集成 Notice 区块，只需一步。',
	nextIntegration: '为 Next.js SSR 前端框架的爱好者，提供流畅集成。',
	vueIntegration: '在不到一分钟的时间内将 Notice 集成到您的 Vue.js 项目中。',
	nuxtIntegration: '为 Nuxt SSR 前端框架的爱好者，提供流畅集成。',
	linkIntegration: `最简单的解决方案，只需分享链接！您甚至不需要一个网站。`,
	htmlIntegration: `如果您没有找到特定框架，这是网站的首选解决方案。`,
	iframeIntegration: '易于使用，iframe 适用于任何地方，甚至在移动应用程序中。',
	rawJSONIntegration: '对于希望完全控制其项目的高级用户。',
	qrcodeIntegration: `您的内容触手可及！分享您自己的二维码 :)`,
	integrationsDescription: '通过在各处分享和集成您的 Notice 提升您的可见性。',
	categories: '类别',
	all: '所有',
	needADifferentIntegrationAndCannotFindItHere: '需要不同的集成，在这里找不到？',
	shareables: '可分享',
	useTemplates: '使用模板',
	useAIGeneration: '使用 AI 生成',
	selectProjectTip: '您可以在 AI 生成和模板之间切换',
	preFilledTemplate: '预填充的模板',
	helpCenter: '帮助中心',
	termsOfuse: '使用条款',
	privacyPolicy: '隐私政策',
	jobBoard: '工作板',
	getStarted: '教程',
	changelog: '更新日志',
	missionAndValues: '使命与价值',
	investorsReport: '投资者报告',
	startFromScratch: '从头开始',
	helpOurAIGenerateYour: '帮助我们的 AI 生成您的',
	provideYourWebsiteURL: `提供您现有的网站 URL`,
	weFoundAWebsite: `我们发现了一个与您的电子邮件地址相关联的网站`,
	makeSureProvidedWebsiteAlreadyExists: `确保提供的网站已经存在`,
	AIExplanation: `我们的 AI 会通过提供的网站并生成一个自定义`,
	basedOnTheWebsiteInformation: `基于网站信息。`,
	youCanUseAnyExistingURL: `您可以使用任何现有的 URL。`,
	enhanceYourGeneration: `通过添加更多指示来增强您的生成`,
	giveInstructions: `给出指示来生成您的`,
	makeSureThisPromptIsMatching: `请确保此提示与所选项目类型相匹配`,
	writeItInFrenchOnlyUsePastTense: `示例：用法语写，仅使用过去时态`,
	backToList: `返回列表`,
	pricingDescription: '我们的定价直接并与您的业务目标一致。',
	monthlyTokenAmount: '每月令牌数量',
	billingPeriod: '账单周期',
	monthly: '每月',
	yearly: '每年',
	oneMonthFree: '1个月免费',
	customizeYourNewContentsHome: '开始个人项目',
	manageSmartContentForYourCompany: '为您的公司管理智能内容',
	activateContentSynergiesForYourTeam: '为您的团队激活内容协同作用',
	forThoseNeedingAnEnterpriseGradeSolution: '为企业需求量身定制',
	letsTalk: '让我们谈谈',
	numberOfCollaborators: '协作者数量',
	numberOfWorkspaces: '工作区数量',
	integrateAnywhere: '任何地方集成',
	removeNoticeBranding: '移除 Notice 品牌',
	aiAssistant: 'AI 助手',
	customSupportAndHelp: '定制支持和帮助',
	premiumCdn: '高级 CDN',
	ssoEnabled: '启用 SSO',
	onPremiseData: '本地数据',
	contentAndSeoAudit: '内容和 SEO 审计',
	downgrade: '降级',
	newWorkspace: '新工作区',
	createANewWorkspace: '创建一个新的工作区',
	enterNameOfNewWorkspace: '输入您的新工作区的名称',
	create: '创建',
	signIn: '登录',
	signInDescription: '使用您的社交账户快速登录，或使用您的工作电子邮件。',
	signUp: '注册',
	continueWithGoogle: '继续使用 Google',
	continueWithGithub: '继续使用 Github',
	orSignInUsingWorkEmail: '或使用您的工作电子邮件登录',
	enterWorkEmail: '输入您的工作电子邮件',
	enterTemporaryCode: '输入临时代码',
	weJustSentYouATemporaryLoginCode: '我们刚刚向您发送了一个临时登录代码。',
	pleaseCheckYourInbox: '请检查您的收件箱。',
	alreadyHaveAnAccountSignIn: '已经有账户了？登录',
	continueWithLoginCode: '继续使用登录代码',
	continueWithEmail: '继续使用电子邮件',
	selectYourProject: '选择您的项目',
	chooseYourIntegration: '选择您的集成',
	publishingYourProject: '发布您的项目',
	projectCreated:
		'您的 Notice 项目已创建！使用我们的集成之一将此新项目添加到您的网站，或直接通过为您生成的预生成链接。',
	signInMethods: '登录方法',
	signInMethodsDescription: '更新用于登录您账户的电子邮件',
	joinOurSlackCommunityForUpdatesAndFeedback: '加入我们的 Slack 社区以获取更新和反馈，并与我们社交上联系。',
	joinSlack: '加入 Slack',
	joinTheAcademy: '加入学院',
	readOurDoc: '阅读我们的文档',
	checkOurTutorials: '查看我们的教程',
	sendUsAnEmail: '给我们发电子邮件',
	pleaseEnterYourFirstName: '请输入您的名字。',
	pleaseEnterYourLastName: '请输入您的姓氏。',
	firstname: '名字',
	lastname: '姓氏',
	pleasEnterAValidPhoneNumber: '请输入有效的电话号码。',
	phoneNumber: '电话号码',
	pleaseEnterYourCompanyName: '请输入您的公司名称。',
	companyName: '公司名称',
	pleaseChooseYourCompanySize: '请选择您的公司规模。',
	companySize: '公司规模',
	pleaseChooseYourRoleInTheCompany: '请选择您在公司中的角色。',
	companyRole: '公司角色',
	startCreating: '开始创建！',
	welcomeToNotice: '欢迎来到 Notice ！',
	pleaseHelpUsWithForm: '请帮助我们提供完整的 Notice 体验过程。',
	preview: '预览',
	rename: '重命名',
	duplicate: '复制',
	exportMarkdown: '导出 Markdown',
	delete: '删除',
	exportJSON: '导出 JSON',
	type: '类型',
	forCommands: '用于命令',
	paragraph: '段落',
	justWriteDownSomeText: '只需写下一些文本',
	basicBlocks: '基本区块',
	heading: '标题',
	bigSectionHeading: '大节标题',
	mediumSectionHeading: '中节标题',
	smallSectionHeading: '小节标题',
	bulletedList: '项目符号列表',
	organizeContentWithBullets: '使用项目符号组织内容',
	numberedList: '编号列表',
	createANumberedList: '创建一个编号列表',
	captureACodeSnippet: '捕捉代码片段',
	hint: '提示',
	provideHelpfulInformation: '提供有用的信息',
	quote: '引用',
	highlightASpecificPassageOfText: '突出显示特定文本段落',
	divider: '分隔符',
	separateDifferentBlocks: '分隔不同的区块',
	toDo: '待办事项',
	keepTrackOfTasksOrItems: '跟踪任务或项目',
	media: '媒体',
	image: '图片',
	uploadAnImageFile: '上传图片文件',
	document: '文档',
	uploadADocument: '上传文档',
	video: '视频',
	addAVideo: '添加视频',
	advancedBlocks: '高级区块',
	table: '表格',
	organizeWithRowsAndColumns: '使用行和列组织',
	expandable: '可展开',
	addACollapsableBlock: '添加一个可折叠区块',
	textAIGeneration: '文本 AI 生成',
	letOurRobotCreateYourContent: '让我们的机器人创建您的内容',
	imageAIGeneration: '图像 AI 生成',
	letOurRobotCreateYourImages: '让我们的机器人创建您的图像',
	javascript: 'Javascript',
	embedJavascript: '嵌入 Javascript',
	youtube: 'Youtube',
	embedYoutubeVideos: '嵌入 Youtube 视频',
	justCopyPasteTheLinkOfYourVideo:
		'只需复制粘贴您的视频链接到一个空白段落，即可自动嵌入 Youtube 视频。示例链接：https://www.youtube.com/watch?v=m4fDm4rdUdk',
	embedLoomVideos: '嵌入 Loom 视频',
	justCopyPasteLoomVideo:
		'只需复制粘贴您的视频链接到一个空白段落，即可自动嵌入 Loom 视频。示例链接：https://www.loom.com/share/36656bc4afb84de2bb829183f46a1b40',
	embedVimeos: '嵌入 Vimeo 视频',
	embedVimeosInstructions:
		'只需复制粘贴您的视频链接到一个空白段落，即可自动嵌入 Vimeo 视频。示例链接：https://vimeo.com/251147627',
	embedAirtableInstructions:
		'在一个空白段落中粘贴您的表格视图链接，即可自动嵌入 AirTable。示例链接：https://airtable.com/appeh8s8bwMI7JjlW/shro43JbOcXFQH0tQ/tblnrBMRpvfrcqkko',
	AIIsWriting: 'AI 正在写作...',
	Keep: '保留',
	Retry: '重试',
	DescribeWhatYouWantAI: '向我们的 AI 描述您想要创建的内容',
	LetOurAICreate: '让我们的 AI 创建您的页面',
	LetOurAICreateImage: '根据这个页面创建灵感图像',
	freeTrialEndsIn: '您的免费试用将在 X 天内结束。',
	AIIsGeneratingAnImageIdea: 'AI 正在生成图像想法...',
	AIIsGeneratingImage: 'AI 正在生成图像...',
	GenImagePlaceholder: '一片向日葵田在一天结束时。以梵高画作风格。',
	metadata: '元数据',
	pageMetadata: '页面元数据',
	giveInformationForSEO: '丰富此页面的信息，以提高 SEO 和预览效果',
	author: '作者',
	editMyName: '编辑我的名字',
	tags: '标签',
	datePublished: '发布日期',
	addATag: '添加标签',
	advancedOptions: '高级选项',
	tellGoogleExists: '告诉 Google 您的项目存在',
	tellGoogleExistsDescription: `要正确索引您的项目，您需要在 `,
	clickHereToFollowOurGuide: '点击这里按照我们的指南操作',
	explanationDateOfPublication: '设置将来的日期将隐藏该页面，直到选定的日期。',
	articleHiddenDateFuture: '由于日期在未来，本文被隐藏',
	blockMenuChangeImageCover: '更换图片封面',
	blockMenuAddImageCover: '添加图片封面',
	blockMenuDuplicate: '复制',
	blockMenuDelete: '删除',
	blockMenuOnlyText: '仅文本',
	blockMenuWithImage: '包含图片',
	blockMenuPageSummary: '页面摘要',
	blockMenuBorder: '边框',
	blockMenuLayout: '布局',
	blockMenuDisplay: '显示',
	blockMenuStyle: '样式',
	subPageUpgradeSucessTitle: '升级成功',
	subPageUpgradeSuccessMsg: '恭喜！🎉 您的账户已成功升级。感谢您选择Notice来提升您的体验！',
	subPageGoBack: '返回编辑',
	deleteProjectDeleteProject: '删除项目',
	deleteProjectAreYouSure: '您确定要删除这个项目吗？',
	deleteWarning: '此操作无法撤销。',
	cancelButton: '取消',
	confirmButton: '确认',
	deletePageDeletePage: '删除页面',
	deletePageAreYouSure: '此操作将永久删除此页面及其所有相关内容，您确定要继续吗？',
	pasteLinkHere: '在此粘贴链接',
	addLink: '添加链接',
	removeLink: '移除链接',
	selectAnImage: '选择图片',
	selectADocument: '选择文件',
	selectAVideo: '选择视频',
	selectAnAudio: '选择音频',
	dropYourFileHere: '将文件拖放到此处开始上传或',
	anyDocTypeAccepted: '接受任何类型的文件',
	acceptedTypes: '接受的类型',
	browseFiles: '浏览文件',
	filterFiles: '过滤文件',
	files: '文件',
	enterAnURL: '输入网址',
}
